### ISSUE TITLE
Installing java

### ISSUE THREAD

**Issue by frederickpek** [holzschu/a-shell#102]
How should I install java compiler and run java .class files with a-shell?
I would like to use commands like "javac Example.java" for compilation, "java Example" to run the file and even run jshell.
Any help would be appreciated, thanks!

**Comment by holzschu** [comment]
Hi, 
the short answer is you cannot, or at least not yet. 

The longer answer is that one would need the source of a Java compiler, and then cross-compile it for iOS. Execution is also going to be an issue, unless there is a Java compiler that produces WebAssembly.

**Comment by holzschu** [comment]
Hi, can I leave this issue open, so other users can comment? It gives me a sense of what is most needed by users (features get implemented if they are very much needed *and* more or less feasible, so there's no guarantee).

**Comment by amay5267** [comment]
Hi

Have you considered using Pico compiler - Java by Marcin Olawski?

**Comment by ZJ-Adram** [comment]
Hi. Any changes about java since yet? Don’t you steel plan to add it?
