### ISSUE TITLE
[Shortcuts] Execute shell commands never seems to execute

### ISSUE THREAD

**Issue by ixje** [holzschu/a-shell#119]
Any shortcut command I try to sent always ends up in just opening the a-shell app. The following "open the app to execute the commands?" options all open the app: default, run in extension and run in the app (yes all 3), see [screen recording](https://www.dropbox.com/s/jgrgt2v05g0no5l/RPReplay_Final1603034116.MP4?dl=0). 

I'm running iOS 13.3.1 (I don't want to update to 14) on an iPhone XR if it matters. I've reinstalled the app multiple times but no luck.

Any ideas what could cause this?

It feels like permissions, but I've accepted all prompts I got.

**Comment by holzschu** [comment]
Hi, 
that is extremely weird. I haven't been able to reproduce this behaviour on my end. 

What you state in the option, such as "Open in extension" should always be used (it is tested before we look at the content of the command). If you say "default", only then does it look at the command (and, for "pwd", the default behaviour is to run in extesion). 

There is another point: the shortcut opens the app, but does not execute the command (I don't see the current directory displayed on screen).

**Comment by ixje** [comment]
@holzschu yes indeed, the "no execution of `pwd` on screen" at all is where it started for me. The deviating behaviour for the "open the app" options is secondary to me, but might be directing us the actual root cause. 

1. Are you testing it with the same iOS version (I'm guessing the simulator could allow it)? 
I'm hoping to learn if I can exclude the iOS version from the list of causes.  
2. Are all config/permissions files stored in the application folder? 
The reason for asking is I want to know if a simple "hold + delete" actually clears all data or if there is anything left behind somewhere.

**Comment by ixje** [comment]
I opted to update iOS after all and now it works as expected.
