### ISSUE TITLE
[ Letter Key Repeat ] enable letter key repeat in ashell

### ISSUE THREAD

**Issue by chenxi65535** [holzschu/a-shell#120]
When using external keyboard, holding down letter key will only produce one letter. For example, when "k" is holding, "k" will show on screen rather than "kkkkkkkkkkkkkkkkkkkkkkkkk...".
This problem becomes critical when using the Vim editor. Because functions as navigating by "hjkl" is impossible, which makes it inconvinient to use.
After searching a lot of information online, I found that turning off letter key repeating is the default option of IPad OS(excluding arrow key or symbol key, they function well)
And I found that iVim does NOT have the issue, so I guess maybe there is an option for apps to enable the letter key repeating?

**Comment by holzschu** [comment]
The option "Enable caps-lock as Escape" in Settings has the side-effect of also enabling key repeating for external keyboards (basically, it bypasses the iPadOS handling of keys, and thus enables key repeating).

**Comment by chenxi65535** [comment]
Got it, thanks!
Maybe what we can do is waiting for Apple to fix this "Feature".

**Comment by holzschu** [comment]
From what I understand, "it's complicated". Multi-character input (Chinese, Japanese, Korean) interferes with repeating keyboards.
