### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by ongyx** [holzschu/a-shell#124]
When trying to use the lzma module in Python, this happens.

**Comment by holzschu** [comment]
Hi,
that makes sense: the lzma headers are not available for the iOS SDK, so the Python building process did not activate this module.

**Comment by ongyx** [comment]
Ok, thanks for clarifying. The `lzma` module wasn't required for what I wanted to do, so I made it an optional import (this [project](https://github.com/ongyx/mothman)).
