### ISSUE TITLE
Vers 1.6.1 Bug:  Ctrl-L inside Python leads to undefined status 

### ISSUE THREAD

**Issue by jaclu** [holzschu/a-shell#134]
If you start python
and hit Ctrl-L at the >>> prompt
The screen is cleared and you get a $ prompt 
Any input entered is echoed, however, nothing else happens
Ctrl-C / Ctrl-D / fg / exit  
have no effect.
Additional Ctrl-L clears the screen and gives a new $ prompt, but nothing can be done until app is restarted.

**Comment by holzschu** [comment]
Thanks for reporting this.
That bug has been present since the origin, I can't believe it took so long for someone to point it out.
It will be fixed in the next release.
