### ISSUE TITLE
Sleep Command

### ISSUE THREAD

**Issue by gbu117** [holzschu/a-shell#145]
Would it be possible to add sleep?

**Comment by holzschu** [comment]
That sounds interesting, and maybe it can be done using webAssembly, but what would it be used for?

**Comment by gbu117** [comment]
Well my use-case is not particularly sensible, but just so I don't have to bounce back to shortcuts and use "wait for n seconds".

**Comment by holzschu** [comment]
Ah, I forgot about Shortcuts. Yes, in combination with Shortcuts it makes sense.

**Comment by holzschu** [comment]
It will be in the next release.
