### ISSUE TITLE
Open Command - Accept Input From Stdin

### ISSUE THREAD

**Issue by gbu117** [holzschu/a-shell#150]
It would be great to be able to open a url from stdin in the context of a shortcut so the output of commands didn't have to be sent to the shortcuts app via the pasteboard to be opened using "Open URL". Sorry if I am opening too many issues!

**Comment by holzschu** [comment]
Hi, I think a combination of `xargs` and `openurl` should answer your question. `xargs` converts its standard input into the arguments of the next command: https://en.wikipedia.org/wiki/Xargs

**Comment by gbu117** [comment]
Thanks! I should have thought more :)
