### ISSUE TITLE
IPv6 problem. 

### ISSUE THREAD

**Issue by 3735943886** [holzschu/a-shell#160]
I cannot connect ssh on LTE(ipv6) environment. 
If I try connecting, it says strange ipv6 address instead of correct ipv4 address which I type. Ping works. 
iSH works fine with same condition. Screen shot attached. 
VPN was connected with OpenVPN. 

a Shell
![6C5750D5-932E-40E1-AC6D-84126E8A59C6](https://user-images.githubusercontent.com/9522390/103472491-859b8e80-4dd1-11eb-8da0-93f81db2ac49.jpeg)

iSH
![0ABA506A-5FED-4173-8847-AA2C66EE30D3](https://user-images.githubusercontent.com/9522390/103472522-f2af2400-4dd1-11eb-96f0-ee63983a6924.jpeg)

**Comment by holzschu** [comment]
Hi,
would you be willing to try the latest TestFlight version? It is built from OpenSSH, and appears to work with IPv6, but my tests are limited: https://testflight.apple.com/join/WUdKe3f4

**Comment by 3735943886** [comment]
This issue was resolved already. I think it was caused by bug of DNS resolving of iOS itself. Thank you.
