### ISSUE TITLE
How to interrupt command (CTRL-C)?

### ISSUE THREAD

**Issue by lifepillar** [holzschu/a-shell#168]
Nice project! Is there a way to interrupt a command without an external keyboard?

**Comment by manueldeprada** [comment]
I use a Python program that sometimes I want to interrupt. Ctrl C does not work in a-Shell, although it works inside other programs like Vim. 

In iSh works without problem with Python. Can this issue be fixed?

**Comment by holzschu** [comment]
As I said above: control-C in a-Shell sends an interrupt signal to the command running. Whether the command running is able to pick up that interrupt signal or not depends on the command running, and in which state it is.

In other words: control-C works for some commands, does not work for other commands, but that depends on the command. If it's in an infinite loop with no time to listen for interrupt signals, then it won't stop. 

The difference between iSh and a-Shell is that iSh runs an x86 interpreter, while a-Shell runs native code. The good side is that native code is much faster. The bad side is that it needs to go through the cleanup routines at the end of a command, it cannot be abruptly stopped.

**Comment by manueldeprada** [comment]
I see, thanks for the explanation. Python does not seem to be able to capture the KeyboardInterrupt exception.

I needed a way to halt a while loop in a python script, and this has become an impossible task with a-Shell. Ctrl-c does not work, but also there is no way of listening for normal keystrokes without using the blocking `input()` call.

I tried a separate thread, the keyboard library, the pyinput library, and the termios module. None of them worked. 

My use case is that I need to download a file again and again to download as much GBs as possible through my internet connection. At some point I want to stop it using the keyboard, but for now I will resign myself to force-close a-Shell.
