### ISSUE TITLE
How about renaming git command? (1.6.6 Build 132)

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#170]
I'm afraid that the new `git` command may break Vim with git-related plugins because it is not a true `git` command. So, how about renaming the command from `git` to something else? Thanks.

**Comment by holzschu** [comment]
If possible, I would rather take the opposite approach: tweak the git command until it works with Vim git-related plugins. 
That is one of my motivations: allow Vim users to clone Vim plugins directly in `.vim/pack/`

**Comment by kkk669** [comment]
Thank you @holzschu. Okay, I understand your thoughts.

> That is one of my motivations: allow Vim users to clone Vim plugins directly in .vim/pack/

Does renaming `git` command prevent them from doing that? If they just use it as a command line tool, I don't see any problem.

Let me describe what happened to me in more detail.

I usually share [my .vimrc and Vim plugins (git submodules)](https://github.com/kkk669/dotfiles) with a-Shell, other apps, and other computers, so if `executable('git')` returns `1`, git-related plugins I'm using will start working.

There's nothing wrong with that per se, but because of that, Vim and a-Shell will freeze when I edit a file in a git working directory.

I use the following git-related plugins:

- [fugitive.vim](https://github.com/tpope/vim-fugitive)
- [fern-git-status.vim](https://github.com/lambdalisue/fern-git-status.vim)
- [vim-gitgutter](https://github.com/airblade/vim-gitgutter)

I disabled them one by one, trying to figure out which one was the direct cause, and then it turns out that vim-gitgutter is.

My concern is that the same thing will happen to other users. Also, if a-Shell freezes as it did in my case, it is difficult to identify its cause.

----

By the way, I hope that a-Shell supports creating a symlink to an external directory. If that come true, I can use `.vimrc` and other files that is cloned by [Working Copy](https://workingcopyapp.com/) directly within a-Shell. It also supports Git submodules.

I already do the same thing in [iVim](https://github.com/terrychou/iVim) and [Blink Shell](https://github.com/blinksh/blink). iVim has `:iexdir` command and Blink Shell has `link-files` command.

Of course, it would be nice to have git commands in a-Shell itself.

**Comment by holzschu** [comment]
You are absolutely right, and I now understand your point. I'll remove dulwich in the next build, and instead add "alias" and access to external directories (I am thinking about "~name", where name is the name of the bookmarked directory).

**Comment by kkk669** [comment]
I think you don't need to remove dulwich. You can get around the `executable('git')` problem by simply renaming the current `git` to `dgit` or something else.

> instead add "alias" and access to external directories (I am thinking about "~name", where name is the name of the bookmarked directory).

Awesome! Thanks.
