### ISSUE TITLE
More keyboard shortcuts

### ISSUE THREAD

**Issue by kkk669** [holzschu/a-shell#171]
I think a-Shell still lacks some basic keyboard shortcuts, e.g. Ctrl+U, Ctrl+W, Ctrl+P, Ctrl+N, Ctrl+B, Ctrl+F, and so on. It would be great if they could be supported. Thanks.

**Comment by kkk669** [comment]
If no one disagrees with my opinion, I'll try to add those keyboard shortcuts based on [this commit](https://github.com/holzschu/a-shell/commit/b90656818860a1345347745e620abb9e67dacfc6) and send it as a PR over this weekend.

**Comment by holzschu** [comment]
I remember that someone else also requested more keyboard shortcuts, I just don't remember where. It's clearly worth doing, and I welcome the PR.

**Comment by kkk669** [comment]
@holzschu I couldn't find the issue you said above, but I've sent a PR #178. If you have a time, please check it out. I hope that it helps a-Shell users and you.
