### ISSUE TITLE
Correct value of $HOME environment variable

### ISSUE THREAD

**Issue by lifepillar** [holzschu/a-shell#174]
Currently, `$HOME` is set to `/private/.../<UUID>`. Shouldn't that be `/private/.../<UUID>/Documents` instead? To see the inconsistency, on a fresh install of a-Shell do the following:

```sh
echo $HOME
cd
pwd
```

The values output by the first and the last command are different.

**Comment by lifepillar** [comment]
This is an issue, for instance, for Vim. In my `vimrc` I have `set directory=~/.vim/swap`. But `~` is expanded to `/private/.../<UUID>` instead of `/private/.../<UUID>/Documents`, hence the swap directory is not found.

**Comment by holzschu** [comment]
Hi,
yes, `$HOME` is set by the system, to `/private/.../<UUID>`, but only `/private/.../<UUID>/Documents/` is user-writeable. It's an issue in several places. But the system also expects `$HOME` to be `/private/.../<UUID>`, for example to create temporary directories (to `$HOME/tmp/`), or to create cache files (in `$HOME/Library/Caches`). 

So i'd rather not change the value of `$HOME`, even though it's annoying.

In your `.vimrc`, you can check for the environment variable `TERM_PROGRAM` (it's set to `a-Shell`) to have a separate treatment for a-Shell.

**Comment by lifepillar** [comment]
I see. In fact, the same behaviour is exhibited by LibTerm and Blink. iVim has opted to change `$HOME`, though.

**Comment by holzschu** [comment]
It's not entirely surprising since a-Shell, LibTerm and Blink are all powered by [iOS_system](https://github.com/holzschu/ios_system/) (so are the terminal commands in iVim)

Both options have their pros and cons. I can understand why iVim did what it did.
