### ISSUE TITLE
Trackpad support for scrolling

### ISSUE THREAD

**Issue by sebnoumea** [holzschu/a-shell#186]
Hi,

It would be nice to be able to scroll using the 2 fingers gesture with a trackpad on iPadOS. iSH handles this well.
The workaround is to scroll with touch but it's not convenient when using the iPad in a desk setup fashion (stand, keyboard, trackpad).

Thanks !

**Comment by holzschu** [comment]
That's a great idea. I don't know how to do it, but I'll look for references.

**Comment by sebnoumea** [comment]
Merci bcp !

**Comment by kkk669** [comment]
Both iSH and Blink Shell use hterm and support scrolling by trackpad, so they might be worth a look.

**Comment by personalizedrefrigerator** [comment]
Something like #231 might fix this... I'm mot sure how much I like its approach, though (invisible text overlay that uses default, browser-implemented scrolling).

**Comment by personalizedrefrigerator** [comment]
Sorry! I linked this to #248 (which might partially fix this).
I think this should remain open for now...

**Comment by kkk669** [comment]
a-Shell 1.7.3 (169) can scroll with the trackpad, but it's not momentum scrolling and its direction is reversed. So, I feel some fixes are needed.

**Comment by personalizedrefrigerator** [comment]
> but it's not momentum scrolling
...interesting... I was getting momentum scrolling (and far too much of it!). I ended up setting the "time" it took for the scroll gesture to a very high number (`dt` is in seconds):

https://github.com/holzschu/a-shell/blob/0868ecd23bda2a82aceda34aea193ada3bfced2b/gestures.js#L576-L578

Note that this time is estimated -- I don't know how to get the actual time a **single** wheel event took.

> its direction is reversed.

Adding a negative sign here might fix that...

https://github.com/holzschu/a-shell/blob/0868ecd23bda2a82aceda34aea193ada3bfced2b/gestures.js#L570

...but it was only reversed in `man` and `vim` for me. In `man`/`vim`, a change is definitely needed. In this case, it's moving the cursor, not the view, so `dy` needs to be negated somewhere:

https://github.com/holzschu/a-shell/blob/0868ecd23bda2a82aceda34aea193ada3bfced2b/gestures.js#L570-L577
