### ISSUE TITLE
Unable to build python3_ios-PIL._imaging.xcframework

### ISSUE THREAD

**Issue by bummoblizard** [holzschu/a-shell#190]
Hello. Following the build steps, I have successfully built all Python frameworks except for `python3_ios-PIL._imaging.framework` and `python3_ios-zmq.backend.cffi._cffi.framework`. Here's [make_ios.log](https://github.com/holzschu/a-shell/files/6370287/make_ios.log) for reference. 

```
generating cffi module 'build/temp.macosx-11.0-arm64-3.9/zmq.backend.cffi._cffi.c'
building 'zmq.backend.cython._device' extension
creating build/temp.macosx-11.0-arm64-3.9/zmq
creating build/temp.macosx-11.0-arm64-3.9/zmq/backend
creating build/temp.macosx-11.0-arm64-3.9/zmq/backend/cython
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O3 -Wall -arch arm64 -miphoneos-version-min=14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -arch arm64 -miphoneos-version-min=14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -DCYTHON_PEP489_MULTI_PHASE_INIT=0 -DCYTHON_USE_DICT_VERSIONS=0 -O3 -Wall -I/Users/kenchung/Downloads/cpython/cpython -arch arm64 -miphoneos-version-min=14.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -DCYTHON_PEP489_MULTI_PHASE_INIT=0 -DCYTHON_USE_DICT_VERSIONS=0 -O3 -Wall -I/Users/kenchung/Downloads/cpython/cpython -DHAVE_SYS_UN_H=1 -Izmq/utils -I/Users/kenchung/Downloads/cpython/cpython/Library/include/python3.9 -c zmq/backend/cython/_device.c -o build/temp.macosx-11.0-arm64-3.9/zmq/backend/cython/_device.o
In file included from zmq/backend/cython/_device.c:628:
zmq/utils/zmq_compat.h:20:10: fatal error: 'zmq.h' file not found
#include "zmq.h"
         ^~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
```
It would also be cool if someone can provide me with a build of the two frameworks. :)

**Comment by holzschu** [comment]
For `zmq.h`, you will need to install the MacOS version of libzmq. 

For PIL, looking at the log file, I think the first clue is in the following line: 
`ld: warning: ignoring file /usr/local/Cellar/openjpeg/2.3.1/lib/libopenjp2.dylib, building for iOS-arm64 but attempting to link with file built for macOS-x86_64`

You have installed `openjpeg` and the compile script decided to use it. You'll need to tell the compile script to not use that  `openjpeg` library. Likewise, the compiler found and tried to use: 
- `/usr/local/lib/libwebp.dylib` 
- `/usr/local/lib/libwebpmux.dylib`
- `/usr/local/lib/libwebpdemux.dylib`
- `/usr/local/Cellar/little-cms2/2.11/lib/liblcms2.dylib`
- `/usr/local/opt/freetype/lib/libfreetype.dylib`
All of which are, of course, not compiled for iOS. 

Regarding providing builds of compiled frameworks, I would love to, but I have around 2000 cpython frameworks. I haven't found a way and place where I can automatically upload them. github actions and github release are not designed for that amount of packages.

**Comment by bummoblizard** [comment]
Thank you for your help! I will try to build it again.

Regarding uploading the binaries, wouldn't it be possible to compress the frameworks into a single zip file? (I'm not familiar with GitHub release)
