### ISSUE TITLE
Regression/JavaScript GUI: `jsc` document does not affect `hterm`

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#197]
Previously, `jsc script.js` ran [script.js] in the same `WebView` as `hterm`. This was very useful for styling `hterm` and displaying UI.

A solution might be adding an optional argument to `jsc`, like `--in-window`, that allows executing JavaScript in the same context as `hterm`.

**Comment by holzschu** [comment]
Ah yes, good point. This change was done mostly for webAssembly, so we can have interactive input. I like your suggestion of having an argument to keep running things in the main WkWebView.

**Comment by personalizedrefrigerator** [comment]
It looks like this has been fixed! Thank you!
