### ISSUE TITLE
`lua` immediately exits interactive mode

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#200]
![083B3297-B21B-4AEE-84C3-3AA93BE9BF7C](https://user-images.githubusercontent.com/46334387/117489095-086c5b80-af22-11eb-9bca-e5b7abc395ad.png)

When attempting to enter `lua`'s interactive mode, `lua` exits immediately after printing a prompt.

`echo "print(1)" | lua` works. `echo "print(3)" | lua -i` does not.

**Comment by holzschu** [comment]
Thanks a lot for the warning! I wonder when that error was introduced, and what's causing it.

**Comment by holzschu** [comment]
That issue should be fixed with build 156 (on TestFlight now).

**Comment by personalizedrefrigerator** [comment]
Can confirm that this has been fixed. Thank you!
