### ISSUE TITLE
Consider Updating `hterm`

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#203]
It looks like there are several new versions of `hterm` available (see also #201)!

## See 
 * https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/doc/ChangeLog.md
 * https://github.com/chromium/hterm

**Comment by personalizedrefrigerator** [comment]
Closing as this is really just a potential fix for other issues.

**Comment by holzschu** [comment]
Hi, build 164 has been updated to the latest version of hterm. All changes have been moved to `script.js`, so updating in the future will be easier.
