### ISSUE TITLE
ipython: Command not found

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#204]
## Version Information
 * Build 157
 * ipython works in build 154 but not in build 155

## Steps to reproduce
 * Run ipython in shell

**Comment by holzschu** [comment]
Fun one: the path is encoded as `#!/Users/.../bin/python3.9`, and the change introduced in build 155 translates that as "9" for the executable. Back to the drawing board.

**Comment by holzschu** [comment]
This is fixed with build 157.

**Comment by personalizedrefrigerator** [comment]
Can confirm that this has been fixed.
