### ISSUE TITLE
Copying .profile file from macOS to iCloud Drive to ~/Documents

### ISSUE THREAD

**Issue by ymgenesis** [holzschu/a-shell#205]
I'm trying to place a .profile I made on Mac into a-shell's ~/Documents without having to type it all up in vim on my iOS device.

Once I copy it to iCloud Drive from Mac, then pickFolder in a-shell to the iCloud Drive folder with the file in it, the file (named it testprofile) doesn't appear. ls -a shows a testprofile.icloud, but running cat on this just shows it's more of a plist-type file. 

I thought it had something to do with [this issue](https://www.sync.com/help/why-do-my-files-have-an-icloud-extension/), but that didn't solve my problem.

I guess that would mean any scripts I write on mac which conform to a-shell's limitations can't be copied from mac to drive to ~/Documents in this manor?

**Comment by holzschu** [comment]
I’m not sure I understand every step you took, but something with a .icloud suffix is usually a file that exists but has not yet been downloaded from iCloud. Clicking on it will force iCloud to download it.  
also, a-Shell only reads the `.profile` file from the home directory, not from the iCloud directory.
