### ISSUE TITLE
Feature Request: `xxd`

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#219]
It would be nice to have the `xxd` (hexdump utility) in `a-Shell`! Its source code is included in the Github mirror of Vim: 
* https://github.com/vim/vim/tree/master/src/xxd

It looks like [this mirror](https://github.com/lifuzu/xxd) has a copy of its `man` page.

**Comment by holzschu** [comment]
It compiles nicely to webAssembly, but it seems to have problems handling large files and redirection. Might be worth compiling to Arm instead, it's not like it would increase the size of the App binary much...

**Comment by holzschu** [comment]
The problem with WebAssembly and more (or other redirections) will remain, but since `xxd` is part of the Vim distribution and is already compiled when I compile Vim, I'll go with a native version instead of WebAssembly.

It's a bit annoying that I can't pipe webAssembly programs into less or more.

**Comment by personalizedrefrigerator** [comment]
Thank you!!!
