### ISSUE TITLE
`~/Documents/bin/foo.wasm`: foo: command not found (When in directory with `foo` executable)

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#221]
## Summary
 * All `*.wasm` binaries in `~/Documents/bin` are executable only with their `.wasm` extension. For example, **(edit this is only true if the current directory contains an executable with the same name. See comment below)**
```sh
$ ls ~/Documents/bin
[other output]
xxd.wasm
[other output]
$ xxd --help
xxd: command not found
$ xxd.wasm --help
Usage:
       xxd.wasm [options] [infile [outfile]]
    or
       xxd.wasm -r [-s [-]offset] [-c cols] [-ps] [infile [outfile]]
...
```

## Expected Behavior
 * I should be able to run `xxd` if I have `xxd.wasm` in my `~/Documents/bin` directory.

## Additional Information
 * Renaming `xxd.wasm` to `xxd` and marking it as executable still results in `command not found`.

**Comment by holzschu** [comment]
I am unable to reproduce the issue. It is strange.

**Comment by holzschu** [comment]
It could be that there is also an `xxd` somewhere in the PATH, on top of `xxd.wasm`. That would be one possible explanation for this behaviour.

**Comment by personalizedrefrigerator** [comment]
The directory I was testing this in contained an `xxd` WASM executable. `cd`ing out of that directory fixes the issue. 
In other words,
```sh
$ ls
Makefile        README.md       xxd             xxd.1           xxd.c
$ xxd --help
xxd: command not found
$ cd ../
$ ls
xxd.git
$ xxd --help
Usage:
       xxd.wasm [options] [infile [outfile]]
    or
       xxd.wasm -r [-s [-]offset] [-c cols] [-ps] [infile [outfile]]
Options:
...
```

**Comment by holzschu** [comment]
I'm glad the issue is solved. I need to work on identifying wasm executables without the suffix. It should be feasible.

**Comment by holzschu** [comment]
In the next release, we identify webAssembly files based on their signature (the first four bytes are "\0asm"). The suffix also works, but it's not required anymore.
