### ISSUE TITLE
`ipython`: Ctrl+D blocks I/O

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#222]
## Summary
 * Pressing `Ctrl+D` in `ipython` prints `Do you really want to exit? ([y]/n)` and does not accept further input. To continue using `a-Shell`, I need to restart the app.
   * My guess is that after pressing `ctrl+D`, `ipython` is no longer considered an interactive command...

## Expected Behavior
 * Ctrl+D should cause `ipython` to quit.

**Comment by holzschu** [comment]
Hi, thanks for reporting the issue. 
I've looked into it, and ipython prints the prompt, calls fgets to get the answer... and never gets the answer. It seems that the next input is not sent to stdin.

**Comment by holzschu** [comment]
So, this is like when iPython starts help: we need to get out of interactive mode, temporarily. It will be fixed in the next release.
