### ISSUE TITLE
Segmentation fault when compiling multi-file C++ program

### ISSUE THREAD

**Issue by bummoblizard** [holzschu/a-shell#225]
When compiling multi-file C++ program, clang++ produces segmentation fault.

Example repo: https://github.com/cisc220/first-module

**Comment by holzschu** [comment]
Yes, this is a well-known issue that I haven't been able to fix. It is related to the fact that clang forks, calls clang, cleans up everything, then calls clang a second time, trying to access the memory it freed on the second run.

The solution is to compile each file separately: 
```
clang++ avg.cpp -c
clang++ main.cpp -c
clang++ avg.o main.o 
```
The new `make` command (already in TestFlight) will of course make the process easier.
