### ISSUE TITLE
Vim: Filtering contents of buffer with shell command causes freeze

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#227]
## Summary
 * Filtering the contents of a buffer in Vim (or even just a range of lines) with a shell command causes Vim to freeze. `a-Shell` can still scroll when this happens.
  * E.g.`:%!grep test`, `:%!xxd`, or `:5,8!grep another test` on the contents of a buffer causes Vim to stop accepting input.

## Steps to reproduce
 * Open an empty buffer
 * Run `<Escape>:%!ls<CR>`
 * Run `<Escape>:%!xxd<CR>`
 * Try to interact with Vim.

## Expected Behavior
 * Vim should not freeze when I try to filter the contents of a buffer with a command that accepts input via stdin.

## Version Information
 * Tested in TestFlight 162, 161, AppStore version of a-Shell Mini

## Additional Information/Debugging
<details>

Using this Python script (stored in `~/Documents/bin/logit`),
```py
#!/bin/python

import tempfile, sys, os
outFile = open(os.path.join(tempfile.gettempdir(), "logit.txt"), 'w')

line = '...'
while not (line is None) and len(line) > 1:
    line = sys.stdin.readline()
    outFile.write(line + "\n")
    outFile.flush()
    print("Wrote %s" % line)

outFile.close()
```

If I open a buffer and run `:%!logit`, Vim freezes as expected; however, if I type while Vim is frozen, then close a-Shell and inspect `~/tmp/logit.txt`, I see,

![AABEDE3F-741B-4090-9BF2-3B99140F6144](https://user-images.githubusercontent.com/46334387/120050149-313bba00-bfd1-11eb-9658-1ce8cd5c3cf4.png)

</details>

**Comment by holzschu** [comment]
Thanks for the warning and the extensive tests. It seems this is not something I introduced with the latest version, but rather something that has been present for a long time.
This is one of those situations where it's difficult to decide what exactly is standard input, and possibly harder to send input to said standard input.

**Comment by personalizedrefrigerator** [comment]
This might be related to #170...

**Comment by holzschu** [comment]
In my tests: 
- `:!xxd FileName` (no percent) also freezes.
- typing `:q` while `vim` is frozen sometimes exits `vim`. No other command seems to work, except `:q`.
- redirecting the output (as `vim` usually does) avoids the freezing issue.

**Comment by personalizedrefrigerator** [comment]
* `:!ipython` and `:!jsi` both work (accept input as expected.
 * `:%!grep foo` doesn't work if I set `window.interactiveCommandRunning` to false just before pressing enter.

<details>

I'm using this script to toggle interactive mode.

```js
//Run with jsc --in-window

(function() {
if (!window.term_)
{
    print_error("Must be run in the terminal's context");
    exit(1);
}

if (!window.interactiveToggle)
{
    window.interactiveToggle = {};
    window.term_.document_.body.addEventListener("keydown",
        (evt) =>
            window.interactiveToggle.keyListener(evt),
        true);

    interactiveToggle.display = document.createElement("div");
    document.body.appendChild(interactiveToggle.display);

    setInterval(() => window.interactiveToggle.updateDisplayColor(), 250);
}

let display = interactiveToggle.display;
display.style = `
    position: fixed;
    z-index: 999;
    top: 0;
    right: 0;
    max-width: 25vw;
    max-height: 25vh;
    background-color: white;
    padding: 3px;

    border-bottom-left-radius: 5px;
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.4);

    transition: 0.1s ease all;
`;

interactiveToggle.updateDisplayColor = () =>
{
    if (window.interactiveCommandRunning)
    {
        display.style.backgroundColor = "rgba(255, 200, 200, 0.8)";
    }
    else
    {
        display.style.backgroundColor = "rgba(255, 255, 255, 0.8)";
    }
};

display.innerHTML = "...";
interactiveToggle.keyListener = (evt) =>
{
    let message = "Key: ";
    message += evt.key;

    if (evt.altKey)
    {
        message += " (ALT)";
    }

    if (evt.ctrlKey)
    {
        message += " (CTRL)";
    }

    if (evt.ctrlKey && evt.key == "i")
    {
        window.interactiveCommandRunning = !window.interactiveCommandRunning;
    }

    interactiveToggle.updateDisplayColor();
    display.innerText = message;
};
})();
```

</details>

**Comment by holzschu** [comment]
I have found an issue that was more trivial: `vim` sends commands as `(cmd) <inputFile>outputFile 2>&1`. The command line parsing in ios_system was interpreting that as `cmd < "inputFile>outputFile"`. I've added a space after the name of the input file, before the `>`. Let's see if it works.

**Comment by personalizedrefrigerator** [comment]
It works!!!
