### ISSUE TITLE
Build 162: Vim has wrong CWD on startup (`:e foo.bar` doesn't work just after launching Vim)

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#228]
## Summary
 * Running `:tabe ./some_file_in_the_current_directory` doesn't edit the file.
 * `:!pwd` always prints `/private/var/containers/Bundle/Application/CFDF1EC7-127E-40DD-BC48-FC342C50E2E3/a-Shell.app/vim/autoload/xolox/misc` after startup.
  * Opening another app (such that a-Shell is in the background), then returning to a-Shell temporarily fixes the issue, until Vim is closed and re-opened.

## Additional Information
* Issue present in TestFlight build 162
 * Not present in build 161

**Edit:** I think this is breaking `:w`, too.

Thank you for your work on this amazing app!

**Comment by holzschu** [comment]
Thanks for the warning. I'm going to have a look. I'm taking a wild guess here, but this could be related to the xolox plugin, or to the way plugins are loaded (xolox is probably the last plugin to be loaded, in alphabetical order).

**Comment by holzschu** [comment]
I've found the issue.
The recent versions of `ios_system` redefine `chdir()` to store the new working directory at the window level. 
`vim` uses `chdir()` to go down the hierarchy when loading plugins, but `fchdir()` to go up. I've fixed it by redefining `fchdir()` as well. Now I need to recompile everything that uses `fchdir` (man, perl and cpython).

**Comment by personalizedrefrigerator** [comment]
Thank you!
