### ISSUE TITLE
`jupyter-console`: Needs to be marked interactive

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#234]
> There was a very similar issue with `ptpython`, so I am thinking: should I edit `prompt-toolkit` so that whenever it is loaded, it also calls the command `jsi -w "window.interactiveCommandRunning = true;"`?
> _Originally posted by @holzschu in https://github.com/holzschu/a-shell/issues/206#issuecomment-850956408_

This is also an issue with `jupyter-console`. I agree that making the current command interactive if `prompt-toolkit` is loaded.

Note, however, some commands, like `jsi --no-color`, can still import `prompt-toolkit`, but rely on Python's `str(input())` (and so should not be marked interactive). Perhaps one (rather messy) workaround would be to switch to interactive mode _if_ the current line starts with a color-changing escape sequence (e.g.`\033[32m...`) **and** `prompt_toolkit` has been loaded...

**Comment by holzschu** [comment]
Or we could detect "cursor position requests" (CPR) handling in `hterm_all.js` and move to interactive mode if it happens.

**Comment by holzschu** [comment]
I did that in `script.js`: https://github.com/holzschu/a-shell/blob/9158a9fffa184696a5547daad2aa007d6b26a2b0/script.js#L1892 
It works with `vim` and all commands that use `prompt-toolkit` with CPR, so I simplified `isInteractive`. `less`, `more`, `ssh` and the like don't use CPR, so I kept them in `isInteractive`.

**Comment by holzschu** [comment]
You can now test this fix with build 165.

**Comment by personalizedrefrigerator** [comment]
Can confirm that this has been fixed

**Comment by kkk669** [comment]
I tried `lib.init().then(() => setupHterm())` and `await setupHterm()`, but it doesn't seem that `lib.init()` relates to at least `setupHterm()`.

On the other hand, this modification will fix the issue:

```diff
diff --git a/script.js b/script.js
index e3c3f5ac..5cd06a27 100644
--- a/script.js
+++ b/script.js
@@ -337,6 +337,7 @@ function updateAutocompleteMenu(io, cursorPosition) {
 }
 
 function setupHterm() {
+    setTimeout(() => {
 	const term = new hterm.Terminal();
 	// Default monospaced fonts installed: Menlo and Courier. 
 	term.prefs_.set('cursor-shape', 'BLOCK'); 
@@ -986,6 +987,7 @@ function setupHterm() {
 		window.commandRunning = window.commandToExecute;
 		window.commandToExecute = ""; 
 	}
+    }, 3000);
 }
 
 window.onload = function() {
```

But this one won't:

```diff
diff --git a/script.js b/script.js
index e3c3f5ac..40f8c3c4 100644
--- a/script.js
+++ b/script.js
@@ -338,6 +338,7 @@ function updateAutocompleteMenu(io, cursorPosition) {
 
 function setupHterm() {
 	const term = new hterm.Terminal();
+    setTimeout(() => {
 	// Default monospaced fonts installed: Menlo and Courier. 
 	term.prefs_.set('cursor-shape', 'BLOCK'); 
 	term.prefs_.set('font-family', window.fontFamily);
@@ -986,6 +987,7 @@ function setupHterm() {
 		window.commandRunning = window.commandToExecute;
 		window.commandToExecute = ""; 
 	}
+    }, 3000);
 }
 
 window.onload = function() {
```

Therefore, the timing at which `new hterm.Terminal()` is called seems to be important for this issue.
