### ISSUE TITLE
Build 164: Closing and re-opening a-Shell -> black screen

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#235]
## Summary
 * After closing and re-opening a-Shell, the screen is black, and commands I enter seem to do nothing.
   * When no external keyboard is connected, the touch keyboard does not appear.

## Terminal settings
 * A rather large font-size (`config -s 16`, I think)
 * Black background (`config -b black`)
 * White foreground
 
Thanks again for working on this!

**Comment by personalizedrefrigerator** [comment]
If I call `setupHterm()` myself after starting `a-Shell`, the terminal works as expected (but doesn't apply my custom font size or background).

**Comment by holzschu** [comment]
Looking at the debugging console, I see that this line: 
https://github.com/holzschu/a-shell/blob/9158a9fffa184696a5547daad2aa007d6b26a2b0/a-Shell/SceneDelegate.swift#L1941
results in an error: "JavaScript execution returned a result of an unsupported type". There is a strong probability that the two problems are connected.

**Comment by kkk669** [comment]
Same here. (a-Shell 1.7.3 (164), iPadOS 14.7 DB 2)

In my case, opening a new window in Split View fixes the issue temporarily. (iPadOS only)

**Comment by holzschu** [comment]
I've traced it to `lib.PreferenceManager.prototype.set` which now, with the new hterm version, returns a `Promise.resolve()`, which is (unsurprisingly) not handled by `webView.evaluateJavaScript()`. I've created a synchronous version, which is what we now call from the Swift side. The repository is updated now; the build will take a bit longer.

**Comment by holzschu** [comment]
Build 165 is out on TestFlight. It seems to solve the issue on my setup.

**Comment by personalizedrefrigerator** [comment]
> Build 165 is out on TestFlight. It seems to solve the issue on my setup.

I'm still experiencing the issue...

**Comment by holzschu** [comment]
It seems to works when running from Xcode but not when running from TestFlight. This might be difficult to debug.

**Comment by kkk669** [comment]
I've found that the following change would fix the problem, so I think this is something like a race-condition.

```diff
diff --git a/script.js b/script.js
index e3c3f5ac..c288568c 100644
--- a/script.js
+++ b/script.js
@@ -990,7 +990,7 @@ function setupHterm() {
 
 window.onload = function() {
        lib.init();
-       setupHterm();
+    setTimeout(() => setupHterm(), 3000);
 };
 
 // Modifications and additions to hterm_all.js:
 ```

**Comment by personalizedrefrigerator** [comment]
![3B562FB8-097B-421F-8E44-28CCADDA0F9E](https://user-images.githubusercontent.com/46334387/120919108-c5aaba00-c66c-11eb-8d64-ef54d15d3be1.jpeg)
It looks like lib.init is async...

**Comment by kkk669** [comment]
I tried `lib.init().then(() => setupHterm())` and `await lib.init()`, but it doesn't seem that `lib.init` relates to at least `setupHterm()`.

On the other hand, this modification will fix the issue:

```diff
diff --git a/script.js b/script.js
index e3c3f5ac..5cd06a27 100644
--- a/script.js
+++ b/script.js
@@ -337,6 +337,7 @@ function updateAutocompleteMenu(io, cursorPosition) {
 }
 
 function setupHterm() {
+    setTimeout(() => {
 	const term = new hterm.Terminal();
 	// Default monospaced fonts installed: Menlo and Courier. 
 	term.prefs_.set('cursor-shape', 'BLOCK'); 
@@ -986,6 +987,7 @@ function setupHterm() {
 		window.commandRunning = window.commandToExecute;
 		window.commandToExecute = ""; 
 	}
+    }, 3000);
 }
 
 window.onload = function() {
```

But this one won't:

```diff
diff --git a/script.js b/script.js
index e3c3f5ac..40f8c3c4 100644
--- a/script.js
+++ b/script.js
@@ -338,6 +338,7 @@ function updateAutocompleteMenu(io, cursorPosition) {
 
 function setupHterm() {
 	const term = new hterm.Terminal();
+    setTimeout(() => {
 	// Default monospaced fonts installed: Menlo and Courier. 
 	term.prefs_.set('cursor-shape', 'BLOCK'); 
 	term.prefs_.set('font-family', window.fontFamily);
@@ -986,6 +987,7 @@ function setupHterm() {
 		window.commandRunning = window.commandToExecute;
 		window.commandToExecute = ""; 
 	}
+    }, 3000);
 }
 
 window.onload = function() {
```

Therefore, the timing at which `new hterm.Terminal()` is called seems to be important.

**Comment by holzschu** [comment]
The hterm documentation now recommends:
```
window.onload = async function() {
  await lib.init();
  setupHterm();
};
```
I'm going to try with that.

**Comment by kkk669** [comment]
@holzschu I already tried that. This issue seems to be caused by another reason.

**Comment by holzschu** [comment]
@kkk669 thanks for the warning. I'll try with the timeout then. But I'm curious: how do you manage to reproduce the issue when you're compiling the app yourself? For me it always works when installed from Xcode.

**Comment by kkk669** [comment]
@holzschu I reproduce the issue by the following steps.

1. Modify source code
1. Run the app on the device (from Xcode)
1. Kill it
1. Reopen it from the home screen (this will reproduce the issue)

**Comment by holzschu** [comment]
Thanks. With your instructions, I am able to reproduce the issue. I'd like to avoid the timeout, as it might break later. `await` does not really wait, as you found out. But waiting for `hterm.windowType` to be defined does work:
```JavaScript
  var interval = setInterval(function() {
    if (hterm.windowType) {
      clearInterval(interval);
      setupHterm();
    }
  }, 200);
```
Now that works (as in, I get the prompt), but the session setup has not been done, so the colors and text are lost. But I feel I'm getting there.

**Comment by kkk669** [comment]
@holzschu 

> I'd like to avoid the timeout

Me too. I had used it to isolate the causes.

> But waiting for hterm.windowType to be defined does work:

`hterm.windowType` is defined in [this function](https://github.com/holzschu/a-shell/blob/0d998159e00bf72e169a4cfa5b2aa3e95fd209e7/hterm_all.js#L5205) and it is awaited [here](https://github.com/holzschu/a-shell/blob/0d998159e00bf72e169a4cfa5b2aa3e95fd209e7/hterm_all.js#L107), so I believe it will be defined until `await lib.init()` returns. Am I missing anything? 🤔

**Comment by holzschu** [comment]
I was thinking that it was possible that `await lib.init()` returns before `lib.init()` is complete (it returns really quickly).
But the fix doesn't work actually.
If `lib.init()` returns and is complete, then why is `new hterm.Terminal()` taking forever? It calls `onTerminalReady`, so it could be that.

**Comment by kkk669** [comment]
> It calls onTerminalReady, so it could be that.

Are you referring to [this](https://github.com/holzschu/a-shell/blob/0d998159e00bf72e169a4cfa5b2aa3e95fd209e7/hterm_all.js#L14175)? When I inserted a delay to there, it didn't give any effects.

**Comment by holzschu** [comment]
So the signs are pointing towards `hterm.Terminal = function({profileId} = {})`.
Using your `setTimeout(() => {` in `setupHterm` made me realise that the previous window content was copied twice, so at least I could fix that.

**Comment by holzschu** [comment]
With `setTimeOut` on the second line of `setupHterm`, as in your second example, the terminal does not start even when called from Xcode. Does that ring a bell fo you?

**Comment by kkk669** [comment]
> With setTimeOut on the second line of setupHterm, as in your second example, the terminal does not start even when called from Xcode. Does that ring a bell fo you?

Yes. `setTimeout` should be on the first line of `setupHterm` not the second line as I wrote (Sorry for the confusion caused by my poor English). This is because `new hterm.Terminal()` have to be delayed. But I don't know why it have to be delayed. If we could figure that out, I think we could find another solution.

**Comment by holzschu** [comment]
Thanks.
I placed a test on the first line of `setupHterm`:
```JavaScript
	if (!hterm.Terminal) { ... }
```
and it was triggered. It seems that sometimes, `lib.init()` is done, but `hterm.Terminal` still does not exist. I will try waiting for `hterm.Terminal`.

**Comment by personalizedrefrigerator** [comment]
I'm not sure if this is helpful at this point, but these are the errors I'm getting from `setupHterm()` when called too early:
![Error processing accessibility handler](https://user-images.githubusercontent.com/46334387/120933441-03303700-c6af-11eb-94fd-c383e9a0e4f8.png)

![Stack trace continued](https://user-images.githubusercontent.com/46334387/120933452-0deacc00-c6af-11eb-91b3-2a58874ec246.png)

(Gotten via adding 
```sh
jsi -wc 'window.addEventListener("error", (e) => { alert("Error: " + e.error.message + "\nStack:" + e.error.stack); });'
jsi -wc 'setupHterm();'
```
to the beginning of my `.profile`.)

**Comment by holzschu** [comment]
I think part of the issues may be caused by calling `setupHterm()` a second time. Still, I've modified `print` so that it buffers everything until `accessibilityReader_` is not null:
```JavaScript
hterm.Terminal.IO.prototype.print =
hterm.Terminal.IO.prototype.writeUTF16 = function(string) {
  // If another process has the foreground IO, buffer new data sent to this IO
  // (since it's in the background).  When we're made the foreground IO again,
  // we'll flush everything.
  // iOS addition: don't print until accessibilityReader_ is available. buffer strings until then.
  if ((this.terminal_.io != this) || (window.term_.accessibilityReader_ == null)) {
    this.buffered_ += string;
    return;
  }

  this.terminal_.interpret(string);
  // iOS: keep a copy of everything that has been sent to the screen, 
  // to restore terminal status later and resize.
  if (this.terminal_.isPrimaryScreen()) {
     window.printedContent += string;
  }
};
```

**Comment by holzschu** [comment]
Inspired by your idea, I've added `window.onerror` in `script.js`, which sends the error to the Swift side, which saves it to a file (alerts and console.log were not working):
```JavaScript
window.onerror = (msg, url, line, column, error) => {
  const message = {
    message: msg,
    url: url,
    line: line,
    column: column,
    error: JSON.stringify(error)
  }

  if (window.webkit) {
   window.webkit.messageHandlers.aShell.postMessage('JS Error:' + msg + ' ' + error.stack);
  } else {
    console.log("Error:", message);
  }
};
```

**Comment by holzschu** [comment]
I think it's fixed in build 166, but I'll wait for your tests.

**Comment by personalizedrefrigerator** [comment]
Yes! It's fixed!
