### ISSUE TITLE
`a-Shell` input blocked: Resizing `a-Shell` just after closing an interactive command

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#245]
## Summary
 * Running an interactive command, like `jsi`, focusing another app _then_ closing `a-Shell`, then re-opening `a-Shell` causes `a-Shell` to not act on user input.
 * Input is still blocked if `a-Shell` is then closed (again) and re-opened.
 * **Edit:** This happens more reliably if an interactive command is run, stopped, then the terminal window is resized (i.e. with `<Ctrl +>` or a screen rotation).

## Steps to reproduce
 * Run `jsi`
 * Type `3+3`<Enter>
 * Switch to another app by pressing `<Home>` twice.
 * Close `a-Shell`
 * Open `a-Shell`
 * Type `3+3`<Enter>

## Expected behavior
 * `3+3` should be displayed in all cases.

## Observed behavior
 * `% 3+3         6` is only displayed in the first case.

**Comment by holzschu** [comment]
I only have 2 iOS devices at home, an iPad (running iPadOS 15) and an iPhone (running iOS 14). I can reproduce this behaviour on the iPhone but not on the iPad. So it can be related either to the OS version or to the multi-windows system. For my information, on what device(s) did you see this behaviour?

Anyway, it's very strange: the command is not restarted because you closed a-Shell, and we should see the prompt at the screen (`printPrompt` is called when the terminal window is initialized).

**Comment by personalizedrefrigerator** [comment]
I'm testing this on an iPhone (iOS 14.6).


I'm also unable to reproduce this with a-Shell mini (app store version). Instead, rather than a prompt, I see "[3;1R":

![aShell mini shows no prompt on startup under above conditions](https://user-images.githubusercontent.com/46334387/121656684-98874e80-ca54-11eb-90ee-35c633b9e438.png)
![Pressing enter interprets characters as a command](https://user-images.githubusercontent.com/46334387/121656715-a1782000-ca54-11eb-9ca0-d84369a28f13.png)

**Comment by personalizedrefrigerator** [comment]
If I run the following on startup in `a-Shell`, I see that it thinks the current command is interactive on startup:
```sh
# .profile
jsi -wc "document.body.style.filter = 'invert(1)';"
cat ~/Documents/Web/interactiveTest.js | jsi -w
```

<details><summary>~/Documents/Web/interactiveTest.js</summary>
```js
//jsc --in-window

(function() {
if (!window.term_)
{
    print_error("Must be run in the terminal's context");
    exit(1);
}

if (!window.interactiveToggle)
{
    window.interactiveToggle = {};
    window.term_.document_.body.addEventListener("keydown",
        (evt) =>
            window.interactiveToggle.keyListener(evt),
        true);
    window.term_.document_.addEventListener("selectionchange",
        (evt) => window.interactiveToggle.selectionChangeListener(evt));
    window.term_.document_.body.addEventListener("pointerdown",
        (evt) => window.interactiveToggle.pointerDownListener(evt));
    window.term_.document_.body.addEventListener("pointermove",
        (evt) => window.interactiveToggle.pointerMoveListener(evt));
    window.term_.document_.body.addEventListener("pointerup",
        (evt) => window.interactiveToggle.pointerUpListener(evt));

    interactiveToggle.display = document.createElement("div");
    document.body.appendChild(interactiveToggle.display);

    setInterval(() => window.interactiveToggle.updateDisplayColor(), 250);
}

let display = interactiveToggle.display;
display.style = `
    position: fixed;
    z-index: 999;
    top: 0;
    right: 0;
    max-width: 25vw;
    max-height: 25vh;
    background-color: white;
    padding: 3px;

    border-bottom-left-radius: 5px;
    box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.4);

    transition: 0.1s ease all;
`;

interactiveToggle.updateDisplayColor = () =>
{
    if (window.interactiveCommandRunning)
    {
        display.style.backgroundColor = "rgba(255, 200, 200, 0.8)";
    }
    else
    {
        display.style.backgroundColor = "rgba(255, 255, 255, 0.8)";
    }
};

display.innerHTML = "...";
interactiveToggle.keyListener = (evt) =>
{
    let message = "Key: ";
    message += evt.key;

    if (evt.altKey)
    {
        message += " (ALT)";
    }

    if (evt.ctrlKey)
    {
        message += " (CTRL)";
    }

    if (evt.ctrlKey && evt.key == "i")
    {
        window.interactiveCommandRunning = !window.interactiveCommandRunning;
    }

    interactiveToggle.updateDisplayColor();
    display.innerText = message;
};

interactiveToggle.selectionChangeListener = (evt) =>
{
    let message = "Sel: " + Math.floor(evt.timeStamp);
    display.innerText = message;
    window.selEvent = evt;
};

interactiveToggle.pointerDownListener = (evt) =>
{
    display.innerText = "Pointer down.";
};

interactiveToggle.pointerMoveListener = (evt) =>
{
    display.innerText = "Pointer move.";
};

interactiveToggle.pointerUpListener = (evt) =>
{
    display.innerText = "Pointer up.";
};

})();


```
</details>

I have only tested this for the `jsi -wc 'document.body.style.filter='invert(1)';"` case, however. It could be we're experiencing two different issues...

**Comment by personalizedrefrigerator** [comment]
`a-Shell` is also put (incorrectly) into interactive mode when I do the following:
```
$ jsi
Type 'help' for help and 'quit' to exit.
% quit
$ <Ctrl+`+`>
```
...where `<Ctrl+'+'>` could also be <Ctrl Minus>, or some other resize shortcut, **including rotating the screen**.

**Comment by holzschu** [comment]
Ah yes. Resizing reprints the screen content, so it sends the cursor position request string back to the screen, so it sets `interactiveCommandRunning` to true. 
I've added: 
```JavaScript
	if (window.commandRunning !== undefined) && window.commandRunning != '') {
		window.interactiveCommandRunning = true;
	}
```
to set `interactiveCommandRunning` only if there is a command, not during resize/restart events.

**Comment by personalizedrefrigerator** [comment]
While it should partially fix the issue, running an interactive command, then a non-interactive command (e.g. `python`) and resizing the terminal should still cause `interactiveCommandRunning` to be incorrectly set...

**Comment by holzschu** [comment]
Argl, yes, you're absolutely right. And the other test I placed inside `io.onVTKeystroke` would have the same issue. 
I need to cancel the test on cursor position requests if it is happening during a resize callback.

**Comment by personalizedrefrigerator** [comment]
It looks like `document::onresize` isn't being fired. `term_.io.onTerminalResize` would have to be overridden instead.

**Comment by holzschu** [comment]
Build 168 is now out on TestFlight, with 3 different checks to avoid entering interactive mode if a command is not running. it should fix this issue.

**Comment by personalizedrefrigerator** [comment]
It's fixed!
