### ISSUE TITLE
Vim not resizing on terminal resize

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#250]
## Summary
 * Rotating the screen leaves Vim the same size it was before the rotation -- it doesn't fill the terminal.
![](https://user-images.githubusercontent.com/46334387/121793215-c8983400-cbb1-11eb-85c9-c56450aa0044.jpeg)

**Comment by holzschu** [comment]
I'm going to have a look. A screen rotation should trigger a SIGWINCH signal, which should be caught by Vim.

**Comment by holzschu** [comment]
The plot thickens: SIGWINCH *is* triggered, and Vim's `sig_winch` function *is* called... sometimes.

**Comment by personalizedrefrigerator** [comment]
It's fixed! Thank you!
