### ISSUE TITLE
`jsc` does not do `~` expansion

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#252]
## Summary
 * `jsc --in-window ~/Documents/Web/gestures.js` reports `No such file or directory` even though `gestures.js` exists
 * `jsc --in-window gestures.js` works if the current working directory is `~/Documents/Web`

**Comment by holzschu** [comment]
Interesting; that’s a bug I already fixed in `executeWebAssembly`. Well, that’s an easy fix.
(If you look at the error message, jsc appends the name of the current directory twice in front of the command).

**Comment by personalizedrefrigerator** [comment]
Thank you!
