### ISSUE TITLE
`config`:  `--default` and `--reset` long options listed in `--help`, but not accepted

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#255]
## Summary
 * `config --help` includes `--default`, `--permanent`, and `--reset` long options; however, attempting to run `config --default`, `config --permanent [...other options...]`, or `config --reset` results in a `could not understand argument` message.
 * The short options for `default`, `permanent`, and `reset` all work as expected.

**Comment by holzschu** [comment]
That was easy to fix. Thanks for spotting it.
