### ISSUE TITLE
`config -n` and `config -n picker` always set font to an empty string

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#257]
![A0CEE665-FD68-499A-A514-8806902C0903](https://user-images.githubusercontent.com/46334387/121993513-73e2ed80-cd58-11eb-8764-d8ff54646305.jpeg)

After running `config -n picker` and selecting a font, the terminal's text is shown in a variant of `Serif` (rather than the monospace font I selected).

**Comment by holzschu** [comment]
I'm having trouble reproducing this issue. Using the font picker, Courier, Courier New, Menlo, Source Code Pro all result in a monospace font.
I have some strange results on screen with Andale Mono, which look like the picture you show. From what I can see, there are no errors at any point in the system (iOS creates a UIFont with that name, with the required properties, in JavaScript `this.screen_.style.fontFamily = fontFamily` does not result in an error, etc). 

Looking at the reference (https://en.wikipedia.org/wiki/Andalé_Mono), the font displayed for "Andale Mono" is definitely not Andale Mono. How can I check that the font being used for display is not the font requested? (and also why is the font available for the system but not the HTML display?)

**Comment by holzschu** [comment]
From my rapid look at the documentation, I cannot check that the font has been loaded, but I can add a backup font in case it fails to load.
```JavaScript
hterm.ScrollPort.prototype.setFontFamily = function(
    fontFamily, smoothing = '') {
  this.screen_.style.fontFamily = fontFamily + ", Menlo, monospace";
  this.screen_.style.webkitFontSmoothing = smoothing;

  this.syncCharacterSize();
};
```
(this way, the terminal remains usable. The mystery of why Andale Mono cannot be loaded by the webView when it can be loaded by the system remains...)
