### ISSUE TITLE
`ssh`: Arrow keys not working in Vim?

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#259]
## Summary
 * `ssh`ing into a remote server, I find that while arrow keys move the cursor on the commandline, they do nothing in `vim` or `man`
 * Telling `vim` to log received keypresses,
```vim

  1 ^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[
    [D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C
    ^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[
    [C^[[C^[[C^[[C^[[C^[[B^[[B^[[B^[[C^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[C^[[A^[[A
    ^[[C^[[A^[[A^[[C^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[
    [A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[:q^M
```

**Edit:** This may just be a configuration issue (I don't experience this with `nano`)...

**Comment by holzschu** [comment]
That is a question I have to address anyway. 
At least on iOS 15, arrows on external keyboards don't work with Vim either.
At first glance at the code, arrow keys (on screen) send "escape + [A" and external keyboard sends "^[[A" (from your log), so the reason for the difference in behaviour is not clear.

**Comment by personalizedrefrigerator** [comment]
> At first glance at the code, arrow keys (on screen) send "escape + [A" and external keyboard sends "^[[A" (from your log), so the reason for the difference in behaviour is not clear.

I think `^[` is a synonym for `escape`... 

Additionally, I'm using [`vim -w logfile.txt` to log keystrokes to `logfile.txt`](https://stackoverflow.com/questions/6049184/how-to-see-the-last-few-keystrokes-in-vim).

**Comment by holzschu** [comment]
That's what I meant: they're sending exactly the same string, so why the difference in behaviour?

**Comment by personalizedrefrigerator** [comment]
> so why the difference in behaviour?

This is just a guess: `Vim` might be interpreting `^[[A` as `^[` ... pause ... `[A`, rather than `^[[A`...

**Comment by personalizedrefrigerator** [comment]
Running `export TERM=cons25` before opening `vim` fixes the issue on the remote host for `vim` and `less`.

**Comment by holzschu** [comment]
After debugging, the external keyboard sends "^[OA" rather than "^[[A". And that seems to be related to this issue: https://vi.stackexchange.com/questions/15324/up-arrow-key-code-why-a-becomes-oa 
(and so the change in behaviour for Vim would be related to the move to the alternate screen).

**Comment by holzschu** [comment]
So, the problems are connected:
- the arrow keys always send "^[[A", but they should be sending "^[OA" when we are on the alternate screen.
- the external keyboard sends "^[[A" in primary screen, but "^[OA" in alternate screen (good, but how?)
- Vim (a-Shell) should be recompiled to expect "^[OA" rather than "^[[A"

**Comment by holzschu** [comment]
Yes, translated into Swift code as:
```Swift
    @objc private func upAction(_ sender: UIBarButtonItem) {
        webView?.evaluateJavaScript("window.term_.io.onVTKeystroke((!window.term_.keyboard.applicationCursor) ? '\\x1b[A' : '\\x1bOA');") { (result, error) in
            if error != nil {
                print(error)
            }
            if (result != nil) {
                print(result)
            }
        }
    }
```

**Comment by personalizedrefrigerator** [comment]
> webView?.evaluateJavaScript("window.term_.io.onVTKeystroke((!window.term_.keyboard.applicationCursor) ? '\\x1b[A' : '\\x1bOA');") { (result, error) in

A similar change may also need to be done in gestures.js...

**Comment by holzschu** [comment]
Ah yes. That's in `moveCursor`, right?

**Comment by personalizedrefrigerator** [comment]
https://github.com/holzschu/a-shell/blob/b7012c0314c90b0f65f4c0c96a98a360c124b0f3/gestures.js#L156-L165

**Comment by personalizedrefrigerator** [comment]
In iOS 14.6, `\x1bOA`, `\x1bOB`, etc., are not interpreted by Vim as arrow keys...

**Comment by holzschu** [comment]
Yes, but they will be with build 170.
