### ISSUE TITLE
TestFlight v170 Files app does not show a-Shell, worked fine in v169

### ISSUE THREAD

**Issue by nipunbatra** [holzschu/a-shell#263]
Hi, I was previously on build 169 and could see a-shell in Files app. I had configured the storage of a-shell to be: on the iPad.

After v170, I am not longer able to see a-shell on the Files app. 

I am on iPadOS 14.6

![IMG_0070](https://user-images.githubusercontent.com/60985/122352493-cbf23d80-cf6c-11eb-8eb0-e981ed343a8d.png)

![IMG_0074](https://user-images.githubusercontent.com/60985/122352671-f3e1a100-cf6c-11eb-8ef6-46c9734cf249.png)

![IMG_0073](https://user-images.githubusercontent.com/60985/122352453-c5fc5c80-cf6c-11eb-8818-af82fd7a996a.png)

I am hoping I am not making as silly mistake!

**Comment by nipunbatra** [comment]
Update - the folder is now visible after the restart. I can close the issue.

**Comment by holzschu** [comment]
You had me scared for a while. Thanks for the update.
