### ISSUE TITLE
asdffgh

### ISSUE THREAD

**Issue by dagmob** [holzschu/a-shell#271]
Deleted

**Comment by holzschu** [comment]
I'm not sure I understand the question, but I think the short answer is: if this application was able to work around security protections, then Apple would remove it from the AppStore instantaneously.

**Comment by dagmob** [comment]
Haha fuck apple they can kiss my ass 😂😂 i should’ve worded my question a little better and not so blunt  haha but pretty much my question was instead of a dns server how can I use shell or python to Command on my mobile device to do  similar tasks as if I were re re routing my dns
