### ISSUE TITLE
What is the use of stdout_active in wasm function?

### ISSUE THREAD

**Issue by bummoblizard** [holzschu/a-shell#273]
While I was debugging an issue related to running wasm, I noticed a variable called `stdout_active` and could not find any reference to it throughout the codebase. What is the use of this variable? 

https://github.com/holzschu/a-shell/blob/1b908c5fb20f9851a5638836a0e975eb586a606b/a-Shell/SceneDelegate.swift#L534-L537

**Comment by holzschu** [comment]
`stdout_active` is a boolean that tells whether the `stdout` channel is still open. It is set to `false` when a command sends `^D` (or `endOfTransmission`)  to `stdout`: https://github.com/holzschu/a-shell/blob/181119d0791147ea6d5cbb514b3ebee6fe7f4909/a-Shell/SceneDelegate.swift#L2431

**Comment by bummoblizard** [comment]
Ah I missed it. Thanks for the explanation!
