### ISSUE TITLE
ImageMagick works only the first time from shortcut

### ISSUE THREAD

**Issue by atnbueno** [holzschu/a-shell#279]
When I run the command `convert -size 40x40 xc:red red.png` from the "Execute shell command" action in Shortcuts, it only works the first time. When I run it successive times (deleting the `red.png` file in between) the app opens, but the command hasn't run. I have to force kill a-Shell so the command works again (just once).

**Comment by atnbueno** [comment]
Agh. Of course, now that I've reported the problem, it always works.

**Comment by holzschu** [comment]
In my tests, I do have a difference between first time and subsequent times, but the opposite as what you described: it doesn't always work the first time, but it does always work afterwards. I have the same behaviour with the AppStore version and the TestFlight version. Out of curiosity, are you running from an iPhone or an iPad? They have different behaviour at startup.

**Comment by atnbueno** [comment]
I did it with an iPhone 12 mini and iOS 14.6, but now I've tested in an iPad Pro 12.9" (also with iOS 14.6) and this shortcut always work _from the extension_. I run it in the Shortcuts app, and from the widget.

https://www.icloud.com/shortcuts/699450d555e241c9ba86e54fc17f6bb3
