### ISSUE TITLE
Feature Request: mtr network utility

### ISSUE THREAD

**Issue by agibson2** [holzschu/a-shell#284]
mtr is a really good graphical traceroute utility and would be very useful for network administration.

**Comment by guilhermefigueiredo** [comment]
+1

**Comment by holzschu** [comment]
The biggest issue in porting traceroute to iOS is that it requires superuser privilege, something that is impossible on a (non-jailbroken) iPhone or iPad.

From what I can read on mtr, it also requires superuser privilege to run, so it is impossible to make it run inside an iOS app. 
See this (really nice) explanation by Roger Wolff (maintainer of mtr): https://github.com/traviscross/mtr/issues/204#issuecomment-723961118

**Comment by agibson2** [comment]
I forgot to say thank you for looking into the possibility.  I will close this.
