### ISSUE TITLE
interactive input is supported by the wasi sdk

### ISSUE THREAD

**Issue by williamstein** [holzschu/a-shell#287]
The README says:

> "... We have the limitations of WebAssembly: no sockets, no forks, no interactive user input (piping input from other commands with command | wasm program.wasm works fine)."

However, "no interactive user input" is fortunately **not** a limitation anymore.   E.g., `python` works and gets input, as does a simple C program using scanf.

(This a-shell is AMAZING by the way!  Amazing!!)

**Comment by holzschu** [comment]
`python` is compiled to native ARM64, not to WebAssembly. That's why it is interactive. C programs compiled to wasm can get input with scanf, but not interactively: you can run a program that asks questions, but not an editor like emacs.

**Comment by williamstein** [comment]
Thanks for the clarification!
