### ISSUE TITLE
[Feature suggestion] Ability to show/hide virtual keyboard

### ISSUE THREAD

**Issue by martgil** [holzschu/a-shell#298]
First of all, thank you for creating this terminal for free and open-source. This is by far one of the great terminal i've ever used. 

I have noticed that their isn't the ability available to hide the on-screen keyboard when the user is using an external keyboard. It might be really helpful for those user which have their keyboard connected and being used with the a-shell terminal. The screen size is teribly being occupied almost 50% of the screen size when the virtual keyboard are shown. If it was possible for the next update, I would suggest adding a toggle or switch in the quick access bar to show and hide the virtual keyboard if it was able to control programatically.

Thank you and Kind Regards,
Mart Gil

**Comment by ifuchs** [comment]
I am using the Apple external keyboard with an iPad Pro and the onscreen keyboard does not show.

**Comment by martgil** [comment]
Hi @ifuchs, Im using an infamous brand of wireless keyboard with my iphone. Is it just a normal behavior for small screen devices to occupy the screen without being able to hide the on-screen keyboard? Could you please check it with smaller screen device and see if the same behavior will occur? Thanks!

**Comment by ifuchs** [comment]
I just tested with an iPhone 7 and a keyboard I got from AliExpress. It worked as expected (no on-screen keyboard). Although I did find one strange thing...if I tried to use the iOS search to find ashell, the Return key did not work. Odd, but not related to ashell. If I started ashell without having to search for it, all worked correctly. (Maybe I found an Apple bug?)

**Comment by holzschu** [comment]
Hi @martgil, for every external keyboard I've tried, as soon as the external keyboard is connected, the on-screen keyboard disappears (it's actually a behaviour encoded at the OS level). I have no idea what is happening on your side, but it seems that the OS does not understand that the accessory is a keyboard.

**Comment by martgil** [comment]
Thanks @holzschu @ifuchs for checking this. Ill will check it again later. Btw, is 'git' command working as this date or will there be any alternative (working copy, though im unsure if its like git)

Thanks a lot! 🙏🏻

**Comment by holzschu** [comment]
`git` is covered by the GPL, and the FSF has decided the GPL is incompatible with AppStore distribution. `lg2` is a git clone, based on libgit2 (like WorkingCopy). Most commands are present, but not all. This being said, WorkingCopy is much more advanced and has a better user interface for everything.

**Comment by martgil** [comment]
Got it @holzschu! It could be cover up by setting an alias to 'lg2' to 'git' instead. Thank you @holzschu and have a wonderful day!
