### ISSUE TITLE
Unable to use variables in "Execute shell command" within iOS Shortcuts

### ISSUE THREAD

**Issue by mcgaritydotme** [holzschu/a-shell#335]
In my shortcut, I have a variable which contains the value of an Expanded URL.  Neither the variable or Expanded URL are available to be inserted into my individual command (red circles).  My workaround is to combine my commands in a "Text" 
action as input into the "Execute shell command" action.

![IMG_0040](https://user-images.githubusercontent.com/450236/139147951-a1944d94-32bf-4ee3-b4a5-27aac4735866.jpg)

**Comment by stunpix** [comment]
Is this bug still actual? In my Shortcuts, I can put a variable in the command. I'm using the most recent iOS version.

![623FE633-8FCB-4A34-9615-0D50EED6E927](https://user-images.githubusercontent.com/129271/152049165-13e81804-72be-4478-8efd-aa5740e6fa5b.jpeg)

**Comment by mcgaritydotme** [comment]
@stunpix Thanks for the follow-up.  And yes, it's working now for me (on iPadOS 15.2.1)
