### ISSUE TITLE
A-Shell: Permission denied

### ISSUE THREAD

**Issue by cameololm** [holzschu/a-shell#340]
Hi A-Shell team

I just installed a-shell app and can't use 2 commands like below picture

> mkdir bin
> cd bin

![95C2F02C-0B84-4C5E-9D14-992FD0238C94](https://user-images.githubusercontent.com/73436776/141746931-b12aa72b-233a-4d83-9e47-a9e270067d75.png)

I am trying to install youtube-dl on my phone to use with below command lines

> pip install  #youtube-dl
> pip install gallery-dl
> mkdir bin
> cd bin
> curl -L https://github.com/holzschu/a-Shell-commands/releases/download/0.1/ffmpeg.wasm -o ffmpeg.wasm

**Comment by holzschu** [comment]
Hi, 
from the look of the error messages, the current directory is "/". Type `cd` to go back to the home directory. 

Also, you do not need to download `ffmpeg.wasm` anymore: we now ship with a native `ffmpeg`, much faster than the webAssembly version. Actually, you will need to remove `ffmpeg.wasm` if you already downloaded it.

**Comment by cameololm** [comment]
> Hi, from the look of the error messages, the current directory is "/". Type `cd` to go back to the home directory.
> 
> Also, you do not need to download `ffmpeg.wasm` anymore: we now ship with a native `ffmpeg`, much faster than the webAssembly version. Actually, you will need to remove `ffmpeg.wasm` if you already downloaded it.

I removed it, is ffmpeg available in a-shell or what command do I have to use to download it

**Comment by holzschu** [comment]
It is available in a-Shell by default (now, it was not available by default before). Type `ffmpeg --version` to check.

**Comment by cameololm** [comment]
> It is available in a-Shell by default (now, it was not available by default before). Type `ffmpeg --version` to check.

it is available
thanks
