### ISSUE TITLE
How can I use the syntax checkers?

### ISSUE THREAD

**Issue by tabris-trees** [holzschu/a-shell#342]
![image](https://user-images.githubusercontent.com/39879580/142219099-c4781562-eea8-44ac-8cb0-c5fef77e50f9.png)

**As this picture show that it can run syntax checker, But I don't how to do.
When I install the ALE to my ipad, it report a error that no permission to make dir:**

![IMG_0562(20211117-223420)](https://user-images.githubusercontent.com/39879580/142220411-ab3e6b94-fbef-47e1-86cc-6569ee37bc61.PNG)

what should I do to realize that?

**Comment by kkk669** [comment]
I don't know this is helpful for you, but I manage my Vim plugins including vim-lsp on my git repo.

And here is how I setup them on a-Shell.

https://github.com/kkk669/dotfiles#installation-a-shell-on-ipados

**Comment by tabris-trees** [comment]
> Yes, on iOS, the user can not write in `~`, but only in `~/Documents` (and also in `~/tmp` and `~/Library`, but these are less useful). So all the configuration directories are in `~/Documents`, which is also the directory where you end up if you type `cd`. So you will have to type `mkdir -p ~/Documents/.vim/pack/...`, or:
> 
> ```
> cd
> mkdir -p .vim/pack/...
> ```
> 
> The `git` command does not exist, but `lg2` is a replacement, with a very similar syntax and capabilities.

Thank you!!! It's really helpful!
