### ISSUE TITLE
Shortcuts/In-App: Does nothing if a-Shell already running

### ISSUE THREAD

**Issue by personalizedrefrigerator** [holzschu/a-shell#346]
## Summary

Running a shortcut (in app) if a-Shell is already running produces no output.

## Steps to reproduce

Create the following shortcut:

![shortcut that runs jsc in app, then echos testing...](https://user-images.githubusercontent.com/46334387/143383848-a7999c80-8209-4da5-9b3e-e4d962001bd8.jpeg)

I can reproduce the issue described above if I
 1. Open a-Shell
 2. Open Shortcuts
 3. Run the minimalistic shortcut

...but not if I
 1. Make sure a-Shell is not open
 2. Open Shortcuts
 3. Run the minimalistic shortcut.

_Originally posted by @personalizedrefrigerator in https://github.com/holzschu/a-shell/issues/345#issuecomment-978842560_

**Comment by personalizedrefrigerator** [comment]
Interestingly,
![just echoing testing](https://user-images.githubusercontent.com/46334387/143383994-0916fa73-6296-4d4d-b4d2-4ee628879375.jpeg)

has the opposite issue. It only produces output if a-Shell is already running.

**Comment by NightMarekApps** [comment]
when a-shell is already open my shortcut with jump, yt-dlp, echo, exit actions works

when i added a jsi command at the top, a-shell opens but does not trigger at all. unless i force close the app

seems some commands are affected and some are not

**Comment by holzschu** [comment]
Hi,
Thanks for the report. 
I've been running tests on the latest TestFlight version. Commands like `ls` or `jsi -h` produce output in a-Shell whether or not the app is already running. 

However, running `jsi -wc 'if (!window.b) { window.b = document.createElement("button"); document.body.appendChild(b); } b.focus()'` only acts if the app is not already running. I'll have a look into the code.

**Comment by holzschu** [comment]
It was something related to the single quotes, and the fact that shortcuts sent after the app has started are printed on screen. The Javascript command was wrong. It will be fixed in build 209.

**Comment by holzschu** [comment]
The TestFlight version with a fix for commands with single and double quotes is now available: https://testflight.apple.com/join/WUdKe3f4
