### ISSUE TITLE
Native FFmpeg broken

### ISSUE THREAD

**Issue by contactalexliu** [holzschu/a-shell#352]
When I execute `ffmpeg` and `ffprobe`, I get the following errors:
```
Failed loading ffmpeg from ffmpeg.framework/ffmpeg, cause = (null)
Failed loading ffprobe from ffprobe.framework/ffprobe, cause = (null)
```

I would love to be able to use the native version of FFmpeg instead of the webAssembly one, but it doesn’t seem to work on a-shell 1.8.1.

**Comment by holzschu** [comment]
Hi, 
this has happened in the past with other users and other commands. It seems to be an issue with iOS security. Rebooting the device and / or re-installing a-Shell could fix it.

**Comment by contactalexliu** [comment]
Reinstalling did the trick for now. Thanks for the help!
