### ISSUE TITLE
is google drive supported for pickFolder?

### ISSUE THREAD

**Issue by arpitgupta** [holzschu/a-shell#355]
Currently for it me its greyed out when i use pickFolder.

**Comment by holzschu** [comment]
pickFolder only works with file providers that implement Apple FileProvider API, with access to directories. Google Drive is not among them, so pickFolder won’t work.

I have tried to make it work, but documentation is scarce about folder access.

**Comment by arpitgupta** [comment]
I see. Thanks for the info.
