### ISSUE TITLE
user "bin" folder doesn't work in shortcuts/cloud

### ISSUE THREAD

**Issue by normen** [holzschu/a-shell#361]
Hey,

I don't know if its intended but when I put executables in `~/Documents/bin` I can use them as if they were in PATH - handy! However when i switch to the cloud or shortcuts folders using e.g. `jump ~shortcuts` these don't seem to work anymore, I have to be in the local folder for them to be picked up.

As said, I don't even know if `Documents/bin` is supposed to work, just thought I'd mention this.

Cheers!
Normen

**Comment by holzschu** [comment]
Hi,
`$PATH` does indeed contain `~/Documents/bin`, so the first behaviour you describe is what is expected. But `$PATH` is still being used when you change a directory, so the second behaviour you describe is not normal. I checked on my iPad, and an executable in `~/Documents/bin` is still being executed after a change of directory to `cd ~shortcuts` (so we have a different behaviour on your machine and on mine, which is worrying). All of this only applies inside the App, however. A shortcut running in extension does not have access to the home directory of the app, so it cannot run binaries inside the directory `~/Documents/bin` of the App. 

`$PATH` is defined inside the app as `~/Documents/perl5/bin:$APPDIR/bin:$APPDIR/Library/bin:$APPDIR/Library/bin3/:~/Library/bin:~/Documents/bin:/usr/bin:/bin:/usr/sbin:/sbin`.

For a shortcut running in the extension, `$PATH` is defined as `$APPDIR/bin:$APPDIR/Library/bin:$SHORTCUTS/Library/bin:$SHORTCUTS/bin:/usr/bin:/bin:/usr/sbin:/sbin`.

The last 4 directories (`/usr/bin:/bin:/usr/sbin:/sbin`) is the default value of `$PATH` in iOS. I kept it, even though it is useless.

**Comment by normen** [comment]
Hm.. I did use a shortcut with "Open App" and "put file" - so it should have been working, right?

Concerning the differences.. Forgot to mention that I am using the latest TestFlight version (205). I have a custom `.profile` to get my VIM to play nice but I don't modify `PATH`.

I also had issues with links I manually created using `ln`, they didn't work after I switched from the AppStore version to the TestFlight one.. Maybe that has something to do with it..? I didn't see any issues in other stuff though (e.g. `pip`-installed apps).

Edit:
Scratch all that, now it seems to work no matter how I start a-Shell o_O No idea what that was, I'll keep an eye on it..

**Comment by holzschu** [comment]
There is a small part that I think I understand: when you switch from the AppStore version to the TestFlight version (and even if you upgrade the app version), you are creating a new app, with a different location. So symbolic links created with `ln` might not work anymore, because they are pointing to the old position. Also, the permissions to access the directories that were given to the old app might not transfer to the new app.
