### ISSUE TITLE
_lzma module not included by default

### ISSUE THREAD

**Issue by jtledon** [holzschu/a-shell#364]
I'm trying to use a Python module that relies on the the _lzma module but it isn't available. I tried to sudo "sudo apt-get install liblzma-dev" but the audio command is not found. I am very new to a-shell so I'm not sure where I went wrong and would love some help.

**Comment by holzschu** [comment]
Hi,
Apple rejects the builds if they use the LZMA dynamic library (it's considered private frameworks, even if I recompile them myself). So for now, LZMA is deactivated in a-Shell. 

I've heard recently that I can workaround this restriction by using a static version of the LZMA library. I am going to try this, soon.

**Comment by holzschu** [comment]
**Update:** the `_lzma` module is now included with a-Shell, since version 1.9.4
