### ISSUE TITLE
`config -n` gives a menu with no confirmation button

### ISSUE THREAD

**Issue by TheGamer1002** [holzschu/a-shell#367]
I'm trying to change my font to a powerline-enabled font to use in Vim, however, I can't confirm the font. This seems to be quite a big issue.

Also, if I manually set the font, nothing appears to change. I am using the JetBrains Mono font patched by Nerd Fonts.
![F2692CEB-0EBD-4E03-8C16-9D9F469FEBD9](https://user-images.githubusercontent.com/48131223/151239537-48479c25-35d2-4dea-86b3-70d74022725e.png)
iPad 6, iOS 15.2.1, latest TestFlight build

**Comment by TheGamer1002** [comment]
The Cancel button also does not work.

**Comment by holzschu** [comment]
Thanks for raising that one. I'm confident that it used to work. I can reproduce the issue, so it should be fixable. I'm going to have a look.

**Comment by TheGamer1002** [comment]
Awesome! Thank you. Side note: I made a program that is called by `git` which redirects everything to lg2, do you think that would be useful to include in the app? It’s a C++ program that’s only around 20 lines.

**Comment by holzschu** [comment]
If the program is just redirecting everything to lg2, then something like `alias git lg2` would have the same effect, right?

**Comment by holzschu** [comment]
Build 214, on TestFlight (https://testflight.apple.com/join/WUdKe3f4) fixes the "config -n" issue. 

It uses Apple's settings: clicking on a font picks up the font, clicking on "Cancel" cancels, making the picker disappear is equivalent to cancelling.

**Comment by TheGamer1002** [comment]
So it does actually close the font picker, but there doesn’t appear to be any font change. I switched between the default font and Google’s VT323 with no difference.

**Comment by TheGamer1002** [comment]
Interestingly, the Powerline patched font works for the special characters, but I see no difference between the fonts VT323 & JetBrainsMono (nerd font patched) normally.

**Comment by holzschu** [comment]
I cannot reproduce this issue, but it may be related to how the fonts are installed on the device. I switched between VT323, Menlo and Courier, and I definitely see differences. I have installed the fonts using iFont, which makes me approve of a font certificate. You can also check that the font is installed with `config -n VT323` or `config -n Menlo`.

**Comment by normen** [comment]
> Awesome! Thank you. Side note: I made a program that is invoked by `git` which redirects all arguments to to lg2, do you think that would be useful to include in the app? It’s a C++ program that’s only around 10 lines. (You can see it being run in the background of the screenshot!)

I did something similar in perl, its also grabbing git credentials from a `~/Documents/.git-credentials` file if it exists, so you don't have to enter your password all the time on private repos: https://github.com/normen/.normen/blob/master/bin/a-shell/git.pl

**Comment by TheGamer1002** [comment]
I’m going to close this issue since it seems to work okay now and it’s also been 8 days since the last comment.
