### ISSUE TITLE
streamlink module

### ISSUE THREAD

**Issue by mamanngaga01** [holzschu/a-shell#370]
$ pip install 
〇 PySocks
〇 requests
〇 websocket_client
〇 pycountry
〇 isodate
$ python -m pip install --upgrade pip
〇 setuptools

× pycryptodome
× pycryptodomex

old not use
× Crypto

How can I install it?

**Comment by holzschu** [comment]
That's a good question. streamlink has a dependency on `pycryptodome`, and `pycryptodome` has lots of modules written in C, so it cannot be installed by the user. It might be a good idea for me to add it to the list of modules installed by default.

In the meantime, you could try `pip install --no-deps streamlink`. It could work, except for the parts that need `pycryptodome`.

**Comment by mamanngaga01** [comment]
Thanks.

**Comment by holzschu** [comment]
Version 1.9.4 (now out on the AppStore) has pycryptodome included. You could try reinstalling streamlinks.
