### ISSUE TITLE
Cursor off in VIM with Ctrl-D

### ISSUE THREAD

**Issue by normen** [holzschu/a-shell#375]
Theres some strangeness when scrolling down using `Ctrl-D` in VIM. I can reproduce this with vanilla VIM, no plugins loaded, relevant vimrc lines below.
```
let g:netrw_browse_split = 4
let g:netrw_altv = 1
```

To reproduce:
- run `vim`
- `:Lexplore`
- Select a long file to be able to scroll down
- Keep netrw open
- Scroll down in the file by holding / repeatedly pressing `Ctrl-D`

Result: The cursor is off, or rather the display is shifted up.

Still, if it wasn't for these occasional hiccups I wouldn't even notice my VIM is running in a browser 🙂

**Comment by holzschu** [comment]
Hi, 
I just tried this one, and I think the issue only applies when using an external keyboard. With the onscreen keyboard, I see the cursors keeping in touch. I'll test again in a few hours when I have an external keyboard.

**Comment by kkk669** [comment]
Maybe related to https://github.com/holzschu/a-shell/issues/179#issuecomment-1075548041?

**Comment by holzschu** [comment]
Version 1.8.6 fixes this issue with control-D.

**Comment by normen** [comment]
Can confirm, thanks!
