### ISSUE TITLE
Open Files App command

### ISSUE THREAD

**Issue by D3M1Y0** [holzschu/a-shell#383]
For my scripts, it would be nice, to open the Files App with a path by command.

**Comment by holzschu** [comment]
`open shareddocuments://` will open the Files app. 

It's unclear to me if there is a way to specify a directory with the second part of the URL, but the question has been discussed here: https://stackoverflow.com/questions/46499842/open-ios-11-files-app-via-url-scheme-or-some-other-way#55023876

**Comment by holzschu** [comment]
Update: https://www.macstories.net/ios/fs-bookmarks-a-shortcut-to-reopen-files-and-folders-directly-in-the-files-app/ says there is a way to specify the position of the file or folder to the Files app: https://www.macstories.net/ios/fs-bookmarks-a-shortcut-to-reopen-files-and-folders-directly-in-the-files-app/

**Comment by holzschu** [comment]
So, did it work for you? What's the way to specify the location of the file?

**Comment by D3M1Y0** [comment]
Yes, it works perfekt.

I use a-Shell to download YouTube videos. For this, i install yt-dlp. 

Then, with a Shortcut start the download:

`yt-dlp --ignore-errors --mark-watched --format mp4 --output "%(title)s.%(ext)s" --paths "~/Documents" URL`

When its done, i call the action to open the e-Shell folder in my iPad :

`open shareddocuments:///private/var/mobile/Containers/Data/Application/AB32D3E1-CF0C-459C-8FBD-10E5BB1F4A8A/Documents `

I think, the e-Shell application folder name is the app id ?

For me, its working perfekt.

To get the folder path, i use the FS Bookmark Shortcut, its easy to setup and show you the real path to folder or files.

**Comment by ifuchs** [comment]
I tried installing yt-dlp (pip install yt-dlp) and got:


Preparing metadata (setup.py) ... error ERROR: Command errored out with
exit status 1: command:
/private/var/containers/Bundle/Application/47CD285B-65B7-4E87-8E5D-98D7B8B883F9/a-Shell.app/Library/bin/python3
-c 'import io, os, sys, setuptools, tokenize; sys.argv[0] =
'"'"'/private/var/mobile/Containers/Data/Application/16D012EB-A8A6-48B2-93BF-2F8BFF63389B/tmp/pip-install-gn7ajez5/pycryptodomex_68721976efe5416b9d130739ef1a40ab/setup.py'"'"';
__file__='"'"'/private/
var/mobile/Containers/Data/Application/16D012EB-A8A6-48B2-93BF-2F8BFF63389B/tmp/pip-install-gn7ajez5/pycryptodomex_68721976efe5416b9d130739ef1a40ab/setup.py'"'"';f
= getattr(tokenize, '"'"'open'"'"', open)(__file__) if
os.path.exists(__file__) else io.StringIO('"'"'from setuptools import
setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base
/private/var/mobile/Containers/Data/Application/16D012EB-A8A6-48B2-93BF
-2F8BFF63389B/tmp/pip-pip-egg-info-t_sz7wm6 cwd:
/private/var/mobile/Containers/Data/Application/16D012EB-A8A6-48B2-93BF-2F8BFF63389B/tmp/pip-install-gn7ajez5/pycryp
todomex_68721976efe5416b9d130739ef1a40ab/ Complete output (1 lines):
segmentation fault ---------------------------------------- WARNING:
Discarding
https://files.pythonhosted.org/packages/24/40/e249ac3845a2333ce50f1bb02299ffb766babdfe80ca9d31e0158ad06afd/pycryptodomex-3.14.1.tar.gz#sha256=2ce76ed0081fd6ac8c74edc75b9d14eca2064173af79843c24fa62573263c1f2
(from https://pypi.org/simple/pycryptodomex/) (requires-python:>=2.7,
!=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*). Command errored out with exit
status 1: python setup.py egg_info Check the logs for full command output.
Downloading pycryptodomex-3.14.0.tar.gz (3.4 MB)
|████████████████████████████████| 3.4 MB 5.4 MB/s Preparing metadata
(setup.py) ... -

**Comment by holzschu** [comment]
Hi @D3M1Y0, you shouldn't need to download `ffmpeg.wasm`: recent versions of a-Shell ship with a native build of ffmpeg that is substantially faster than the WebAssembly version (unless you need GPL features, in which case `ffmpeg.wasm` is the only one that has them).

**Comment by D3M1Y0** [comment]
@ifuchs use the `—format mp4` commad to download the videos as mp4 file.
