### ISSUE TITLE
Folder browsing in python

### ISSUE THREAD

**Issue by Mara-Li** [holzschu/a-shell#385]
Hello!

I know I can run bash in python and it works perfect. The problem is : I want to get the value for the folder choose in pickFolder.

My goal is to create a python script that : 
- Ask to choose a folder in IOS explorer (pickFolder way?)
- Return the path of this folder.

It is possible to do that?
Thanks

**Comment by holzschu** [comment]
That's a good question. First thing first: once you select a folder in pickFolder, you also change directory to that folder. So `pwd` will give you the information you seek (or `os.getcwd()` from inside Python). And of course you can change the directory back to the original position if you want, the access permission remains valid.

Now, the hard part: I don't think it's possible to call pickFolder any other way than as a shell command (unless someone creates a specific Python extension): it needs access to several iOS system libraries.

**Comment by Mara-Li** [comment]
As pickFolder automatically change the directory folder, I can easily get the path with os.getcwd(), so everything is okay! 

So you know what error is raised in case of "pickFolder" doesn't exists? Or maybe a way to check if the user use a-shell to run the script.

**Comment by holzschu** [comment]
There are at least two methods to check if you're inside a-Shell: 
- the value of the environment variable `TERM_PROGRAM` is set to a-Shell (and to `Apple_Terminal` on a Mac, to `xterm` on xterm, etc)
- inside Python, you can also check the combination `sys.platform == "darwin"` and `os.uname().machine.startsWith("iP")`(to cover both iPhone and iPad):
```
if (sys.platform == "darwin" and os.uname().machine.startswith("iP")):
```
(the second one could, in theory, give you true in another system that uses the same library for Python)

**Comment by Mara-Li** [comment]
That's works like a charm! Thank you
