### ISSUE TITLE
iCloud folder contents deleted when switching storage?

### ISSUE THREAD

**Issue by normen** [holzschu/a-shell#39]
Hi,

it seems a-Shell (or iVim) deleted all the contents of my iCloud "TextEdit" folder (the folder that the MacOS TextEdit app creates in iCloud). I use that folder to keep my code snippets etc. and opened it in both a-Shell and iVim. At some point the folder was suddenly empty except for the two files I had opened in iVim before. This points to iVim being the culprit and I posted an issue over there (see below) however just before that happened I played with the settings of a-Shell and changed the "Document Storage" from iCloud to NextCloud.

Heres what I *suspect* was the sequence that triggered this:
- In the a-Shell settings I had "iCloud" selected as storage
- I then opened the TextEdit iCloud folder in a-Shell
- Then in the settings I switched the "iCloud" storage to my "NextCloud"
- I tried to open a folder from my NextCloud in a-Shell (which didn't work, it was still greyed out)
- Then I switched the settings back to iCloud storage

At some point after that I noticed all my files were gone.

For reference, heres the issue I raised in iVims tracker:
https://github.com/terrychou/iVim/issues/111

Cheers,
Normen

**Comment by holzschu** [comment]
I've had issues with files disappearing in iCloud recently (but not in folders accessed by my apps); The files were still present on iCloud.com, but not visible on my iPad or my Mac. After a while, they came back.

**Comment by normen** [comment]
That doesn't seem to be the case here, I restored most of the files but two I didn't have in my backup, they're not visible in iCloud.com either. I know iCloud can be wonky but I use my TextEdit folder for a long time already, accessing it from mjltiple devices and only in the last days played with iVim and just that day installed a-Shell. Might be the bug is in iCloud but the data is gone either way. 

Anyway, if I get brave I'll try and reconstruct the issue. Problem is I only have one iCloud to test on ;)

**Comment by normen** [comment]
The iVim developer seems to have found an issue in iVim, he's currently testing a fix, I'll install a-shell again as well and report back.

**Comment by normen** [comment]
I think this can be closed, the issue was most probably down to iVim.
