### ISSUE TITLE
Submodule for cpython in commit is missing

### ISSUE THREAD

**Issue by don17sch** [holzschu/a-shell#396]
The Fiona submodule for cpython is missing in commit eaf6c4a26d9ebb81df50b35a7e82f35310e0eb9f.

without this I cannot compile a-shell

**Comment by holzschu** [comment]
Is that something that "git submodule update --init --recursive" solves?

**Comment by don17sch** [comment]
No it is not. when you go to cpython in github, if you click on Fiona you get an error that the commit for Fiona does not exist. So there is nothing for git submodule update --init --recursive to find.

**Comment by holzschu** [comment]
I thought I added Fiona again 9 hours ago. Are you still having the issue?

**Comment by don17sch** [comment]
ok with the latest commit Fiona is working but now rasterio is missing

**Comment by holzschu** [comment]
I've added rasterio and committed. I've run a check on the modules in github, but let me know if another one is missing.

**Comment by don17sch** [comment]
I will check after work

**Comment by don17sch** [comment]
`fatal: No url found for submodule path 'cpython/packages/scipy/scipy/_lib/unuran' in .gitmodules`

this is the error I am getting now

**Comment by don17sch** [comment]
by the looks of it in https://github.com/holzschu/scipy/tree/42d6d7aee867e28f9ba4ba6adba72fe0cac5cf62/scipy/_lib

the unuran link is no longer working. github no longer treats that as a web link. Never seen that one before

**Comment by holzschu** [comment]
I have created the submodule scipy in Carnets, committed it and pushed it, but I cannot pull it to a-Shell. I'll have to look in the doc of git.

**Comment by holzschu** [comment]
I think it's done for unuran.
Now the next problem is that Xcode 13.3 broke the settings used in `buildAllArchitecture.sh`. I'm still trying to make it work. Changes are big enough that maintaining a version that works for both versions of Xcode will be difficult. If you're using Xcode 13.2, keep the old version of `buildAllArchitecture.sh`. If you're using Xcode 13.3... I'm still debugging. I think it works as long as you don't use Fortran.

**Comment by don17sch** [comment]
`https://github.com/holzschu/scipy/tree/2ed1fba33ae2e6c40524a1e0989540b7654ebc52/scipy/sparse/linalg/_propack`

this link for PROPACK is having the same problem as unuran

**Comment by holzschu** [comment]
I've removed the module, committed and pushed.Thanks for your help on this one.

**Comment by don17sch** [comment]
there are no errors this time when using `git clone --recursive` So it can download all the current modules. 

and what do I have to remove in order to compile on Xcode 13.3?

**Comment by holzschu** [comment]
I've just finished the new version of `cpython/buildAllArchitecture.sh`, it seems to work on my machine. 
If this is your first time compiling cpython, you need to download the frameworks with `downloadFrameworks.sh`. It provides the frameworks and libraries for iOS and simulator, but not all of them for OSX.

**Comment by don17sch** [comment]
I am getting a ton of these errors
`Showing Recent Messages
There is no XCFramework found at '/Volumes/MSSD/a-shell/cpython/XcFrameworks/pythonA-pyfftw.pyfftw.xcframework'.`


I installed openssl zmq and freetype2 and ran those 2 scripts. this is the result when I go to build the app

**Comment by holzschu** [comment]
If you ran the two scripts without errors, you're getting close. You just have to create the Python frameworks with `createFrameworks.sh` and `createModuleFrameworks.sh`, then you can compile. 

I wish there was an easier way to distribute the Python frameworks (like all the other frameworks), but there are just too many of them.

**Comment by don17sch** [comment]
I am closing this ticket as the problem that the ticket was originally for has been resolved

I will work on compiling at a later date.
