### ISSUE TITLE
Source code for the play command.

### ISSUE THREAD

**Issue by thatsitipl** [holzschu/a-shell#397]
I wanted to modify the play command so that it is able to play streams, but i wasn't able to find the source code.

**Comment by holzschu** [comment]
See “play_main” in ExtraCommand,swift: https://github.com/holzschu/a-shell/blob/eaf6c4a26d9ebb81df50b35a7e82f35310e0eb9f/a-Shell/ExtraCommands.swift#L1263

**Comment by holzschu** [comment]
…which itself calls `play_media` in SceneDelegate.swift: https://github.com/holzschu/a-shell/blob/eaf6c4a26d9ebb81df50b35a7e82f35310e0eb9f/a-Shell/SceneDelegate.swift#L899

**Comment by thatsitipl** [comment]
Thank you very much
