### ISSUE TITLE
Symlinked folders become invalid after update

### ISSUE THREAD

**Issue by normen** [holzschu/a-shell#413]
To use my default vim setup from a git checkout of my dotfiles I symlink the `.vim` folder to its place in the `Documents` folder which works well. However when a-Shell is updated or I switch to the dev version that link seems to become invalid for some reason, I have to delete the link and re-create it.

The fix is easy enough but I thought I'd mention this, thanks for a-shell, it's awesome!

**Comment by holzschu** [comment]
At every re-install, iOS changes the name of the `$HOME` directory, and thus invalidates all links that used an absolute path (and it also invalidates bookmarks, I think). The best workaround is to use relative paths in the link: `../../folder/file` will remain valid.

**Comment by normen** [comment]
Right, okay. I seem to remember that you already told me that, sorry. The link is created by a script so I don't even know if it was relative or absolute. Thanks again!
