### ISSUE TITLE
Vim not opening.

### ISSUE THREAD

**Issue by nonphiksion** [holzschu/a-shell#424]
Hi!
I’ve been trying to run Python scripts within Vim and it works excepts for scripts with the input() method. When I try to run the code with: !python % it pops up the prompt but I can’t input anything because it just freezes and then I’d exit the app and launch again. 

Somehow after repeated crashes and relaunches the Vim command stopped responding.

I’ve tried entering with: vim -u NONE but I can’t see my .vimrc or any of my directories. 

Please how can I resolve this issue other than re-installing the app?

I anticipate your kind response.

Thank you.

**Comment by holzschu** [comment]
I'm going to have a look and try `!python %` but the short answer might be that it's difficult to find out who should be in charge of the input stream in that case.

To answer the other question: all scripts and config files are in `~/Documents` (because it is not possible to write in `~`). So `~/Documents/.vim/`, `~/Documents/.vimrc` and `~/Documents/.viminfo`. Vim is trying to save the content of the current session in `~/Documents/.vim/sessions`

**Comment by nonphiksion** [comment]
Okay. So can I make vim work again?

Because each time I type in vim from the terminal it doesn’t open.

**Comment by holzschu** [comment]
I don't exactly know what's happening. Normally, if you force quit a-Shell (double press on home button, then slide a-Shell window upwards) it should reset everything and allow you to start Vim.

If you have an iPad, typing "exit" will have the same effect.

**Comment by nonphiksion** [comment]
I have typed exit many times and still it won’t work. This is the second time it has happened to me and I had to re-install the app. Sadly this is the only thing that doesn’t work as the other packages still work fine. I can type python or python3 in the terminal and it will load fine but vim won’t work at all.

**Comment by nonphiksion** [comment]
I am also using a-Shell on my iPhone XR and it happened with it as well. Here is a screenshot:
![65DD6BDE-0812-4EF0-B6A7-D6E09B683AAD](https://user-images.githubusercontent.com/108638063/177095622-8f22e781-b391-45bd-b620-faedddda81fa.jpeg)

**Comment by holzschu** [comment]
Thanks for the clarification. I still have no idea what is happening.
I see two possible hypotheses: 
a) there is another a-Shell window running with Vim inside, and that blocks the launch of the new Vim.
b) Vim is trying to restore a previous window or read a `.swp` file and that causes the issue.

If it's the former, a reboot of the iPad should solve it. If it's the latter, you can temporarily move all config files to another directory (`mkdir debug`, followed by `mv ~/Documents/.??* debug`), then restart Vim.

**Comment by nonphiksion** [comment]
Okay. Let me try it.

Thank you.

**Comment by nonphiksion** [comment]
It worked!! I used the second solution and moved the files as instructed. Thank you!

So running of python codes (with input()) remains. Am very concerned about trying it again.

**Comment by nonphiksion** [comment]
That's a relief!!

I'll be waiting for the new update.

Thank you so much!!

**Comment by nonphiksion** [comment]
Just updated and the input() is working now.

Thank you for the update!
