### ISSUE TITLE
Is there anything in a-shell equivalent to /etc/hosts ?

### ISSUE THREAD

**Issue by mtcabeza** [holzschu/a-shell#428]
/etc/hosts in linux and unix allowed for recording the ip addresses of hosts by editting the file.

For example, It would allow one to say:
     ssh someuser@somehost

rather than:
     ssh someuser@192.168.1.10

**Comment by holzschu** [comment]
The short answer is no (there is no way to set individual names for IP addresses using `/etc/hosts`).

The long answer is that both ssh on Unix and ssh on a-Shell use the DNS to map hostnames to IP addresses, and DNS use `/etc/hosts`, if it exists. On iOS, `/etc/hosts` is not accessible by the user.

However, you can set up a mapping between hostnames and IP addresses using ssh config files (in `~/Documents/.ssh/config`). For example:
```
Host website
        Hostname 275.128.172.46
        User alice
        Port 1500
```
With this config file, `ssh website` will be translated as `ssh alice@ 275.128.172.46 -p 1500`.

**Comment by mtcabeza** [comment]
yeah, i don't run a DNS for my LAN but, for ssh this is a very handy feature.
Thanks for the quick response and all the great work on a-shell!

------- Original Message -------
