### ISSUE TITLE
Can't find .vimrc file

### ISSUE THREAD

**Issue by domi04** [holzschu/a-shell#431]
Hi, I wanted to configure vim a little bit and couldn't find the .vimrc file. I know that it should be in the Documents folder but I couldn't find it there so I searched trough every directory with ls -a but I had no luck. When I created a new file all of the previous configuration of vim was lost.

**Comment by domi04** [comment]
Do I have to create the file or should it be there from the start on, because that isn't the case. With 'default configuration' I mean for example the syntax highlighting which was gone as soon as I created a .vimrc file myself.

**Comment by holzschu** [comment]
You have to create the file.
