### ISSUE TITLE
Unable to run Python

### ISSUE THREAD

**Issue by ghofferek** [holzschu/a-shell#434]
I just installed a-Shell on my iPad, opened it and tried to run Python. I got the following error:

`
[~]$ python
Failed loading python from python3_ios.framework/python3_ios, cause = dlopen(python3_ios.framework/python3_ios, 0x0009): tried: '/private/var/containe
rs/Bundle/Application/6D9EF2C8-5F97-4499-A313-685908BE5208/a-Shell.app/Frameworks/python3_ios.framework/python3_ios' (could not register fairplay decr
yption, mremap_encrypted() => -1), '/private/var/containers/Bundle/Application/6D9EF2C8-5F97-4499-A313-685908BE5208/a-Shell.app/Frameworks/ios_system.
framework/Frameworks/python3_ios.framework/python3_ios' (no such file), '/usr/lib/swift/python3_ios.framework/python3_ios' (no such file), '/private/v
ar/containers/Bundle/Application/6D9EF2C8-5F97-4499-A313-685908BE5208/a-Shell.app/Frameworks/python3_ios.framework/python3_ios' (could not register fa
irplay decryption, mremap_encrypted() => -1), 'python3_ios.framework/python3_ios' (relative path not allowed in hardened program), '/System/Library/Fr
ameworks/python3_ios.framework/python3_ios' (no such file)
python: command not found
[~]$ 
`

**Comment by holzschu** [comment]
Hi, 
thanks for reaching out about this issue.
I'm taking a wild guess, but I think all commands are giving you the same error message, is that correct?

It looks like a faulty install; I would suggest uninstalling and reinstalling.

**Comment by ghofferek** [comment]
Hi,some other commands (perl, vim, …) give the same error. Others seem to work. I will try to remove and re-install and see if that fixes the issue. Thanks for the fast reply!Gesendet mit der mobilen Mail AppAm 24.07.22 um 11:07 schrieb Nicolas Holzschuch
                
            
            
                
                    Von: "Nicolas Holzschuch" ***@***.***>Datum: 24. Juli 2022An: "holzschu/a-shell" ***@***.***>Cc: "Georg Hofferek" ***@***.***>,"Author" ***@***.***>Betreff: Re: [holzschu/a-shell] Unable to run Python (Issue #434)
                
                
Hi,
thanks for reaching out about this issue.
I'm taking a wild guess, but I think all commands are giving you the same error message, is that correct?
It looks like a faulty install; I would suggest uninstalling and reinstalling.

**Comment by ghofferek** [comment]
You were right. Removing and reinstalling did solve to problem!
Thanks again for your very fast response!
I‘ll close the issue.

**Comment by holzschu** [comment]
Out of curiosity, was your device jailbroken at the time? I'm trying to understand what causes the issue.

**Comment by ghofferek** [comment]
Hi,no, my device never was jailbroken at any time.Best regardsGesendet mit der mobilen Mail AppAm 01.11.22 um 17:53 schrieb Nicolas Holzschuch
                
            
            
                
                    Von: "Nicolas Holzschuch" ***@***.***>Datum: 1. November 2022An: "holzschu/a-shell" ***@***.***>Cc: "State change" ***@***.***>,"Georg Hofferek" ***@***.***>Betreff: Re: [holzschu/a-shell] Unable to run Python (Issue #434)
                
                
Out of curiosity, was your device jailbroken at the time? I'm trying to understand what causes the issue.

**Comment by holzschu** [comment]
I suspected as much. Thanks for confirming this.
