### ISSUE TITLE
How to know the end of an a-Shell action ?

### ISSUE THREAD

**Issue by Sylvin78** [holzschu/a-shell#439]
Hi ! I am trying to make a shortcut which launch a python script. It works pretty well and thanks a lot for a-Shell. However, the actions after the one which launches the python script begins before the end of the python script execution. To solve this problem, I added an action to wait 10 seconds but it is not the best solution. So is there a way to stop the shortcut while the python script execution is not finished ?
Thanks a lot for your help !

**Comment by Sylvin78** [comment]
I have just found how to do it with the command line « open shortcuts:// ». It was pretty simple, sorry

**Comment by bordam** [comment]
Can you share how you do it with the open shortcuts://

**Comment by Sylvin78** [comment]
Hello ! You have an example at the end of this shortcut here : https://www.icloud.com/shortcuts/529b1c172d724344a3b1757e9cf1e56b

**Comment by bordam** [comment]
Hey! Thank you, I have tried looking into it but that's a LONG shortcut 😳😳 never seen one like this

At the end, I figured it out: I had to insert a Wait to return block after the execution of open shortcuts://
