### ISSUE TITLE
yt-dlp broken after version 2022.4.8 - xattr/lib_build.h missing header

### ISSUE THREAD

**Issue by gbu117** [holzschu/a-shell#447]
Latest version of yt-dlp installed with the --no-deps option. This works fine until after v2022.4.8. I am not sure if this is at all related to pycryptodomex given the references in the output, so maybe with the 1.9.5 release things will improve. Given the main issue seems to be related to a missing xattr header, maybe this is an issue with the lack of support for pyxattr even though the xattr package supposedly is enough according to yt-dlp's dependencies.py.

```

Successfully installed yt-dlp-2022.8.19
[Documents]$ ytdl -h
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/xattr/lib.py", line 7, in <module>
    from ._lib import lib, ffi
ImportError: dlopen(/private/var/containers/Bundle/Application/*/a-Shell.app/Frameworks/pythonA-xattr._lib.framework/pythonA-xattr._lib, 0x0002): tried: '/private/var/containers/Bundle/Application/*/a-Shell.app/Frameworks/pythonA-xattr._lib.framework/pythonA-xattr._lib' (no such file), '/System/Library/Frameworks/pythonA-xattr._lib.framework/pythonA-xattr._lib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/*/Library/bin/ytdl", line 5, in <module>
    from yt_dlp import main
  File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/yt_dlp/__init__.py", line 18, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/yt_dlp/cookies.py", line 16, in <module>
    from .aes import (
  **File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/yt_dlp/aes.py", line 5, in <module>**
    **from .dependencies import Cryptodome_AES**
  File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/yt_dlp/dependencies.py", line 79, in <module>
    **import xattr  # xattr or pyxattr**
  **File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/xattr/__init__.py", line 13, in 
<module>**
    **from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,**
  **File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/xattr/lib.py", line 9, in <module>**
    **from .lib_build import ffi, c_source**
  **File "/var/mobile/Containers/Data/Application/*/Library/lib/python3.9/site-packages/xattr/lib_build.py", line 7, in <module>**
    **with open(os.path.join(PATH, 'lib_build.h')) as**
 **hf:**
**FileNotFoundError: [Errno 2] No such file or directory: '/var/mobile/Containers/Data/Application/*/Library/lib/python3
.9/site-packages/xattr/lib_build.h'**
```

**Comment by holzschu** [comment]
I don't have the issue on my end. yt-dlp does install `ytdl`, but rather `yt-dlp`, and `yt-dlp -h` does not create the issue. 

Maybe `ytdl` is left over from a previous install?

**Comment by gbu117** [comment]
I have an alias, I should have said. youtube-dl isn't installed.

**Comment by gbu117** [comment]
I'm  running v1.9.4 not testflight to be clear.

**Comment by holzschu** [comment]
I looked at my install, and I do not have xattr, or pyxattr. It is not listed as a dependency for `yt-dlp` through `pip`. This is going to be counter-intuitive, but maybe try to *remove* xattr?

**Comment by holzschu** [comment]
I can confirm (looking at `yt_dlp/dependencies.py`, line 79): if you don't have xattr, then `yt_dlp` will work without it (it tries to load it, but if it's not available it does not cause an error).

Another thing: `brotli` is not going to work (it installed an OSX library), but it won't be an issue unless you try to use the format.

**Comment by gbu117** [comment]
Solved :) Sorry, I should have tried that. I wonder why the header file is missing nonetheless. xattr/pyxattr is an opptional dependency according to dependencies.py.
