### ISSUE TITLE
How to execute bash script ? there has another package manager  than pip ?

### ISSUE THREAD

**Issue by poneoneo** [holzschu/a-shell#453]
I've tried to run bash file like I do usually : 
./filename.sh
 even with bash ./filename.sh but each I have 
"bash: command not found "

So how could I manage my bash script...

Also there has another package manager than pip ?

**Comment by holzschu** [comment]
We can not provide bash, but we do have dash if you want to run shell scripts.

(bash is covered by the GPL, and the FSF position is that the GPL is incompatible with AppStore distribution).

Apple rules forbid the extension of an application by adding binaries after the review process, so a package manager is difficult. The next version will have one, but it will be limited to a few commands at first.
