### ISSUE TITLE
[IPHONE] This character "*" cannot be used in this scene.

### ISSUE THREAD

**Issue by mamanngaga01** [holzschu/a-shell#454]
mogrify -format png *.jpg 

I used it in the image in the document, but it didn't work.

**Comment by mamanngaga01** [comment]
![IMG_7916](https://user-images.githubusercontent.com/91867174/188113333-72e174dc-661f-43c0-b374-ae016695d1d9.PNG)


It may be because it is a Japanese iPhone.

**Comment by holzschu** [comment]
From what I can see, the most likely cause for the message is that there are no files ending with `.jpg` in this directory, hence the "no such file or directory".

If your goal was to convert all `*.png` files into `jpg` files, then the command should be: `mogrify -format jpg *.png`.

**Comment by mamanngaga01** [comment]
Thank you! it is complete.
I thought that if "*" was entered, non-ASCII would need an absolute path and could not be done.
