### ISSUE TITLE
vim can't delete things when create .vimrc

### ISSUE THREAD

**Issue by yenw** [holzschu/a-shell#455]
step1: write something in .vimrc
step2: edit other file
step3: i 
step4: write something
step5: delete char by char

I can't delete any blank line in the insert mode.
sometimes, I can't delete any char.

when I delete the .vimrc file, all is work normally and I can delete anything.

a-shell version: 1.9.4

**Comment by holzschu** [comment]
Hi, 
thank you for spotting the difference of behaviour between "no vimrc file present" and "a vimrc file present". I had noticed, too, that deleting char by char did not work for me either in insert mode, but I had not made the connection with the `.vimrc` file.

A quick search on the internet tells me that we should both add the line `set backspace=indent,eol,start` to our `.vimrc`files. I think this is set in a default options file that is not loaded if a `.vimrc` file is present.

**Comment by yenw** [comment]
I comform it the add 'set backspace=indent,eol,start' in the '.vimrc' is work.
thanks for your answer.

**Comment by holzschu** [comment]
Thank *you* for asking the question! I was having the same issue, but I did not realize I could solve it until you asked!
