### ISSUE TITLE
pip Install Issue

### ISSUE THREAD

**Issue by Skridiotic** [holzschu/a-shell#466]
I've been using a-shell for a while now, but when I attempt to install a pip package (more specifically, getkey), it gets terminated and I get the "Too many Python scripts" prompt.

I'm on iOS 16 with an iPhone SE 2nd Generation. 

Just wanted to know if there was a way to workaround this or if it's an actual issue.

**Comment by holzschu** [comment]
Interesting. I have the same issue with getkey on my iPhone (running iOS 16) but not on my iPad (still running iOS 15).
I'm investigating.

**Comment by holzschu** [comment]
If you run:
```
pip install flake8
pip install getkey
```
the install process will work. It's an issue caused by the install process on getkey calling `pip install flake8` rather than listing flake8 as a dependency.

I was worried this could be an issue caused by iOS 16, but it seems not to be the case.

**Comment by Skridiotic** [comment]
Ah, cool!
Thanks for your help, it's working for me fine now.
