### ISSUE TITLE
[Feature Request] Support Up(La)TeX?

### ISSUE THREAD

**Issue by RadioNoiseE** [holzschu/a-shell#489]
LuaLaTeX is already very good. But the luatex-ja macro-package used to typeset CJK is an incomplete porting of pTeX. And it's much slower than pTeX, also uses a lot of memory.
So is there a chance to support the up(La)TeX engine extension?

**Comment by holzschu** [comment]
I'm ready to give it a try with the port to texlive 2023.
As I have no knowledge here, which of the engines are required? pTeX, epTeX, upTeX, eupTeX?

**Comment by RadioNoiseE** [comment]
It should be upeTeX(and upeLaTeX).

Thanks for considering this feature request!

**Comment by holzschu** [comment]
Thanks. I've had a look; since they both produce DVI files, that means I have to port `dvipdfmx` first. Let's see.

**Comment by holzschu** [comment]
Thanks for the reply; there's no hurry, the compilation process is very slow.

**Comment by RadioNoiseE** [comment]
In this repo: `https://github.com/texjporg/uptex-base/tree/master/samples` are some small example files that show many functionalities of euptex.

The file `00readme_uptex_samples.txt` is an explanation (or index?) of which functionality can each file test.

**Comment by holzschu** [comment]
Awesome, thank you very much!

**Comment by holzschu** [comment]
Hi, 
the latest TestFlight version has uptex and euplatex: https://testflight.apple.com/join/WUdKe3f4

It works in my tests, except for inclusion of postscript files (but that was expected: there's no Ghostscript for iOS).

**Comment by RadioNoiseE** [comment]
Great!
I think this feature request can be closed as complete now
