### ISSUE TITLE
Changing how the app looks

### ISSUE THREAD

**Issue by sahil48** [holzschu/a-shell#49]
Is there a way to change the font size or color of the text and background?

**Comment by holzschu** [comment]
Not yet, except that we take iOS dark mode / light mode settings. It is coming.

**Comment by phu54321** [comment]
Hello, is this issue being considered? I want to use dark mode while keeping my ipad on light mode.

**Comment by holzschu** [comment]
The "config" command lets you set up the colors (background and foreground), the font used, the font size... And you can do this on a window basis, or generally. Try "config -h" for help, or "man config".

**Comment by sahil48** [comment]
Thank you!
