### ISSUE TITLE
I broke it lmao

### ISSUE THREAD

**Issue by Luxvao** [holzschu/a-shell#496]
I downloaded a-shell today and wanted to see if I can break it. I thought it may take a while, but I broke it already. So if I cd into Library, then cd into usr, then cd into Include and then I just cd .. and cd .., it breaks it gets me access to the root I think (I have folders like /bin/ and others). So to recap:
```
cd Library
cd usr
cd Include
cd ..
cd ..
```
(maybe another `cd ..` I can't test it)

**Comment by holzschu** [comment]
Yes, a-Shell gives you access to the iPhone file system, as far as Apple permits it (they are very restrictive, as you will find out). All system calls are direct iOS system calls, which explains many of the peculiarities.

You can just type `cd /`, and you will be at the root of the file system. From here, you can `ls`, and see folders. Most of them are restricted, but you can `cd` into `System/Library`, for example. In short, you can explore and see many things, but only the things Apple allows you to see.

**Comment by Luxvao** [comment]
I checked and you have to do cd .. twice. Also it drops you into a-shell.app and you can see the app icon

**Comment by holzschu** [comment]
For that directory, you can just type `cd $APPDIR`.

**Comment by Luxvao** [comment]
Okay thanks
