### ISSUE TITLE
Does A-shell have support for bashrc files or something like that?

### ISSUE THREAD

**Issue by YousufSSyed** [holzschu/a-shell#502]
I would like to be able to have a .bashrc file for things like aliases. I know that you can set in an alias by doing `alias something=something`, but that doesn't persist after you exit the app.

**Comment by YunHsiuLu** [comment]
Hi! I would like to ask a similar question: is it able to echo a self-designed .profile? I have tried to do `echo "Hello There!"` in .profile but shows nothing :((

**Comment by YousufSSyed** [comment]
- Why doesn't it support multi-line execution?
- How could I easily edit the .bashrc file outside of A-Shell? 
- Because it starts with a dot, it's a hidden file in the Files app I tried symlinking a bashrc (without the dot) to .bashrc in the home directory but that didn't work. Is it possible to do that?

**Comment by holzschu** [comment]
- the `.bashrc` file is executed by a-Shell own terminal, not by a full-blown shell, hence the restriction. Each line is read, then sent to execution.
- to answer your other two questions: you have two solutions. Probably the easiest for you would be to create a hard link instead of a symbolic link: `ln .bashrc bashrc`. The files app can follow hard links (because it does not actually have to follow them, it's as if the file was in two places at the same time). The other solution is to temporarily rename the file to, say, `bashrc` while you edit it.

**Comment by YousufSSyed** [comment]
* What stops A-Shell from supporting multi-line execution? I was going to ask about that, since I couldn't get multiple commands working in one line with characters like `&&` and `\` .
* I don't think the `ln` thing works well, or is finicky at best. I tried doing `ln .bashrc bashrc.txt`, but when I would try restarting A-Shell with just pickFolder or `jump "Folder name"` (folder name already being bookmarked and working with `jump` in the terminal) in the file, but neither seemed to be working. Could you perhaps give specific instructions for how you get `.bashrc` linking, editing the linked file, and refreshing A-shell to work correctly? To reproduce exactly what you did?
* Would it be possible to `ln` to a file in iCloud, so I could have `.basrhc` it sync between devices?

**Comment by holzschu** [comment]
I don't understand what you mean with "but when I would try restarting A-Shell with just pickFolder or jump "Folder name" (folder name already being bookmarked and working with jump in the terminal) in the file, but neither seemed to be working.". It seems a very strange thing to do. 

- type `ln .bashrc bashrc.txt` in a-Shell.
- open the File app, navigate to the a-Shell folder.
- edit the "bashrc.txt" file using whatever tool you like.
- go back to a-Shell.
- your ".bashrc" file has also been edited.

Hard links are just that: two different names that point to the same file. On the other hand, you cannot hard-link across volumes, so no, you cannot hard link with a file in the Cloud.

**Comment by YousufSSyed** [comment]
When I try to `sh -c "jump folder" && "python3 script.py"` to launch a Python script that takes input, I can't do input, but it works fine when I run the two commands by themselves. Try this: 
* create a script `script.py` in whatever folder and put this in: `print(input("Type something: "))`
* then try the command: `sh -c "jump folder" && "python3 script.py"`

**Comment by YousufSSyed** [comment]
By the way, lately I've noticed the execute script shortcut in the Shortcuts app work consistently. When I first started using A-Shell back in July, it didn't work consistently. Did you make changes to the shortcut since then?

**Comment by holzschu** [comment]
About your question on "sh -c": the short answer is yes. "sh -c" is for running commands that don't take input and produce output.

About shortcuts: no I did not change anything. Apple might have changed things in the system.
