### ISSUE TITLE
Help Regarding a-shell

### ISSUE THREAD

**Issue by Karthik-20034** [holzschu/a-shell#507]
**Hey Developer,**

- > I am Here to seek a help to you.
      How to install packages like aria2c,bento4,mkvmerge,shaka packager etc….
      It will be great if you help these packages in a-shell.

**Comment by holzschu** [comment]
I'll keep it mind, but adding new programs is always a bit of work. It would help if you could provide a link to the source code, and a bit of information about what they do and how many people would be interested.
