### ISSUE TITLE
How to save config (theme) for a-shell (Use the same config every time you open it)

### ISSUE THREAD

**Issue by C4ntor** [holzschu/a-shell#509]
Currently every time I open a new a-shell my previous configuration with font size, font's color and background's color will not be applied, So I am asking if is there a way to save the config in order to apply it to each new shell, and to automatically load it every time you close a-shell and re-open it (without manually set the config again every time)

**Comment by holzschu** [comment]
"config -p" for "permanent" will store current settings as default values from now on.

**Comment by C4ntor** [comment]
Thanks!

**Comment by C4ntor** [comment]
Are there any commands available to change cursor shape of terminal? Usually in terminal app you can choose between  Vintage ( ▃ ), Bar ( ┃ ) (default), Underscore ( ▁ ), Double underscore ( ‗ ), Filled box ( █ ), or Empty box ( ▯ ).

**Comment by holzschu** [comment]
This is a little more involved, but you can call the JavaScript function `window.term_.setCursorShape('UNDERLINE')` using `jsi --window`. The function takes three options, BEAM, UNDERLINE and BLOCK.

**Comment by C4ntor** [comment]
> This is a little more involved, but you can call the JavaScript function `window.term_.setCursorShape('UNDERLINE')` using `jsi --window`. The function takes three options, BEAM, UNDERLINE and BLOCK.


I tried to launch the command but it doesn't recognize it
![IMG_0154](https://user-images.githubusercontent.com/116038756/203834539-4ba599ca-9384-4ed4-ad9b-7e6b63050eb7.PNG)

**Comment by holzschu** [comment]
Sorry, I made a mistake. That’s `jsi -w` to open the JavaScript interpreter with the option to change window settings:
![2BE5CF25-F8CD-4A20-AD13-7ED12F91AB13](https://user-images.githubusercontent.com/8070736/203835982-e1a567d8-b46a-43d2-8e78-71fc4c1d8c98.jpeg)

You can also call `jsc --in-window file.js`, where `file.js` is a file that contains the  JavaScript line you want.

**Comment by C4ntor** [comment]
> Sorry, I made a mistake. That’s `jsi -w` to open the JavaScript interpreter with the option to change window settings: ![2BE5CF25-F8CD-4A20-AD13-7ED12F91AB13](https://user-images.githubusercontent.com/8070736/203835982-e1a567d8-b46a-43d2-8e78-71fc4c1d8c98.jpeg)
> 
> You can also call `jsc --in-window file.js`, where `file.js` is a file that contains the JavaScript line you want.

ok thanks, but is there a way to save permanently the cursor shape?

**Comment by C4ntor** [comment]
> > Sorry, I made a mistake. That’s `jsi -w` to open the JavaScript interpreter with the option to change window settings: ![2BE5CF25-F8CD-4A20-AD13-7ED12F91AB13](https://user-images.githubusercontent.com/8070736/203835982-e1a567d8-b46a-43d2-8e78-71fc4c1d8c98.jpeg)
> > You can also call `jsc --in-window file.js`, where `file.js` is a file that contains the JavaScript line you want.
> 
> ok thanks, but is there a way to save permanently the cursor shape?

otherwise each time I close the shell, the cursor shape will come back to the standard one.

**Comment by holzschu** [comment]
The `.bashrc` and `.profile` files are both executed each time a-Shell opens a new window. You can place the line `jsc --in-window cursorShape.js` in one of these, it should restore the cursor shape each time you log in.

**Comment by C4ntor** [comment]
> The `.bashrc` and `.profile` files are both executed each time a-Shell opens a new window. You can place the line `jsc --in-window cursorShape.js` in one of these, it should restore the cursor shape each time you log in.

Where can I find these two files?

**Comment by C4ntor** [comment]
> > The `.bashrc` and `.profile` files are both executed each time a-Shell opens a new window. You can place the line `jsc --in-window cursorShape.js` in one of these, it should restore the cursor shape each time you log in.
> 
> Where can I find these two files?

I cannot find these files (neither using a command like find) so I created a new one in the Documents folder, but it seems it doesn't get recognized as .profile file, and I cannot move it into the home directory ~ because I get and error: 'Operation not permitted'

**Comment by holzschu** [comment]
By default, these two files do not exist. If the user creates them, then they are executed. They should be in `~/Documents`, since `~` is not allowed for writing, as you found out. I can guarantee that `.profile` is indeed executed, but it might be that the cursor shape is reset after the `.profile` is executed.

**Comment by C4ntor** [comment]
I created both `.profile` and `.bashrc` in my `~/Documents` but neither of them seems to be executed when I open the shell. Because when I try to execute any command contained in .bashrc and .profile (they contain the same following code: `jsc --in-window test.js` ), they don't run the test.js file. Considered that, as you said, cursor shape could be reset after .profile is executed, I tried to execute something else just to test if` .profile `and `.bashrc` are executed at the start, testing other commands like a simple `console.log("hey");` that is stored in the file named test.js

**Comment by C4ntor** [comment]
I want also to say that you have two Cursors (the one of the terminal that you can customize, and the other cursors, the slim vertical bar that seems to be the typical iOS cursor) it would be great if you could show just one of them. Because sometimes a bug occurs, for example (as you can see from the video here in attachments) when editing something in Vim, if you press the spacebar the two cursors will not be "aligned", however they will get back when you start to writing something after that space. Please fix this. 

https://user-images.githubusercontent.com/116038756/204086336-cbabae3a-9907-495e-ba58-f6a7a6951695.mp4

**Comment by holzschu** [comment]
- I confirm that the `.profile` is executed, but the windows settings are executed after it, so the result is overridden. I can add a configuration settings for the cursor shape in `config`. 
- I know about the two cursors thing. It is really annoying, but I haven't found a way to remove the second one.

**Comment by C4ntor** [comment]
> * I confirm that the `.profile` is executed, but the windows settings are executed after it, so the result is overridden. I can add a configuration settings for the cursor shape in `config`.
> * I know about the two cursors thing. It is really annoying, but I haven't found a way to remove the second one.

I appreciate it, I will wait for the next update on the AppStore.

**Comment by C4ntor** [comment]
Hi, I was wondering if from the shell I could see all my files (showed in the File manager App of Apple) but it doesn’t seems possible, but from the File app I can actually see files that I created and that can bee viewed from the terminal (for example the file `we` ). Also is there any possibility of enable a drag and drop option of a file in the shell. copying automatically its path ? (See the video in attachments for more details)

https://user-images.githubusercontent.com/116038756/204113207-dc827334-6ddc-463c-8b1a-e617cf6a7c7d.mp4


https://user-images.githubusercontent.com/116038756/204113329-0dd768c2-b23d-4af3-ab53-2221dcf758ee.mp4

**Comment by holzschu** [comment]
Hi, 
File access is one of the points where iOS differs more strongly from other systems, mainly for security reasons.
- the Files app does not show files and directories that begin with "." These are "hidden" files in the Unix world. It does show all the other files.
- by default, an app can only see its own files (everything under `~`) and the Files app can see all the public files from all apps (everything under `~/Documents/` for each app). 
- you can make a-Shell access public files and directories from other apps using `pickFolder`. By clicking on a folder, you are granting a-Shell the right to access that folder.

If you want to access hidden files from the Files app (either files in `~/Library` or files that begin with a `.`), there are few options:
- you can copy it to `~/Documents`, for example `cp .profile profile.txt`, then edit it using the Files app, then copy it back.
- you can create a hard link with `ln .profile profile.txt`. Now `.profile` and `profile.txt` are two names for the same file. If you edit `profile.txt` using the Files app, your changes are reflected in `.profile`. 

I'll have a look at the drag-and-drop stuff.

**Comment by C4ntor** [comment]
Great! thanks.
