### ISSUE TITLE
Help !!!

### ISSUE THREAD

**Issue by Karthik-20034** [holzschu/a-shell#511]
How to copy paste txt files in a-shell…somebody help me….please…..

**Comment by holzschu** [comment]
You might be looking for the `pbcopy` and `pbpaste` commands. Unless I misunderstood the question; if you can explain a bit more what the issue is?

**Comment by Karthik-20034** [comment]
The Problem is when I  copied a cookies.txt from iOS files download section and I wanted to paste it into a file which is not present in files app.so I come across to use cli.but I don't know how to copy and paste into a directory in A-Shell.

**Comment by holzschu** [comment]
If it is a file that you want to copy and paste, then you need to copy and paste it from the Files app (a-Shell can only copy and paste text).

You can, for example, copy the file to a-Shell directory using the Files app, then use the command line to move it to a different place (`cp file newPlace`). However, there are no miracles: you can only copy it to places that a-Shell is authorized to access: a-Shell main directory, a-Shell iCloud directory, a-Shell shortcuts directory, and directories that you have accessed with `pickFolder`. If you cannot access it from the Files app, there is a strong likelyhood that you cannot access it from a-Shell either. Where are you trying to copy the file?

**Comment by Karthik-20034** [comment]
I tried but I had no idea on how to copy.reference image given below.
![DDED770F-8D27-415A-ABB7-A8E2A9EF9FBB](https://user-images.githubusercontent.com/83129674/204068105-dd0d90c2-1970-474e-b16a-4ff7059650d2.jpeg).the left side image is the file that I want to copy.

**Comment by Karthik-20034** [comment]
Thanks.My Problem Is Solved.Thank You For Your Helping mind..
