### ISSUE TITLE
Is there a way to exit out of the Python interpreter or other CLIs?

### ISSUE THREAD

**Issue by YousufSSyed** [holzschu/a-shell#514]
Normally to exit a CLI or python3, you would press CTRL + C or CTRL + D, I don't know if that possible with A-Shell. If you want to test it, enter in `python3` in the app.

**Comment by holzschu** [comment]
Hi, 
control-D works on my end. If it doesn't on your machine, then that means it is something I have fixed since the last release, and the change will be in the next release. That being said, `quit()` always works in python3, and I recommend using `ipython` rather than `python3`.

**Comment by YousufSSyed** [comment]
Oh I got it working, I couldn't get CTRL + C working and assumed that CTRL + D didn't work either. Anyways, thanks.

**Comment by YousufSSyed** [comment]
@holzschu btw can you look at my other open issues? I had asked more questions there.
