### ISSUE TITLE
What data in A-Shell migrates between iPhones and what data doesn't?

### ISSUE THREAD

**Issue by YousufSSyed** [holzschu/a-shell#515]
I upgraded to the iPhone 14PM and am going to return the 13 I got. I noticed that all of my pip packages were already installed when I used pipreqs and `pip install -r requirements.txt`, as well running my scripts. However, I noticed my bookmarks weren't and I had to do `pickFolder` again to recreate them.

**Comment by holzschu** [comment]
This is more about what Apple transfers from one phone to the other, not about a-Shell itself. The content of the home directory for the app is copied to the new phone, so everything under `~`: `~/Library`, `~/Documents/`. The bookmarks are not transferred, because the directories are different.

**Comment by YousufSSyed** [comment]
Ah I see.
