### ISSUE TITLE
MuPdf

### ISSUE THREAD

**Issue by thetrilogy19** [holzschu/a-shell#520]
It's command line tool `mutool` would be quite helpful at processing pdf (and probably EPUB).

**Comment by holzschu** [comment]
mupdf relies on Ghostscript, and so it will be really difficult to cross-compile. Also, it is either distributed under the GPL (which is not compatible with appStore release), or under a commercial license (which I cannot afford).

**Comment by thetrilogy19** [comment]
I see. Thanks anyway.
