### ISSUE TITLE
Is it possible to add custom fonts to A-Shell?

### ISSUE THREAD

**Issue by YousufSSyed** [holzschu/a-shell#525]
If not, there should be an GUI and command to select font files (preferably support multiple formats) and set them as the terminal font.

**Comment by Majixed** [comment]
You can install custom fonts with an installer such as iFont, these can be found om the App Store. Then open a-Shell and run `config -n`, and you should see your font appear in the menu.

**Comment by YousufSSyed** [comment]
That works, thanks!

**Comment by 4rc0s** [comment]
I have a managed iPad that I can't install profiles on, so installers like iFont won't be an option. Would it be possible to bundle a couple of additional terminal fonts with a-shell itself? If so, I'd vote for the Nerdfont variants of JetBrains Mono and Ubuntu Monospace. Thanks!
