### ISSUE TITLE
How do I get tab-completion to work on items in ~/Library/bin ?

### ISSUE THREAD

**Issue by naryfa** [holzschu/a-shell#526]
Hello,

As in the subject... I placed a pre-compiled speedtest-cli in ~/Library/bin

I then issued: _source .profile_ to refresh things.

I had hoped it would tab-complete when I type _spee_

I then put it in .profile as an alias named _speedtest_, but it still won't tab-complete.

What am I doing wrong? When I issue the full speedtest-cli command, it works OK.

Please help.

**Comment by holzschu** [comment]
I think the autocomplete list for binaries is re-generated only when a new window is created (or when the app restarts).
I need to think if I can have a command to re-generate it, or if I can do it on the fly.

**Comment by naryfa** [comment]
It would be really cool to be able to re-generate it or have it done on the fly.

But I am closing this now. Perhaps you can add some information to the  [README.md](https://github.com/holzschu/a-shell#readme)? I mean that the autocomplete requires a new window and also which directories fall under the autocomplete (I'm just assuming that's $PATH)? At least that's something for goofs like myself lol.
