### ISSUE TITLE
Unable to install Git (lg2) on A-Shell

### ISSUE THREAD

**Issue by YousufSSyed** [holzschu/a-shell#528]
When I run pkg install git, It outputs this:
```
Downloading git
The git command cannot be included with
a-Shell. Would you like to create a
script at $HOME/Documents/bin/git that
wraps lg2 with the following contents?
#!/bin/sh
lg2 "$@"
Keep in mind that git and lg2 options
are not 100% compatible, and they also
do not use the same configuration files
or environment variables.
Create $HOME/Documents/bin/git? (y/n [n]) y
The $HOME/Documents/bin directory does not exist.
Exiting without creating wrapper.
Done
```

**Comment by holzschu** [comment]
That's a bug in the git package, I will fix it. In the meantime, as it said, you just have to create the bin directory yourself:
`mkdir ~/Documents/bin`, then run `pkg install git` again.

**Comment by YousufSSyed** [comment]
It works. If Git is a wrapper for lg2, shouldn't you add `pkg install lg2`? 

Also, in CLIs, adding `-y` automatically says yes to dialogues. I think you should have it here too. Like `pkg install git -y`.

**Comment by holzschu** [comment]
lg2 is part of the binaries that are installed by default. Because it is a binary, it cannot be installed by the user.

I'll think about the "-y" option, but for now git is the only package that has a dialog, and the warning is relatively important, so I think it's good if the users read it.

**Comment by GodsGear** [comment]
pkg install git is still not working for me. Even when I make a directory called bin. It still asks me if I want to create a wrapper
