### ISSUE TITLE
credential helpers for lg2

### ISSUE THREAD

**Issue by michaelrommel** [holzschu/a-shell#532]
Hi,

I was experimenting with different ways to have credentials stored for lg2 to push without having to repeatedly enter a personal access token.

I have not gotten any way to work, even in the simplest case of a helper shell script with all commands available, I could not avoid the prompt.

```
[credential "https://github.com/michaelrommel/myrepo"]
        username = michaelrommel
        helper = "!f() { test \"$1\" = get && echo \"password=$(cat $HOME/Documents/.myrepo-cred)\"; }; f"
```

Is there any way to achieve this with lg2?

Thanks - I haven't found a solution in any of the documentation or issues. Did I overlook this?

**Comment by holzschu** [comment]
Hi, 
I didn't know of this authentication method until your post, so I don't know how it is handled in libgit2. The only documentation I found so far is here: https://libgit2.org/docs/guides/authentication/ but it doesn't match with your use.

It would be good to know what is happening (is the "[credential]" part of the configuration file completely ignored, or is it executed but the system but the helper command is too complex for a-Shell simplified shell?)

**Comment by michaelrommel** [comment]
Hi,
I tried different variations, the simplest was:
```
[credential]
    username = michaelrommel
    helper = "store --file $HOME/Documents/.myrepo-cred"
```
with a line that is containing the URL and the password, just like in standard .git-credentials files.

Both variants (I tested them in iSH with regular git) were still asking interactively for the password only, not the username.
So, I don't exactly know, if they are ignoring the [credential] section completely. I would have liked to look at how the `lg2` binary is compiled, but I was not able to find that in a-shell, ios-system or your fork of libgit2... Where is the file that produces the lg2 binary which then links against libgit2? Maybe I can then find out more about this topic. I just wanted to store the Personal Access Tokens (fine grained only for a particular repo) for two repos on github, therefore need to differentiate the files where the credentials are stored.

**Comment by tino** [comment]
FYI I'm using a Github deploy key with write permission as such:
```
[remote "origin"]
  url = git@github.com/my/repo
[user]
  password = ""
  identifyFile = id_ed25519
  ...
```
I generated the ssh key with `ssh-keygen` in a-Shell mini, and it's in the home directory in `.ssh`.

**Comment by holzschu** [comment]
Yes, that's what I'm doing too (using an ssh key to access GitHub), but I felt that was kinda cheating in terms of answering the question.

Now, there is one question I *can* answer: the source for the lg2 command is here: https://github.com/holzschu/libgit2/tree/main/examples (`lg2.c` is the main file, the others are for the commands).

**Comment by michaelrommel** [comment]
Dear guys,

thanks so much for your pointers. Those are enough to get me going and exploring more. I will close the issue now as I believe I will get either version working for me and I don't want to keep the issue list cluttered!

Thanks again everyone, I hope that the a-shell approach survives the Apple Review process longterm!

  Michael.
