### ISSUE TITLE
unrar p command stdout missing

### ISSUE THREAD

**Issue by adbennet** [holzschu/a-shell#552]
e command works, p command does not. I'm trying to pipe a password protected file to grep without saving to disk first.
1. password is echoed in the terminal, less than ideal
2. p command does not print file contents on the terminal

Simple example session, password is xyzzy.

[Documents]$ ls
foo.rar foo.txt
[Documents]$ cat foo.txt
foo
bar
baz
[Documents]$ rm foo.txt
[Documents]$ unrar v foo.rar
UNRAR 6.02 freeware      Copyright (c) 1993-2
021 Alexander Roshal
xyzzy
Archive: foo.rar
Details: RAR 5, encrypted headers
 Attributes      Size    Packed Ratio    Date
    Time   Checksum  Name
\----------- ---------  -------- ----- -------
\--- -----  --------  ----
\*-rw-r--r--        12        32 266%  2023-01
-22 17:32  943E0A1B  foo.txt
\----------- ---------  -------- ----- -------
\--- -----  --------  ----
                   12        32 266%         
                     1
[Documents]$ unrar p foo.rar
UNRAR 6.02 freeware      Copyright (c) 1993-2
021 Alexander Roshal
xyzzy
Extracting from foo.rar
------ Printing foo.txt
  43%
All OK
[Documents]$ unrar p -inul foo.rar
xyzzy
[Documents]$ unrar e -inul foo.rar
xyzzy
[Documents]$ ls
foo.rar foo.txt
[Documents]$ cat foo.txt
foo
bar
baz
[Documents]$

**Comment by holzschu** [comment]
Hi,
thanks for pushing this one to the front of the pile. Other users had reported it before, but I hadn't been able to find where `unrar` was writing with `p`. I have now found it (it uses `STDOUT_FILENO`), so it will be fixed in the next release. 

For the password being visible, that's a bit more difficult. I'll keep it in mind.

**Comment by adbennet** [comment]
I just updated to 1.10.4 and `unrar p` is working great. I am closing this issue since that was the part I really needed. The echo masking I guess is a general problem across all commands.

Where is the donate button?

**Comment by holzschu** [comment]
I'm trying to keep this work free from monetary issues, so there's no donate button. I gladly take donations in kind: tests, reports, suggestions and code changes (*especially* code changes).
