### ISSUE TITLE
Feature request - send ctrl space to terminal

### ISSUE THREAD

**Issue by m-zheng** [holzschu/a-shell#556]
Hi, thanks for making such a nice app. I am just wondering if it is possible to send ctrl space to terminal (A-Shell) rather than switching the keyboard layout? This feature could be very useful when working on a remote machine via A-Shell.

**Comment by holzschu** [comment]
Hi, that one would be tricky. For one thing, a lot of people appreciate the quick change to the keyboard layout (myself included), especially when dealing with multiple languagues. 
Also, it's one of the system shortcuts, so I don't know how feasible this is.
What I would suggest is to use the newly introduced ability to change the toolbar (`config -t`, then follow instructions) and add a button to send control-space to the terminal.

**Comment by m-zheng** [comment]
This is a feature provided in [iSH](https://github.com/ish-app/ish). Users are allowed to turn it on/off as the screenshot shown below. It might not be doable in A-shell though, but it is worth a look. 

Thanks for the suggestion. Creating a button in the toolbar to send ctrl-space should work (even though a native solution is more desirable)

![IMG_0049](https://user-images.githubusercontent.com/18236342/216280233-a3636c75-b224-4562-9723-d76649fa9468.jpeg)

**Comment by m-zheng** [comment]
Closed as this feature is kind of an edge case. It can be reopened if more people need it.
