### ISSUE TITLE
[Question] Does updating a-shell also update the sub-modules that come with it?

### ISSUE THREAD

**Issue by myfingerhurt** [holzschu/a-shell#569]
I use a-shell with SW-DLT, which is usually reliable, but sometimes it breaks. 

Today, after upgrading a-shell to the latest version (I'm not sure how to check the version number), I found that `yt-dlp` was no longer working. I went to their GitHub page and discovered that the issue had already been fixed with the latest version released on February 17, 2023. 

This brings me to my question: Does updating a-shell also update the sub-modules that come with it?

![IMG_4526](https://user-images.githubusercontent.com/12622279/221343934-4901d033-048c-4fee-852c-4e50bd199040.jpeg)

I fixed the issue by running `pip install yt-dlp -U`

**Comment by holzschu** [comment]
Updating a-Shell updates all the modules that come sub-modules with it, but not the sub-modules that were installed by the user. It's up to the user to upgrade them by themselves.

**Comment by myfingerhurt** [comment]
Thanks for getting back to me so quickly. I will close this issue.
