### ISSUE TITLE
Customizing prompt with .bashrc - what's feasible?

### ISSUE THREAD

**Issue by CarlyRaeJepsenStan** [holzschu/a-shell#570]
Hello again friends and developers, I've successfully crafted a **bash** specific custom prompt: 

<img width="572" alt="Screen Shot 2023-02-25 at 9 20 21 PM" src="https://user-images.githubusercontent.com/44917034/221393771-66a3a6ff-34aa-40d2-baac-e52ae65658c3.png">

Here lies the source code, which I tried to make as reading-friendly as possible: 

```bash
blue="\\033[38;5;019m"
lightblue="\\033[38;5;069m"
purple="\\033[38;5;099m"
pink="\\033[38;5;171m"
steel="\\033[38;5;081m"
salmon="\\033[38;5;209m"
green="\\033[38;5;119m"
reset="\\033[0m"

function baseprompt {
echo "${blue}${reset} ${lightblue}\u${reset} ${purple}⊏${reset} ${pink}\h${reset}
 ${steel}\w${reset} "

}

function cleanicon {
echo "${salmon}⌀${reset} "
}
function dirtyicon {
echo "${green}○${reset} "
}

# begin git processing

function modify {
gitstatus=$(lg2 status 2> ~/test.txt | head -1)
if [[ ${gitstatus:0:1} == "O" ]]; then # Looking for "On branch main" 
        pushstatus=$(lg2 status --porcelain | tail -n1)
        if [[ -n $pushstatus ]]; then
	  export PS1="$(baseprompt)$(cleanicon)"
        else
          export PS1="$(baseprompt)$(dirtyicon)"
        fi
else 
	export PS1="$(baseprompt)"
fi 
}
PROMPT_COMMAND=modify
```

While this functions perfectly on my own computer (a MacBook), it appears like this on my a-shell:

![IMG_0001](https://user-images.githubusercontent.com/44917034/221393863-f1e0e51d-a8e4-44f6-bad5-bdba60944d74.jpeg)

Evidently, while the color codes are functioning, the "shortcut" variables to display path, etc aren't working.  Also, function is not a keyword in sh (but it is in bash) ?!?  

But then I tried something like this:

```
export PS1="\u\h\w "
mobileiPad~/Documents echo hello world
hello world
```
Very strange.

Buoyed by this positive result, I turned .bashrc into simply

```bash
blue="\\033[38;5;019m"
lightblue="\\033[38;5;069m"
purple="\\033[38;5;099m"
pink="\\033[38;5;171m"
steel="\\033[38;5;081m"
salmon="\\033[38;5;209m"
green="\\033[38;5;119m"
reset="\\033[0m"

export PS1="${blue}${reset} ${lightblue}\u${reset} ${purple}⊏${reset} ${pink}\h${reset}
 ${steel}\w${reset} "
```

But then my prompt turned into something definitely incorrect, without any backslashes.

I sincerely hope this extensive error report will lend some insight into how extensively I can customize my terminal! What am I doing wrong, what is simply impossible, and what kind of future does customizing the prompt on a-shell have?

Edit: I did a little experimenting and theorize this unpredictable behavior is coming from some mixup between dash and bash:

![IMG_0003](https://user-images.githubusercontent.com/44917034/221394924-39192b1a-09ee-4aea-be60-b7f1f23abb85.jpeg)

Furthermore, trying to make random variables (like typing `a="1"`) will either say "command not found" or will execute perfectly.  I'm really at a loss to explain what's happening.

**Comment by holzschu** [comment]
a-Shell is running a very, very simple shell, with very limited command parsing (when you need more abilities, you can run dash as a more advanced shell). 

I think you need to place this in your `.bashrc`:
```sh
export PS1="\033[38;5;019m\033[0m \033[38;5;069m\u\033[0m \033[38;5;099m⊏\033[0m \033[38;5;171m\h\033[0m\n \033[38;5;081m\w\033[0m "
```

For environment variables, `setenv a 1` works, `export a=1` works (both change the default environment), `a=1 command` works (it temporarily sets a to 1 then runs command), but `a=1` alone doesn't.

**Comment by CarlyRaeJepsenStan** [comment]
Thanks for the advice!  My goal with my custom prompt was to display something in my prompt indicating the git status of the current folder.  Given the limitations of a-shell, I gather it is not possible to use something like PROMPT_COMMAND to execute every time I type a command or change directories, and then display the git status?

**Comment by holzschu** [comment]
That's not a feature I have already implemented in a-Shell. 

dash has a different syntax for prompt customization, but it accepts backquoted commands so you could do it inside dash.

**Comment by CarlyRaeJepsenStan** [comment]
I see - I believe I've spent enough time on my prompt and also value colorful words over git information :P  Thanks for being in contact, and I'll be typing away on a-Shell!
