### ISSUE TITLE
support for stty?

### ISSUE THREAD

**Issue by tthkbw** [holzschu/a-shell#572]
a-Shell apparently has no stty. Can this be added? 

I am using cmd2 module in a python program and it works really well in a-Shell except that it prints an error "stty command not found" after each command is executed because stty is not available in a-Shell.

Is there a simple way to add stty?

**Comment by holzschu** [comment]
If we can find a source code, we can compile it to WebAssembly, I think.

**Comment by tthkbw** [comment]
I found the source code at https://github.com/coreutils/coreutils/blob/master/src/stty.c.

I knew I could compile C code for a-Shell, and that led me to the other issue I just posted :)

**Comment by holzschu** [comment]
That one seems to have many dependencies. We might have a better chance with this: https://github.com/apple-oss-distributions/adv_cmds/tree/adv_cmds-199.0.1 

(and if it fails to compile to WebAssembly, it should be feasible in Arm64).

**Comment by tthkbw** [comment]
for the purposes of this particular problem, we actually just need a no-op stty.

I had posted a question on the cmd2 issues forum and was able to solve the issue. Here's the link:

[No-op stty solution](https://github.com/python-cmd2/cmd2/issues/1263)

**Comment by holzschu** [comment]
That is a very fast and efficient solution. I'll still compile stty to Arm64 (it has too many dependencies to work with WebAssembly), but that's medium term solution.
