### ISSUE TITLE
Compiling and running simple C program

### ISSUE THREAD

**Issue by tthkbw** [holzschu/a-shell#573]
I'm sure I did this a few months ago, but now I can't get a simple C program (for example hello_world.c) to compile and run in a-Shell.

I am compiling the following:

```
#include <stdio.h>
int main(void) {
	printf("hello world");
	return(0);
}
```
It compiles wihtout error using clang, and creates a.out. However, 
'''
wasm a.out
```
fails with the message "Wasm: Error:".

I'm running iOS 16.3.1 on an iPad Pro.

What am I doing wrong?

**Comment by holzschu** [comment]
The short answer is that I have no idea. It works on my iPad. Does it affect all Wasm programs, or only the ones you created yourself? (you can check with the programs you install with `pkg`).

**Comment by tthkbw** [comment]
I installed banner using pkg and I get the same result:

```
[~/Documents/bin]$ ls
banner
[~/Documents/bin]$ wasm banner
wasm: Error : [~/Documents/bin]$ mv banner banner.wasm
[~/Documents/bin]$ ./banner.wasm
wasm: Error : [~/Documents/bin]$ 

```

**Comment by tthkbw** [comment]
Ha! I just fiddled with this some more, and restarted a-Shell. Now both banner and my hello_world work.
