### ISSUE TITLE
Invoke PageUp and PageDown keys from toolbar

### ISSUE THREAD

**Issue by agostonbarna** [holzschu/a-shell#585]
Hi,

I generated the .toolbarDefinition file with the config -t command and tried to add the PageUp and PageDown keys to the toolbar.

The keys appear on the toolbar after an app restart, but I cannot seem to make the buttons invoke the PageUp and PageDown keys.

This is what I added to the .toolbarDefinition file:
```
arrow.up    insertString \u{F72C}
arrow.down  insertString \u{F72D}
```

I'm not sure if I'm using the wrong unicode key codes, or these key codes are not supported by a-shell, but I get empty boxes after pressing these keys on the toolbar instead of invoking the keys.

I also tried it with the shell escape sequence `\e[5~` and `\e[6~` but no luck (well, there was no example in the file for this so it was more like a desperate try).

Motivation: the PageUp/PageDown keys are mapped to the history-search-backward/forward readline functions in bash on my server and make the shell history navigation a lot faster than the Up/Down keys or Ctrl-R.

Thanks,
Barna

**Comment by holzschu** [comment]
Indeed, currently, a-Shell does not use page-up or page-down. 

Alt-Up arrow and Alt-Down arrow will move 5 levels up and down in the history inside a-Shell's own shell, but if I read you correctly, this is for when a-Shell is connected to a server, so it's a different question. Then, the question is: how does your server encode page up and page down. I'm pretty sure it isn't with a unicode key code, but rather with a string combination (something like escape + something).

**Comment by agostonbarna** [comment]
Thanks for pointing me to the right direction.
As I have mentioned `\e[5~` and `\e[6~` didn't work, but it was close to the solution, only the escape key code had to be adjusted in the escape sequences.
With that said, I found two combinations that work on my server:
```
arrow.up    insertString  \033[5~
arrow.down  insertString  \033[6~
```
```
arrow.up    insertString  \u{001B}[5~
arrow.down  insertString  \u{001B}[6~
```
