### ISSUE TITLE
Package installing error

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#591]
```
[~/Documents]$ pkg install zip
wc: stdin: read: Bad file descriptor
/private/var/containers/Bundle/Application/6B8D50A5-EADB-4598-935D-82970D7F4F3E/a-Sh
ell.app/bin/pkg: 60: [: -eq: unexpected operator
/private/var/containers/Bundle/Application/6B8D50A5-EADB-4598-935D-82970D7F4F3E/a-Sh
ell.app/bin/pkg: 63: [: -eq: unexpected operator
Package name zip unclear. Did you mean:
```
`pkg search` works well. Any other info needed?

**Comment by holzschu** [comment]
I cannot reproduce the issue on any of my machines.
It could be caused by a poor internet connection, or it could be a bug that has been fixed in recent updates. Which version of a-Shell are you using?

**Comment by HeavySnowJakarta** [comment]
> I cannot reproduce the issue on any of my machines.
> 
> It could be caused by a poor internet connection, or it could be a bug that has been fixed in recent updates. Which version of a-Shell are you using? 

Ver 10.0.4, build 308

Should I reinstall the app?

**Comment by holzschu** [comment]
The TestFlight version is quite outdated compared to the AppStore version (because Apple takes longer to approve TestFlight version than AppStore versions, weird, I know). I would suggest installing the AppStore version.

**Comment by HeavySnowJakarta** [comment]
> The TestFlight version is quite outdated compared to the AppStore version (because Apple takes longer to approve TestFlight version than AppStore versions, weird, I know). I would suggest installing the AppStore version.
> 
> 

I've switched to the App Store version. Another problem occurred: 
```
$ pkg search
[~/Documents]$ pkg search unzip
Packages available:
[~/Documents]$ export PKG_SERVER=https://github.com/holzschu/a-Shell-commands
[~/Documents]$ echo $PKG_SERVER
https://github.com/holzschu/a-Shell-commands
[~/Documents]$ pkg search unzip
Packages available:
[~/Documents]$ pkg search
Packages available:
Not Found
```

It occurred on just newly installed a-shell today. Ver 1.11.0 (btw, how to get the version inside the app)

**Comment by holzschu** [comment]
unzip is part of the zip package. Once you installed zip, you also got unzip.

**Comment by HeavySnowJakarta** [comment]
> unzip is part of the zip package. Once you installed zip, you also got unzip. 

So does zip:
```
[~/Documents]$ pkg search zip
Packages available:
[~/Documents]$ pkg install zip
Package zip not found
```

**Comment by holzschu** [comment]
Again, it works on my machine. I suspect this may be caused by the value you gave to `$PKG_SERVER` earlier. Try `unsetenv PKG_SERVER`, then retry `pkg`.

**Comment by HeavySnowJakarta** [comment]
> unsetenv PKG_SERVER

Cool. This time it works fine.
