### ISSUE TITLE
vim: :set background=dark

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#592]
When changing the color scheme, I need to `:set background dark`, right? But it rejects:
```
E518: Unknown option: dark
Press ENTER or type command to continue
```
`:set background light` works, but not for dark. That's to say, when I change the color scheme, it looks unbearable:
![image](https://user-images.githubusercontent.com/54460050/228735171-353fdf38-bed2-4a45-85bc-bfcd11153166.png)

**Comment by holzschu** [comment]
On my machine, `:set background dark` gives the error `E518: Unknown option: dark`, but `:set background=dark` does work.

**Comment by HeavySnowJakarta** [comment]
> On my machine, `:set background dark` gives the error `E518: Unknown option: dark`, but `:set background=dark` does work.

That's because you are running the command on the vim window without a color scheme. Try to write the command into `.vimrc` file and load a color scheme, and you'll find it not working.
