### ISSUE TITLE
Native FFmpeg missing pipe functionality

### ISSUE THREAD

**Issue by grassybeetle144** [holzschu/a-shell#594]
Hello,

There's a strange problem I've been having with a-Shell using FFmpeg. 
When I run this command:
```
ffmpeg -i http://www.w3schools.com/tags/movie.mp4 -vn -f wav pipe: | cat > output.wav
```
`output.wav` is returned as an empty file. 

<br>

Upon further inspection, I found that reading from stdin with FFmpeg also does not work.
I ran this command, using a local wav file `hello.wav` as input:
```
cat hello.wav | ffmpeg -i pipe: output.wav
```
I received this error:
```
ffmpeg version n5.1.2-11-g30d432f205 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --cc=clang --arch=arm64 --disable-asm --enable-cross-compile --enable-pthreads --enable-videotoolbox --disable-audiotoolbox --enable-openssl --enable-libfreetype --enable-libzimg --enable-network --disable-debug --disable-gpl --disable-nonfree --enable-libmp3lame
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
pipe:: Invalid data found when processing input 
```

<br>

However, when I tried the command again using `ffmpeg.wasm` downloaded from https://github.com/holzschu/a-Shell-commands/releases/download/0.1/ffmpeg.wasm, the previous command ran successfully. Unfortunately, the `wasm` version is much slower (which is to be expected) and is configured with `--disable-network`, which I need enabled for my purposes.

I suspect that this issue on native FFmpeg has to do with the `--disable-gpl` configuration, but I'm very confused why pipes would fall under this because saving output to a file works just fine. I'm not sure if this can be fixed, but clarification on this issue would be greatly appreciated. Thanks in advance.

**Comment by holzschu** [comment]
I'm going to have a look. Starting pipes inside commands is difficult, but it works for most commands, so it should work with ffmpeg. I don't think it's related to `--disable-gpl`, more likely related to one command running much faster than the other (for example, `cat` starts, waits for `ffmpeg` to send data, `ffmpeg` hasn't started yet so `cat` thinks the input data is closed and terminates). But that doesn't explain the "Invalid data" in the second case.

**Comment by holzschu** [comment]
Thanks for raising that one. It was simply a case of ffmpeg sending the output to the wrong channel. It will be fixed in the next version.

**Comment by grassybeetle144** [comment]
Fixed! Closing this for now, thank you so much!
