### ISSUE TITLE
Would you know if there are any commands that work on both Mac and iOS, that can output OS information but gives different results on each platform? (As a way to detect if something is running on macOS or iOS)

### ISSUE THREAD

**Issue by YousufSSyed** [holzschu/a-shell#595]
There's nothing I need this for but am curious. I tried looking for a way to detect iOS and macOS with python looking at `os` and `platform` functions, but found nothing. Perhaps there's a command I could in run A-Shell that can say that its on iOS, and that same command works in macOS' Terminal (with Zsh) to say its on Mac?

**Comment by holzschu** [comment]
That's a question I have had to solve for myself. There are at least two ways to do this:
- the `TERM_PROGRAM` environment variable is set to `a-Shell` on a-Shell, and to something else (`Apple_Terminal`) on the Mac.
- inside Python code, I use:
```
if (sys.platform == "darwin" and os.uname().machine.startswith("iP")):
```
which first selects platforms running Darwin (MacOS and iOS), then selects machines that start with "iP", which covers iPhone, iPad and iPod touch.

**Comment by YousufSSyed** [comment]
Thanks for the answer!
