### ISSUE TITLE
Does Pyenv work on A-Shell or is there a way to run different Python versions?

### ISSUE THREAD

**Issue by YousufSSyed** [holzschu/a-shell#600]
I want to see if I can install Pywb, [but it doesn't work on 3.11](https://github.com/webrecorder/pywb/issues/835#issuecomment-1494495858).

**Comment by holzschu** [comment]
- there's no way to have several Python versions for the time being (because binaries have to ship with the app, that would require increasing the size of the app too much). That might change in the future.
- `venv` works for virtual environments (as long as you stick to pure Python packages):
    - `python -m venv env`,
    - followed by `source env/bin/activate` to activate the new environment,
    - `deactivate` to deactivate the environment.

**Comment by YousufSSyed** [comment]
Would it be possible for you / A-Shell to provide python versions to download onto the app after installing it?

**Comment by holzschu** [comment]
No, that is the main issue: anything that is a binary (a command or a dynamic library) has to ship with the app. Only non-executable files can be downloaded after the installation.

**Comment by YousufSSyed** [comment]
How come its possible to install pip packages but not python vesions like that?

**Comment by holzschu** [comment]
pip in a-Shell only works with "pure Python" packages, packages that only include Python files. If you try to pip install packages with dynamic libraries, C files or Cython files, you will see a failure as well.

**Comment by YousufSSyed** [comment]
Alright, thanks for the explanation.
