### ISSUE TITLE
Maybe ash is better

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#606]
`ash` is light, extendable and completely compatible with `bash`. What's more important, it's under MIT license.

**Comment by holzschu** [comment]
Based on the links I can find, `dash` is the latest version of `ash` (as in Almquist Shell), so I'd take the "completely compatible" claim with a grain of salt. But if you have a link to the source code for a different version of `ash`, I'll give it a try (there are many things called "ash", so finding exactly what you mean is difficult).

**Comment by HeavySnowJakarta** [comment]
> Based on the links I can find, `dash` is the latest version of `ash` (as in Almquist Shell), so I'd take the "completely compatible" claim with a grain of salt. But if you have a link to the source code for a different version of `ash`, I'll give it a try (there are many things called "ash", so finding exactly what you mean is difficult). 

I have to reconsider the question. "`ash`" I saw was just a "bash module". But I still think there is a more proper shell that is bash-user-friendly.
