### ISSUE TITLE
Support for Alpine Linux (Just like iSH)

### ISSUE THREAD

**Issue by Swarde11** [holzschu/a-shell#610]
I want to have support for alpine Linux just like iSH, so i can easily download packages (without the message “illegal instruction”, because people are struggling installing NodeJS)

**Comment by holzschu** [comment]
That was also suggested in #604.
I'm not saying no, but it's a lot of work, so it will take time. Also, it won't be fast. it will probably be slower than WebAssembly version (if it exists) and slower than iSH because both are using highly optimized emulators.

**Comment by HeavySnowJakarta** [comment]
Well if you want an emulator you have to use iSH. Commands of `a-Shell` _should_ be native to ensure efficiency. To support `node.js` projects, I would rather suggest using a perfect alternative than adding an emulator layer.
