### ISSUE TITLE
Dark mode setting

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#612]
I would prefer keeping the dark mode always open rather than follow the system setting.

**Comment by holzschu** [comment]
`config -f white -b black -gp` will do that. See `man config` or `config -h` for more information.

Short explanation: 
- `config -f white`: foreground color white
- `config -b black`: background color black
- `-gp`: applies to all windows (global) and makes it permanent (p)

**Comment by HeavySnowJakarta** [comment]
I know `config`, but I prefer
![image](https://user-images.githubusercontent.com/54460050/230759956-2e5975c1-002c-45f6-876f-3a9f63c4236f.png)
rather than
![image](https://user-images.githubusercontent.com/54460050/230759968-2eae8fa5-ce53-481d-ba1e-892d97e7c27b.png)

**Comment by holzschu** [comment]
Ah, I understand the question better, thank you.
I'm not sure it's always possible (in some cases, the toolbar is managed by the system, so it takes colors from the system). But I'll investigate.

**Comment by HeavySnowJakarta** [comment]
> Ah, I understand the question better, thank you.
> 
> I'm not sure it's always possible (in some cases, the toolbar is managed by the system, so it takes colors from the system). But I'll investigate. 
> 
> 

It's not a complex thing at all. You just need to add an option at the setting menu:
![image](https://user-images.githubusercontent.com/54460050/230760529-daa9ae9c-296c-4528-be3a-cf5f8939af57.jpeg)
You just need to support the dark mode since iOS 13, that's enough.

**Comment by holzschu** [comment]
I see what you mean. It took a bit of digging to get the right function call. The latest TestFlight build has this setting: https://testflight.apple.com/join/REdHww5C 

There's actually 4 possibilities: follow the system, follow the screen colors, always dark and always light.

**Comment by HeavySnowJakarta** [comment]
> I see what you mean. It took a bit of digging to get the right function call. The latest TestFlight build has this setting: https://testflight.apple.com/join/REdHww5C 
> 
> 
> 
> There's actually 4 possibilities: follow the system, follow the screen colors, always dark and always light.

That's it. Release it completely!
