### ISSUE TITLE
Shortcuts: shared folder between app and "in-extension"

### ISSUE THREAD

**Issue by 87435** [holzschu/a-shell#620]
Hi, 

I am trying to execute a python script in-extension. Is there a (writable) folder accessible by both the app and extension so I can write a script with the former, and execute it with the latter? 

Thank you

**Comment by holzschu** [comment]
All shortcuts (both in-app and in-extension) are executed in a shared folder, accessible by both the app and the extension, named `~shortcuts` or `$SHORTCUTS`.
