### ISSUE TITLE
Clang: error

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#621]
![image](https://user-images.githubusercontent.com/54460050/232382889-2b026cf4-c5ad-4501-8964-03f538878b82.jpeg)

**Comment by holzschu** [comment]
You need to compile C++ files with `clang++`, not `clang`.

**Comment by HeavySnowJakarta** [comment]
> You need to compile C++ files with `clang++`, not `clang`.

Ah, I forgot it
