### ISSUE TITLE
`file` errors out with videos as input

### ISSUE THREAD

**Issue by ringosham** [holzschu/a-shell#630]
Using the file command against a video will error out with `Wasm: Error`

a-shell 1.11.3, iPad OS 16.2

**Comment by holzschu** [comment]
I just tried and it works. I think it's more likely that webAssembly has an error. Try force closing a-shell and restarting it.

**Comment by ringosham** [comment]
Well, force closing and restarting a-shell does work.

Not sure what is the reason of this but I'll close this issue.
