### ISSUE TITLE
Chinese&Japanese inputting error

### ISSUE THREAD

**Issue by HeavySnowJakarta** [holzschu/a-shell#631]
On the current version Chinese and Japanese inputting don't work, affecting my i18n process. With them switched to, I can only input Latin characters instead of Han characters.

**Comment by holzschu** [comment]
It's easier for me to understand the origin of an issue and potentially fix it if I have a more complete description than "don't work".

After receiving this message, I opened my iPhone, switched to a Chinese keyboard, typed text, and observed that the Chinese keyboard did work (as it did in all my previous tests). Can you give more information here?

**Comment by HeavySnowJakarta** [comment]
Well it's harder for me to give a further description. You may see the video to understand the issue.
https://user-images.githubusercontent.com/54460050/233978320-4c772b32-ef7e-46b1-a3c5-8c4dfa0b8557.MOV

**Comment by HeavySnowJakarta** [comment]
> I think you could start by giving the full name of the "Chinese" keyboard you used (there are around 20 of them), and how it is expected to work. I used "Pinyin - QWERTY", which shows the ideograms corresponding to the roman letters I have typed so far, and lets me chose the best one, or automatically inserts one if there is no other choice.
> 
> 
> 
> As a basic rule, once text is inserted, it cannot be modified (hence the Korean keyboard and Vietnamese-Telex keyboard don't work, because they need to go back an modify a character that was typed before). 

I use Pinyin, for Simplified Chinese (简体拼音) and Japanese Roman characters (日本語ローマ字). They worked before but not for now.

**Comment by holzschu** [comment]
I am using the same keyboards and they still work. 
I've run more tests. I think you have the Settings "Use caps-lock as escape" activated; it interferes with keyboard input, in ways that I cannot avoid.

**Comment by HeavySnowJakarta** [comment]
> I am using the same keyboards and they still work. 
> 
> I've run more tests. I think you have the Settings "Use caps-lock as escape" activated; it interferes with keyboard input, in ways that I cannot avoid. 

That works. Thank you for your advice (actually it does not work for multi keyboards at all)
