### ISSUE TITLE
Can I use git command?

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [holzschu/a-shell#651]
Is there a way I can use `git` in a-Shell? I'm trying to install a python package from github using pip.

**Comment by ego-lay-atman-bay** [comment]
I probably should've looked around a bit mire.
https://github.com/holzschu/a-Shell-commands/blob/master/packages/git

**Comment by holzschu** [comment]
Hi, 
that is one of the fastest open-and-close issues ever.

To complete: you can install git with "pkg install git", but it's actually a layer around lg2, for licensing issues. For ordinary commands, there's little differences, but as you start using more complicated git commands, you will start encountering limitations (submodules, for example).

**Comment by ego-lay-atman-bay** [comment]
For some reason, just doing `git --version` (without it being installed), it asked me if I wanted to install it. Oh, and I had tried the same command before opening the issue, and it just said that git wasn't a command. I have no idea why.
