### ISSUE TITLE
Clang hangs after “segmentation fault”

### ISSUE THREAD

**Issue by RadioNoiseE** [holzschu/a-shell#657]
While I was trying to compile a tiny c program to web assembly in a-shell using clang, the compiler hangs after giving several “segmentation fault” errors:
![IMG_5706](https://github.com/holzschu/a-shell/assets/86350742/a26deb41-acb4-4ac6-8eb8-063b0bd111a3)
But however at present I can’t use my pc, so I’m not quite sure where actually the error comes from.

The source code is here for further investigations:
[JSTML.zip](https://github.com/holzschu/a-shell/files/11713884/JSTML.zip)
(It’s really just a small and dirty showcase, hence it’s not commented

**Comment by holzschu** [comment]
I'm going to have a look. That's a weird issue.

**Comment by holzschu** [comment]
Hi,
I have the answer. `clang` cannot compile multiple C files, I remember that now (it's a limitation connected to the fact that iOS does not have `fork()`, and one of the reasons I ported `make`...)

You'll need to compile each C file into an object file first, then link these:
```Makefile
.PHONY: complie
.SUFFIXES: .o
.c.o:
        clang -o ${.TARGET} -c ${.IMPSRC}

complie: asrtktp.o creattok.o jstml.o jstml.h jstparse.o scantok.o textokenize.o tokbuf.o
        clang tokbuf.o creattok.o scantok.o asrtktp.o jstparse.o textokenize.o jstml.o -o jstml.wasm
```
I see several linking errors afterwards (duplicate symbols) but I think you can fix these.

**Comment by RadioNoiseE** [comment]
I've tried, and it worked after solving a few linking problems.
Thanks very much for your help!
P.s. I've never realised how important `fork()` is![image](https://github.com/holzschu/a-shell/assets/86350742/eb9ce3bb-b7c0-4bf3-811b-bfff6e9b1b52)

**Comment by holzschu** [comment]
The whole project started more or less on a dare: `fork()` is an essential tool of all Unix commands, and is not available on iOS. How far can I go without it? It turns out the answer is "quite far", but there's a bug whenever a command starts itself (i.e. python launching python, sh starting another sh, clang starting another clang...) You just met one of these.
