### ISSUE TITLE
Lualatex problems

### ISSUE THREAD

**Issue by FMuro** [holzschu/a-shell#658]
Since the update to texlive 2023 I'm unable to use lualatex. I get the following message:

`LaTeX2e <2022-11-01> patch level 1
...3/texmf-dist/tex/luatex/lualibs/lualibs-basic-merged.lua:4145: bad argument 
#1 to 'find' (string expected, got nil)
stack traceback:
        [C]: in function 'string.find'
        ...3/texmf-dist/tex/luatex/lualibs/lualibs-basic-merged.lua:4145: in main chun
k
        [C]: in function 'dofile'
        ...y/texlive/2023/texmf-dist/tex/luatex/lualibs/lualibs.lua:96: in local 'load
module'
        ...ive/2023/texmf-dist/tex/luatex/lualibs/lualibs-basic.lua:44: in main chunk
        [C]: in function 'dofile'
        ...y/texlive/2023/texmf-dist/tex/luatex/lualibs/lualibs.lua:96: in local 'load
module'
        ...y/texlive/2023/texmf-dist/tex/luatex/lualibs/lualibs.lua:106: in main chunk
        [C]: in function 'require'
        ...023/texmf-dist/tex/luatex/luaotfload/luaotfload-init.lua:224: in upvalue 'i
nit_main'
        ...023/texmf-dist/tex/luatex/luaotfload/luaotfload-init.lua:590: in function '
luaotfload-init.lua'
        ...ive/2023/texmf-dist/tex/luatex/luaotfload/luaotfload.lua:322: in field 'mai
n'
        [\directlua]:1: in main chunk.
<everyjob> ...ring \\def\string \\encodingdefault{OT1}')end }
                                                  \let \f@encoding \encoding...`

**Comment by holzschu** [comment]
Hi, 
thank you for reporting this. I don't encounter this issue on my own install, so this is weird. I can see from your error message that lualatex is using the TeX install in `~/Library/texlive/2023`.

Looking at the source code and the line that corresponds to the error (line 4145 in `lualibs-basic-merged.lua`), it seems that `os.getenv("PATH")` did not return a string as expected, which is weirder. Could you check `echo $PATH`? Even better, make this small file:
```lua
#! /bin/lua
print(os.getenv("PATH"))
```
and execute it with `lua smallFille.lua`.

**Comment by FMuro** [comment]
Thanks a lot for your quick answer! Both commands output an empty string (blank line).

**Comment by holzschu** [comment]
Well, at least this empty string explains the behaviour of lualatex. That might be an issue for you in other places as well, since a-Shell and dash are looking for commands in the `$PATH`.

The problem will survive a remove-reinstall because a-Shell saves the environment variables and restores them, and iOS keeps that information after uninstalling. I see several fixes:
- in Settings, you can tell a-Shell to stop storing the content of the session and restoring it, at least temporarily. It should stop it from restoring the environment variables.
- you can set the PATH variable yourself using: `setenv PATH $APPDIR/bin:$APPDIR/Library/bin:$HOME/Library/bin:$HOME/Documents/bin` (possibly place this line inside your `.profile`).

**Comment by FMuro** [comment]
Thanks a lot! First proposed solution solved the problem. I’ll investigate the other ones if this shows up again.

I might have said that before but, as a fellow scientist I’d like to seize this opportunity to warmly thank you for your work in this app. I use it mostly for latex (also for some simple scripting and vim editing). This app makes getting an iPad worth for me, and it would make it worth even if this was the only existing iPad app (well, this and GoodNotes).

**Comment by holzschu** [comment]
Thanks a lot! I wrote the app first for myself (long ago, in 2018), then realized I could share it with others. So, yes, it's heavily geared towards our uses as fellow scientists. 
In recent additions, you can write text in Vim using the pencil, which allows me to be more focused during seminars and meetings (although the interaction with Vim requires having the floating keyboard to enter commands).
