### ISSUE TITLE
upTeX binding for pTeX

### ISSUE THREAD

**Issue by RadioNoiseE** [holzschu/a-shell#671]
Usually, we use the tool `ptex2pdf` which is a Lua script already available in a-shell to generate pdf from the TeX manuscripts. But calling it would result in `ptex command not found` error:
![image](https://github.com/holzschu/a-shell/assets/86350742/c8298e9d-bdac-44ba-af26-0b7d8605bc48)
Since in TeXLive, we bind pTeX to upTeX, just like what we did for TeX (`tex` actually calls `pdftex`) and upTeX itself (`uptex` calls `e-uptex`).

So maybe we should add the `ptex` command to the TeXLive distribution a-shell uses which is an alias for `uptex`.
![image](https://github.com/holzschu/a-shell/assets/86350742/084c0cd9-4fa9-4f1a-9984-782cf211de0c)
Right now, a simple `alias ptex uptex` in the `.profile` will work.

**Comment by holzschu** [comment]
Hi, 
thanks for the detailed explanation. I've tried adding ptex to the list of commands, but it fails because it cannot find the format file `ptex.fmt`. I would need to create the format file too. I think the `alias ptex uptex` is the best solution for now.

**Comment by RadioNoiseE** [comment]
> Hi, 
> 
> thanks for the detailed explanation. I've tried adding ptex to the list of commands, but it fails because it cannot find the format file `ptex.fmt`. I would need to create the format file too. I think the `alias ptex uptex` is the best solution for now. 

Just like `tex` results in `format tex.fmt not found`?

But there's another workaround: using `-u` option provided by `ptex2pdf` to explicitly call `uptex`.

Anyway thanks for your reply and this great app!
