### ISSUE TITLE
libgit2 pulling from self-hosted git server

### ISSUE THREAD

**Issue by LevinCeglie** [holzschu/a-shell#672]
I am trying to pull a git repository from a self-hosted git server. The connection is configured and working via the ssh config file under the name `homegit`. That is to say that `ssh homegit` is working properly. But when I try to use it with `lg2` to pull a repository from it I get the following error:

```
[Memory]$ lg2 pull origin
Fetching origin for repo 0x105c4f360
Bad news:
 failed to resolve address for homegit: nodenam
e nor servname provided, or not known
```

PS: I did already try to reinstall the app. Let me know if further explanation is needed, I am happy to elaborate.

**Comment by holzschu** [comment]
Hi, 
that one is puzzling. I didn't think reinstalling was going to help (it almost never helps, anyway).

ssh and libgit2 have different config files, so you might have to duplicate some information (some lines have to be present in both `.ssh/config` and `.gitconfig` or `repository/.git/config`).

Let's try analyzing from the information provided. You said `lg2 pull origin`, so you have already cloned the repository, and you are inside the repository. The command line said `failed to resolve address for homegit`, so `lg2` knew that the server name is `homegit`, so it has read the configuration file and found the name of the server. `homegit` is not a valid hostname, so presumably you have it aliased in `.ssh/config` to something else. But I don't think `lg2` is reading `.ssh/config`, so it doesn't know about that alias, hence the error message: it doesn't know to which server it should send the connection request.

You're probably going to have to edit the repository config file `.git/config` file to change the name of the server. Let me know if I missed something.

**Comment by LevinCeglie** [comment]
Hi
First of all thank you very much for the quick reply. 
Nice analysis of the problem and your solution worked!! All I had to do was to add the necessary information to `.git/config`, namely: user, host and port.

Thank you!
