### ISSUE TITLE
Homebrew support?

### ISSUE THREAD

**Issue by Tama47** [holzschu/a-shell#686]
Is it possible to have homebrew support with a-Shell?

**Comment by Tama47** [comment]
Thanks for the answer! I am looking to run mpv (command line media player) on iOS. Is that at all possible with a-Shell or any other package? I am aware of [Outplayer](https://github.com/OutplayerApp), but would like to use mpv.

**Comment by holzschu** [comment]
Try "play" or "view". Both commands use iOS to display movies and images. If that doesn't fit your needs, VLC is available on the AppStore. mpv itself would be difficult to cross-compile, I think.

**Comment by Tama47** [comment]
Okay, thanks!
