### ISSUE TITLE
APT installation?

### ISSUE THREAD

**Issue by DeBeast591** [holzschu/a-shell#69]
Could the APT package manager be added? If there is already a way to install it then just tell me, there is no info online that works on a-Shell.

**Comment by holzschu** [comment]
No, there are no package managers currently working on a-Shell. There are several issues at work here. One is that AppStore rules explicitly forbid package managers. The other is that even though we have a working compiler and SDK, we are not yet at the point where we can pull any package source and compile it. There are OS limitations (no fork), WebAssembly limitations (no sockets), a-Shell limitations (no user input)...

A repository of pre-compiled commands is available here: https://github.com/holzschu/a-Shell-commands 
It's not as practical as apt, but it's: download the wasm binary, place it in `~/Documents/bin`, run the command.

**Comment by DeBeast591** [comment]
Ok, thank you for the info.
