### ISSUE TITLE
Using put file shortcut

### ISSUE THREAD

**Issue by ifuchs** [holzschu/a-shell#70]
I'm trying to use the put file shortcut. a-shell says file created but where is it? ls does not show it in Documents.

**Comment by ifuchs** [comment]
It would appear that the shortcut invocation of a-shell starts in a different directory than the app but one can cd  between them.

**Comment by holzschu** [comment]
All sortcuts are running in the same directory, `$SHORTCUTS`. You can always move files to the main directory or use the "Get File" shortcut to get the file back. 

The "main directory" is not the same if the shortcut is running "In Extension" or "In App", hence the use of a neutral ground.
