### ISSUE TITLE
How to switch default login shell to dash?

### ISSUE THREAD

**Issue by Iridium-Lo** [holzschu/a-shell#706]
and then source .profile? chsh cmd is not available.

**Comment by holzschu** [comment]
There is an option in Settings that makes it that, if dash was running when you left a-Shell, then it will be restarted when you restart a-Shell.

**Comment by holzschu** [comment]
It's one of the very few things in a-Shell that use the iOS user interface.
- leave a-Shell
- there is an app on your iPad or iPhone called "Settings" (or the translation if your interface language is not English).
- open it and scroll down to "a-Shell".
- there is one option "Restart Vim or dash after closing a-Shell". It is unchecked by default, set it to on.
- from then on, if dash was running when a-Shell went in the background, it will be restarted.

IIRC, my motivation for putting this option outside of a-Shell usual system of commands was the following: you can create a situation where the app becomes unresponsive or impossible to use. I wanted to provide users with a way to control the situation outside of the app.

**Comment by holzschu** [comment]
The `.profile` *is* automatically sourced when a-Shell is started. It is a limited version of `source`, though: each line is executed independently (you cannot have `if` or `for`) and there is no output yet because the `.profile` is executed while the system is still busy creating the window.

**Comment by holzschu** [comment]
They should be supported. Try enclosing the prompt in quotes, or with "\\n" instead of "\n". Colour codes work.
