### ISSUE TITLE
Can't change A-Shells default font anymore

### ISSUE THREAD

**Issue by ByAzuraByAzuraByAzura** [holzschu/a-shell#710]
Config -n no longer lets me change A-Shells default font to an installed third party custom font (like Fira code or source code pro). The command used to trigger the iOS device font picker popup but now it just results in an error message.

**Comment by holzschu** [comment]
Hi,
I think I've fixed the issue with the font selector in the TestFlight version: https://testflight.apple.com/join/REdHww5C 
If you can give it try? I'll submit an AppStore update too.
