### ISSUE TITLE
F_NOCACHE not supported in a-Shell

### ISSUE THREAD

**Issue by lbuczkow** [holzschu/a-shell#715]
The program below reads a file which can be changed in background so F_NOCACHE flag must be used. The program works OK on mac but does not work as expected when built with clang in a-Shell (the file is read from cache rather than from the external drive). F_NOCACHE is not defined and providing the value explicitely does not help. 

Is this a limitation of iOS or the feature just has not been implemented in a-Shell?

The flag seems to be defined in SDK (https://github.com/xybp888/iOS-SDKs/blob/master/iPhoneOS13.0.sdk/usr/include/sys/fcntl.h).

```
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdint.h>

#define F_NOCACHE 48

int main(int argc, char *argv[])
{
  int fd;
  off_t disk_off;
  int ret;

  char buf[80] = {0};

  fd = open("a_volatile_file.txt", O_RDONLY);
  if (fd < 0) {
    printf("disk open error: %s\n", strerror(errno));
    exit(1);
  }
  fcntl(fd, F_NOCACHE, 1);
  ret = read(fd, buf, sizeof(buf) - 1);
  if (ret == -1) {
    printf("error reading from device %s\n",strerror(errno));
    exit(1);
  }
  printf("%s\n", buf);
  close(fd);
}
```

**Comment by holzschu** [comment]
I don't know if the feature works in iOS. a-Shell compiles C programs to WebAssembly (using wasi-sdk), and as you found WebAssembly does not have the notion of `F_NOCACHE`. wash-libc implementation of fcntl is minimalist: https://github.com/WebAssembly/wasi-libc/blob/main/libc-bottom-half/cloudlibc/src/libc/fcntl/fcntl.c 

I have already extended WebAssembly, to provide access to the local filesystem. I could try to extend it further and add the other fcntl options, to be sent to the system.

**Comment by lbuczkow** [comment]
It turned out that F_NOCACHE cannot be relied upon to bypass the cache. Reading from the file is done directly, as long as the read data is not already in the cache (another process can open the file without F_NOCACHE). In this case, the data is returned from the cache. I think it is not worth implementing this feature in WebAssembly.
