### ISSUE TITLE
Extension no longer has access to folders from `pickFolder`

### ISSUE THREAD

**Issue by n8gray** [holzschu/a-shell#729]
I’m trying to build a shortcut that will do some git operations in another app’s sandbox. 
* I’ve used `pickFolder` to create a bookmark to that folder called `LogSeq`.
* I’m running a script to `cd` to that folder and do the work
* The script works when run in the full app, but doesn’t work in the extension
* I’ve tried using the full path to the folder instead of the bookmark. Neither way works
* I believe this used to work? I’m basing this belief off comments from people in the LogSeq community who used this workflow in the past, but I’ve never personally used it before.

![IMG_0022](https://github.com/holzschu/a-shell/assets/82794/c70cbb0b-c3ed-4fa4-b207-a46ef3bea219)

Thanks!

**Comment by holzschu** [comment]
From Apple's point of view, the App and the extension are two different apps, with different permissions. The extension does not have access to the same folders as the app (and reciprocally). They have a few bookmarks in common (`~iCloud` and `~shortcuts`/`~group`), but that's it.

**Comment by n8gray** [comment]
Thanks for the reply! The "Working Copy" app makes this work somehow. You can make shortcuts that operate on a repo in the LogSeq sandbox without bringing Working Copy to the foreground. I suspect there's a way to configure your entitlements so that the extension and the app share these acquired permissions. I'll do some research this weekend and see if I can find the info.

**Comment by holzschu** [comment]
Thank you for pointing out that it was possible; I may have found out how to do it. I'm implementing it.

**Comment by n8gray** [comment]
Awesome, great to hear it.

**Comment by holzschu** [comment]
Not for now. I'm back to "I have no idea how this could work".

**Comment by Emasoft** [comment]
How Working Copy does it?

**Comment by holzschu** [comment]
Apple documentation explicitly says that this is impossible. I have no idea how Anders Borum does it with WorkingCopy, and I think the only way to know would be to ask him directly.

**Comment by mdbraber** [comment]
@holzschu tnx - I first had to figure out what is exactly the Shortcut Item where this is used, but yes it indeed works in Working Copy (Pro Version):

1. Create a new repository in Working Copy with "Link to external directory" and e.g. select On iPhone > Obsidian > <Vault name> as the folder
2. Create a Shortcut with an action "Get Repository Files", select the Repository Created and select the path to a test file e.g. `/Test.md` which is in my `On iPhone > Obsidian > Notes` directory
3. Switch to Obsidian and make a test edit in the `Test.md` file
4. Switch back to Shortcuts and run the Shortcut: it indeed shows the updated content!

So somehow Andreas is able to make this work (which is nifty!) Let's see if we can ask him if he would be able to shed some light on he is able to get this to work!

**Comment by palmin** [comment]
Working Copy will run most of its Shortcuts actions from the main binary (while staying in the background) as the memory limits are a little relaxed compared to an intent extension. A side effect is that security scoped bookmarks made by the main app worjk.

I'm not 100% sure this is the whole story but I would try this is a first thing.

**Comment by mdbraber** [comment]
Thanks for thinking along @palmin! I have to get a bit acquainted with the code (and Intents API), but would this mean that `NSExtensionPointIdentifier` would not be `com.apple.intents-service` or `NSExtensionPrincipalClass` has to be changed?

**Comment by palmin** [comment]
This video describes how to handle intents in the main app:
  https://developer.apple.com/wwdc20/10073

**Comment by holzschu** [comment]
Thank you for the explanation, @palmin! If the Shortcuts actions are run from the main app, not the extension, that explains everything.

**Comment by mdbraber** [comment]
With my limited knowledge of building iOS apps, this does seem rather possible as most of the Intent logic is already there. It seems that handling intents can be simplified as we don't need to repeat code as is now done in e.g. `IntentHandler`. 

@holzschu what do you think? Would it be feasible to change from running apps in the extension to running from the main app?

**Comment by WigsExp** [comment]
I don't now how can't you do because may order coming department application az management thes all

**Comment by mdbraber** [comment]
Absolutely right - I didn't make myself clear. I meant to ask if it's feasible to run Shortcuts "in app but in the background" as Anders mentioned. Would be great if this something which could be implemented.

**Comment by n8gray** [comment]
Great to hear this is feasible! I think a lot of workflows could benefit from the ability to run in-app without bringing the app to foreground.

**Comment by mdbraber** [comment]
![image](https://github.com/holzschu/a-shell/assets/1781890/94dbc866-c9a8-4b99-83b3-63fb7fa19b69)

I've got it working in XCode / development - I'll clean up the code, test some more and submit a PR

**Comment by holzschu** [comment]
The TestFlight version ( https://testflight.apple.com/join/REdHww5C ) had the PR by @mdbraber and offers the possibility to run Shortcuts commands "in the app but in the background", so you can access the bookmarks created by pickFolder (and also run Python packages and Python commands).

**Comment by mdbraber** [comment]
Thanks @palmin for the pointer in the right direction!
