### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by DavidTheDev556** [holzschu/a-shell#735]
How do I change my username, so when I run whoami, the user is not mobile, but the one I chose. I added an env variable But it doesn't change anything. I used: export USERNAME='myusernamehere'.

**Comment by holzschu** [comment]
I don't think you can change what `whoami` shows. It's using system calls to query the password database, which cannot be changed. You can change the username that is displayed on the prompt (`\u`), but that's not the same (it will use 
$USERNAME, $USER and $LOGNAME, in that order).
