### ISSUE TITLE
Perl script that open up a webserver does not show up on local web browser, hang and does not respond to ctrl-C

### ISSUE THREAD

**Issue by jiang-qian** [holzschu/a-shell#736]
I really appreciate your spending such energy and ingenuity to make a-shell, which makes iPad OS much more useful! It is a shame to waste a nice piece of hardware on such restrictive and limited OS!

Please pardon my not being an experienced developer, so I may need a bit of help to get to the bottom of the issue.

I am trying to get a very useful piece of special software for  Greek and Latin readers to work in a-shell. It is basically a perl script that serves up a web interface in a localhost and then the user access that web interface via a browser.

When I run the attached perl script in a-shell it does not throw any error and gave a correct message
Startup complete. You may now point your browser at this address:
http://127.0.0.1:8888
I put a-shell and safari side by side in ipadOS multitasking mode, and point my web browser to that address and nothing happen. Sometimes in the a-shell I could not even do ctrl-C to kill the perl script and have to close the entire shell.

Then I downloaded the testflight beta and use internalbrowser http://127.0.0.1:8888 on a new a-shell window 
and nothing shows up either. Indeed, I just run internalbrowser www.google.com and nothing shows up.

If the attached perl script does not run, you might need to have the other diogenes files but I can share with you that.
[diogenes-server.txt](https://github.com/holzschu/a-shell/files/13635757/diogenes-server.txt)
(I could not upload .pl extension so I changed the ending to .txt)

I would really appreciate it if you could be patient with me and let me know what other debugging this issue. If there is a need to modify the perl script perhaps you could point to me a few hints about how to do it?

(I have no problem with say starting a python web server like python3 -m http.server in a-shell Then I can access the files within a-shell using safari running side by side in iPad mulittasking mode)

**Comment by holzschu** [comment]
Thanks for reaching out and for the kind words. 
The short answer is that Perl is much more challenging to run inside a-Shell, especially as a server or a background process. I'm not sure it will be possible to make it work.

I'll have a look at your script. It needs to install extra modules (such as HTTP/Daemon.pm) which may also be a cause for trouble.

**Comment by jiang-qian** [comment]
I really appreciate it that you reply so quickly!

Is it harder for perl to run as a background server than python? I have friend who wrote a python based dictionary that also use web server and he got it to run successfully using internalbrowser.

For me somehow internalbrowser does not work at all? I simply run internalbrowser www.google.com and nothing happens? I am on the latest test flight.

Here is the full program needed to run the above script. No extra things are needed and I can run it just fine with no error on a-shell. Just no webpage is served...

https://drive.google.com/file/d/1Kzq20rwVruua6KmhIuGQZ9l225jMRfor/view?usp=sharing
You can untar it (tar xfz) then the just run the perl script
diogenes/server/diogenes-server.pl

In any case, if you don't mind taking a quick look, just to make sure there is no quick  & dirty solution to get it run on a-shell, I'd really appreciate it!

If there is no other way  I will concede defeat! I can always run the server on my android phone (termux) and then use ipad to browse it.

But iPad has such powerful (and for iPadOS overpowered ) chip---M1 in mine is laptop grade---that it feels really sacrilegious to use it just as a dumb terminal. I was hoping that with a-shell I can take full advantage of this powerful piece of hardware! (Diogenes can be CPU intensive when doing searches".

Please keep up with the good work in making the software (iPadOS and iOS) living up to the potential of its hardware!

**Comment by holzschu** [comment]
Hi, 
thanks for the files. I've been running them, and the answer is much easier than I expected: there is no fork() system call on iOS, so I'm cheating by emulating the behaviour of fork().

But Diogenes is using the fork call in a way that I did not expect. The good news is, Diogenes already has code for a fork-less server, for Windows. We'll use this code, with  bit of tweaking. If you go to line 185, you will see `if ($Diogenes::base::OS eq 'windows')`. Replace this line by `if (1)`, so we always go throught the non-forking version. Comment lines 187 to 199 (we won't fork, like, at all) and line 212 (to match the opening brace on line 199, which you just commented out). That works. 

You can use either Safari or the internalbrowser as the browser, both work. I wonder if you could replace the line that prints the address with a line that starts a command to open a browser.

The bad news is that there's nothing in the code to listen to user input and terminate the server, so the only way is to kill a-Shell (using the three dots at the top of the window). I don't think that's a major issue.

**Comment by jiang-qian** [comment]
That's wonderful to hear! I can't thank you enough for working through this issue so effectively! I will test it out later today and report back how it works on my end!

**Comment by jiang-qian** [comment]
It works!  I can report that, after adding the databases, Diogenes now works like a champ! With the internalbrowser it is also extremely speedy, too! I cannot express how grateful I am to be able to take full advantage of the hardware with the help of a-Shell. 

I will also report to the author of Diogenes, a Classics professor in the UK, that his program now can run on iOS as well!

Classical scholars are, by and large, not very tech savvy. But in time I am sure this niche of a niche, running Diogenes on a-shell, will find their users, too! Thank you again for making a-shell such a versatile iOS tool!
