### ISSUE TITLE
Codemirror not saving changes

### ISSUE THREAD

**Issue by 0507spc** [holzschu/a-shell#748]
When I download a particular file and edit it in codemirror it does not save the changes.

````
curl https://raw.githubusercontent.com/code
mirror/theme-one-dark/main/src/one-dark.ts > one-dark.ts

codemirror.sh one-dark.ts
````

Make any change, save and quit, then open file again and changes won't have saved.

**Comment by holzschu** [comment]
That should have been fixed by the recent new release of codemirror. Can you try reinstalling it (pkg install codemirror) and check again?

**Comment by 0507spc** [comment]
It has! Thank you. Didn't realise I needed to update. Thanks for the heads up. Thanks.
