### ISSUE TITLE
Can a-shell use Python packages built for Mac?

### ISSUE THREAD

**Issue by Crissium** [holzschu/a-shell#749]
I developed a Python package with C++ but `pip install` failed due to the problem as mentioned in #652. But I have also uploaded binaries built for Mac (both x86_64 and arm64), which seemed to have been ignored by pip. So is it possible to use these binary packages at all?

I see there are many bundled Python packages that come with a-shell. Are these compiled with a regular C compiler or the clang in a-shell that produces WebAssembly?

It's a pity that the user can only install pure Python packages. But anyway we must thank you for all the effort you have spent in building a fully usable terminal for iOS!

**Comment by holzschu** [comment]
Thanks for reaching out. This is an interesting question.
For security reasons, you cannot add any binary to an app after it has been approved by Apple: the approval process must see the entire app, with all its functionalities. Or rather, you can add binaries, but the app cannot execute them.

For this reason, the app ships with a lot of bundled packages (the most essential ones). These are compiled with a regular C compiler, after being edited in a few places where iOS differs from OSX: 
- no access to $HOME, only to $HOME/Documents so all configuration files have to move.
- stdin, stdout, stderr do nots exist, they are replaced with thread-local versions (thread_stdin, thread_stdout, thread_stderr).
- no fork()/exec() mechanism for parallelism, it is replaced by threads.
The repository to generate Python and all the associated packages used in a-Shell and Carnets is here: https://github.com/holzschu/cpython

To make things worse, there are differences between the binary format used in OSX and the binary format used in iOS, so you cannot take a binary generated for OSX and use it in iOS (on top of the differences between the file systems).

Which of your Python packages were you trying to add to a-Shell?

**Comment by Crissium** [comment]
Thanks for your detailed explanation! Much appreciated. I now understand why a-Shell can only make use of pure Python packages.

I was trying to install [this one](https://github.com/Crissium/python-dsl), which doesn't read from the filesystem, nor prints anything or reads any input from stdin. And no parallelism is utilised. But probably it is too special-interest to be included in a-Shell since the only functionality is to translate a special format into HTML. Anyway the pure Python alternative works well enough on powerful Apple chips…
