### ISSUE TITLE
How to enable developer mode on IOS 17.5 by a-Shell

### ISSUE THREAD

**Issue by pxgri** [holzschu/a-shell#762]

**Comment by holzschu** [comment]
I do not know what "developer mode" is. Do you have some references?

**Comment by pxgri** [comment]
Lockdown is the best but I still want deploy from Android ... So we have and bonuses like Dev Mode

**Comment by pxgri** [comment]
On pip install rust I have problem the code is return 1; and it have to be return 0; So I don't have a PC to revoke

**Comment by pxgri** [comment]
rustup: unknown CPU type: iPhone13,2
My phone is 12 edition , but with Developer Beta 17.5 is showing 13,2

**Comment by NobodyXu** [comment]
FYI the lockdown is imposed by Apple: anything in app store cannot sideload another app, e.g. compile to native arm code and run it.

a-shell workaround it by having gcc compile code to wasm and run it interpreter mode

**Comment by pxgri** [comment]
👍Sent from my iPhoneOn 21 Apr 2024, at 13:08, Jiahao XU ***@***.***> wrote:﻿
FYI the lockdown is imposed by Apple: anything in app store cannot sideload another app, e.g. compile to native arm code and run it.
a-shell workaround it by having gcc compile code to wasm and run it interpreter mode

**Comment by pxgri** [comment]
Can you tell the a-shell command for interpreter mode

**Comment by NobodyXu** [comment]
> Can you tell the a-shell command for interpreter mode

I'm sorry but I didn't get it.

**Comment by holzschu** [comment]
Any command compiled to WebAssembly will be executed if it's typed on the command line (try "file" or "tree"). a-Shell will detect that it's a WebAssembly binary and execute it. If you want to force it, you can call "wasm" followed by the name of the WebAssembly file: "wasm a.out".

**Comment by pxgri** [comment]
I know but here is written that the IPhone doesn't have the module or it's not registered as apple Silicon Valley's ... May be LockDown mode is higher than dev settings...

**Comment by pxgri** [comment]
I found it the Rust pkg can't get installed on iOS ... it's abandoned on the system

**Comment by holzschu** [comment]
"here is written that the IPhone doesn't have the module": what do you means by that? (a screenshot would help me understand you). It's very likely that the Lockdown mode prevents you from executing WebAssembly files, yes.

"the Rust pkg can't get installed on iOS": once again, you *cannot* add binaries to an existing app. It's impossible technically as well as legally. There are no "packages" that can get installed to an existing app. It's not just Rust, it's *everything*. Developer mode is about adding new apps, not about adding modules to existing apps.

**Comment by pxgri** [comment]
I’m only with IPhone … I don’t have PC…
