### ISSUE TITLE
Cannot install ssh-copy-id

### ISSUE THREAD

**Issue by kkebo** [holzschu/a-shell#768]
I can't install ssh-copy-id via the `pkg` command.

```console
$ pkg list
base64
gawk
getopt
hexdump
mktemp
seq
sqlite3
ssh-copy-id
which
zip
$ pkg install ssh-copy-id
Package ssh-copy-id not found
```

My environment:

- a-Shell 1.14.1 (400) (TestFlight)
- iPadOS 17.5 (21F5073b)
- iPad Pro 12.9-inch 6th generation

**Comment by holzschu** [comment]
Ah, thanks for pointing that out. It's now installed by default, as I realized that it doesn't make sense to make it a downloadable command (very small size, used very often). But I forgot to remove it from the package list.

**Comment by kkebo** [comment]
Thank you very much. I didn't noticed that.
