### ISSUE TITLE
Flex and Bison

### ISSUE THREAD

**Issue by aagudeloz** [holzschu/a-shell#773]
Are these tools available and how can I install them?

**Comment by holzschu** [comment]
These are GNU tools, so they cannot be installed with the app. They would have to be compiled to WebAssembly. That seems feasible. I'll give it a try once I've finished updating the C compiler and SDK.

**Comment by aagudeloz** [comment]
Thanks, I'll be watching.

**Comment by holzschu** [comment]
Hi, 
some preliminary reports: I cannot compile bison to WebAssembly. It has an entire mechanism to call external commands that will be too complicated to disable, even though it seems to be used only once or twice, for pretty-printing the output.

I'll try with flex and yacc; when searching for the source of flex, I saw that there's pure Python implementation of lex and yacc, which are probably a better choice given the limitations: http://www.dabeaz.com/ply/ or https://github.com/dabeaz/sly

**Comment by holzschu** [comment]
**Update:** I'm also unable to compile flex to WebAssembly. `ply` seems to be your best solution.
