### ISSUE TITLE
Please Oh Please Oh Please support libxml2 it is such a nice xml library

### ISSUE THREAD

**Issue by eddo888** [holzschu/a-shell#78]
Collecting libxml2-python3
  Downloading https://files.pythonhosted.org/packages/41/97/a2ecf6c5b291799dbd40b3d041d89b0ecdb1b43c8c2503e27991325851cd/libxml2-p
ython3-2.9.5.tar.gz (216kB)
     |████████████████████████████████| 225kB 4.8MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: failed to find headers for libxml2: update includes_dir
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/mobile/Containers/Data/Application/7AD86E0D-1A9
0-4C56-A9EA-9A6B5F942459/tmp/pip-install-9ykj2cui/libxml2-python3/
$ 

**Comment by eddo888** [comment]
I sorted this issue, try using py3-libxml2 instead, it works a treat. as does py3-lxml

**Comment by f1shy-dev** [comment]
> I sorted this issue, try using py3-libxml2 instead, it works a treat. as does py3-lxml
How did you solve this? I'm trying to use lxml and am failing, and have no idea what `py3-lxml` is.

**Comment by holzschu** [comment]
a-Shell now has lxml included by default in the Python distribution. Can you tell me what errors you are seeing, since you say that you are failing?
