### ISSUE TITLE
Strings command

### ISSUE THREAD

**Issue by jpferrero** [holzschu/a-shell#783]
I've just discovered this project and it's awesome! It would be nice to include 'strings' command from binutils into the wash repo!

Thanks

**Comment by holzschu** [comment]
I'm going to see if I can find the source code for that. That's the command that displays all the character strings inside a binary, right? There's already `hexdump`, available as a downloadable command (`pkg install hexdump`); it's not the same but it might help while I find the source, compile and install strings. I have to warn you, an app does not have access to the binaries of other apps, and also does not have access to most of the system binaries, and all of these are usually encrypted, so `strings` might not work.

**Comment by holzschu** [comment]
The GNU version is now available for download, using `pkg install strings`.
I have to make a correction: strings actually works pretty well with the system binaries (those in /System/Library).

**Comment by jpferrero** [comment]
Installed and using it! Thank you very much much!
