### ISSUE TITLE
Incorrect path, I do not know how to access the files path

### ISSUE THREAD

**Issue by HODAKdev** [holzschu/a-shell#796]
Hello, after several commands, I get into the group folder, and if I create something there, the file does not appear in the files app in a-Shell. It should be the Documents folder, just like when I installed the app, but now I can't access it. Even "cd .." doesn't work.
![IMG_8373](https://github.com/holzschu/a-shell/assets/82084934/b1bab854-14de-4d01-a87a-c492c25db708)

![IMG_8374](https://github.com/holzschu/a-shell/assets/82084934/18217599-e4c9-4bce-aa60-748bca70606a)
I need this folder “Documents”
![IMG_8375](https://github.com/holzschu/a-shell/assets/82084934/280bc9ac-df5e-4ae0-82b5-09e9b9217659)

**Comment by holzschu** [comment]
Hi, 
yes, the `~group` folder (also named `~shortcuts`)  is the folder where Shortcuts are executed, for practical reasons. The folder that appears in the Files app is `~/Documents`. You can always copy files and directories from the `~group` folder to the main folder with, e.g. `cp myFile.mp4 ~/Documents` or `mv myFile.mp4 ~/Documents`.
