### ISSUE TITLE
Internalbrowser (webview) doesn't display text picker UI

### ISSUE THREAD

**Issue by 2gn** [holzschu/a-shell#798]
# Steps to reproduce
1. `internalbrowser https://google.com`
2. Try to select texts by long pressing on texts
3. Text will be selected, but the text picker UI (blue transparent overlay) doesn't appear

# Expected behavior

Normally, text selection should look like this

![image](https://github.com/user-attachments/assets/dcfec2fb-89de-46f3-a1f1-8f91da704386)

This is extremely useful when editing code on webview based code editors like `ace`, `monaco` and `codemirror`.

**Comment by holzschu** [comment]
I followed the steps, and got this result, which seems to be the expected behavior:
![IMG_0487](https://github.com/user-attachments/assets/5a1a4c7f-d0b0-4627-b3b4-21f9699a24d7)
We’re going to need more tests about when this happens, in order to fix it.

**Comment by 2gn** [comment]
I'm on a-Shell v1.15.0 on iPhone OS. I'll check if it happens on my iPad.

I just tried it on Testflight version and when I open https://google.com, it did showed the text picker. However, webview based code editor still doesn't show anything like that.

**Comment by holzschu** [comment]
On my phone, I have the blue transparent overlay, but not the handles with Google and ace-editor, I have the blue transparent overlay and the handles with codemirror. To the best of my knowledge, there are no differences between the iPhone and iPad code, so it must be something weirdly specific.

**Comment by 2gn** [comment]
Confirmed it's not a issue anymore
