### ISSUE TITLE
【Vim】if_lua

### ISSUE THREAD

**Issue by suliveevil** [holzschu/a-shell#80]
Would you please add if_lua for Vim？So that we can use neocomplete.

**Comment by holzschu** [comment]
Thank you for raising this issue. Everything to enable the lua interpreter is present in the build file, just like for the python interpreter. So if_lua should be included, even though it isn't. I'm going to investigate.

**Comment by holzschu** [comment]
Found it. It will be fixed in the next version.

**Comment by nodecentral** [comment]
Hi

Is it there now? 
If so how do you make use of it ?

**Comment by suliveevil** [comment]
I gave up using Vim plugins on iPadOS.
Dependency hell is painful.
