### ISSUE TITLE
Clang and clang++ not working

### ISSUE THREAD

**Issue by ivansigmund** [holzschu/a-shell#809]
When attempting to compile C and C++ programs using clang and clang++ in the a-shell iOS app, the compiler is failing to find standard header files, resulting in compilation errors. Specifically:

![image](https://github.com/user-attachments/assets/315d0f5f-c7ee-4e94-b34b-40e97bfa28cf)
1. For C programs (start.c):
   Error: 'bits/alltypes.h' file not found
   Location: /var/mobile/Containers/Data/Application/062BDAA2-A689-4CC4-B3A4-B2C39C898AA5/Library/usr/include/wasm32-wasip1/stdio.h:28:10
![image](https://github.com/user-attachments/assets/79cda7cf-b02d-4463-b11e-754caee16aa6)
2. For C++ programs (proba.cpp):
   Error: 'iostream' file not found

These errors occur even when trying to compile simple "Hello World" programs. Multiple compilation attempts with different compiler flags (-Wall, -std=c++11) yield the same results.

Possible causes:
1. Incomplete or misconfigured C/C++ standard library installation in the a-shell environment

Before i did not have this problem 
Afterwards the program asked me to install llvm-18
Then it did not compile afterwards 
I tried deleting the program 
And install the test flight a-shell program 
It still did not work

**Comment by holzschu** [comment]
I cannot reproduce these issues on my machines. The headers in question *are* included in llvm-18, so my best guess is that something went wrong during the install of this package. I would suggest re-installing llvm-18 with `pkg install llvm-18`.

**Comment by ivansigmund** [comment]
> I cannot reproduce these issues on my machines. The headers in question *are* included in llvm-18, so my best guess is that something went wrong during the install of this package. I would suggest re-installing llvm-18 with `pkg install llvm-18`. 

You are right. I restarted my iPhone, reinstalled llvm-18 and it worked fine this time.

**Comment by holzschu** [comment]
Thanks. I am relieved that it works now.
