### ISSUE TITLE
Query - clear cookie for internalbrowser

### ISSUE THREAD

**Issue by m-zheng** [holzschu/a-shell#820]
Hi Nicolas,

Thanks for creating this amazing app. I am just wondering if it possible to clear cookie used in the internal browser launchged by the `internalbrowser` command. Any help would be appreciated!

Regards,
Ming

**Comment by holzschu** [comment]
The cookies seem to be stored in `~/Library/Cookies/Cookies.binarycookies`. It's a simple data file, and you can remove it with `rm ~/Library/Cookies/Cookies.binarycookies`.
