### ISSUE TITLE
X11 + Docker + Distrobox = Linux!

### ISSUE THREAD

**Issue by Swarde11** [holzschu/a-shell#822]
if you don’t know what is distrobox, it’s a project to run any linux distribution inside your terminal, and i want docker because distrobox needs it!

and i want an X11 server for running GUI apps!

**Comment by NobodyXu** [comment]
I was just going to say that's impossible because iOS forbids running unsigned binaries, but then I realized that Euro iOS being able to side load App, so perhaps it'd be possible.

**Comment by FNsi** [comment]
Any update?
