### ISSUE TITLE
Support PiP for play command 

### ISSUE THREAD

**Issue by gferreroferri** [holzschu/a-shell#825]
Support PiP for play command

**Comment by holzschu** [comment]
I'm pretty sure I included PiP in the play command since the beginning. I just checked on my Phone, and it works:
![image](https://github.com/user-attachments/assets/3fd50ba4-7f47-42ae-ba7d-73deffc693ab)

It seems to not work on iPads, but then that would be a limitation of the system.

**Comment by gferreroferri** [comment]
Sorry, yes. It does.  Not sure why on my first trial it did not allow me. Closed

Guillermo Ferrero

El 22 sept 2024, a las 20:36, Nicolas Holzschuch ***@***.***> escribió:

﻿

I'm pretty sure I included PiP in the play command since the beginning. I just checked on my Phone, and it works:
image.png (view on web)<https://github.com/user-attachments/assets/3fd50ba4-7f47-42ae-ba7d-73deffc693ab>

It seems to not work on iPads, but then that would be a limitation of the system.
