### ISSUE TITLE
Text dump when opening app

### ISSUE THREAD

**Issue by jackharro** [holzschu/a-shell#826]
G'day,

I used curl and less to view some raw HTML. Now whenever I open the app, it concatenates the text to the screen

See https://youtube.com/shorts/k1CQ-lRyqNc for demo

**Comment by holzschu** [comment]
Thanks for the report. That connects with another issue that was reported to me elsewhere : moving to the background immediately after a "clear" command cancels the effects of that "clear" command.

You have the option in "Settings" to deactivate the fact that a-Shell keeps and restores the app content when it moves to the background.

**Comment by jackharro** [comment]
Wait iOS settings? lol I forgot to check there for configs.

**Comment by jackharro** [comment]
Haha, thanks and sorry.
