### ISSUE TITLE
[wasm3] Some Wasm binaries are no longer executable since 1.15.7 (432)

### ISSUE THREAD

**Issue by kkebo** [holzschu/a-shell#838]
## Description

Some Wasm binaries are no longer executable on wasm3 since 1.15.7 (432). The version fixed other wasm3 issues, so I think this is a regression.

## Steps to reproduce

sample file: [swift-format.wasm.zip](https://github.com/user-attachments/files/17480149/swift-format.wasm.zip)

1. Download the file above
1. Unzip it
1. Run `wasm3 swift-format.wasm --version`

## On a-Shell 1.15.4 (428) (Expected behavior)

```console
$ wasm swift-format.wasm --version
main
$ wasm3 swift-format.wasm --version
main
```

## On a-Shell 1.15.7 (432) (Actual behavior)

```console
$ wasm swift-format.wasm --version
main
$ wasm3 swift-format.wasm --version
Failure loading function: path_filestat_set_times for module wasi_snapshot_preview1: function signature mismatch
swift-format.wasm: could not link with Wasi: function signature mismatch.
```

**Comment by holzschu** [comment]
That one was connected to many other issues...

At the beginning of a-Shell, webAssembly was not reading 64 bit integers, so I added parameters to the functions that set time for files (`path_filestat_set_times` and `fd_filestat_set_times`). It fixed the issue, but it made a-Shell version of wasi-sdk incompatible with the standard wasi-sdk (which is bad), and I recently made the same change to `wasm3` (between build 428 and 432), and that is why it broke.

The best solution, for the future, is to set the wasi-sdk back to its original number of parameters, since it now works. But that means I have to check all Wasm compiled binaries, and recompile them if they use one of these two functions (that's the case for zip, unzip, swift-format...)

**Comment by holzschu** [comment]
While working on that issue, I think I have found another issue: in wasm3, readdir() does not work recursively, that is it doesn't work if there is a directory inside the directory. Do you have the same issue?

**Comment by kkebo** [comment]
> readdir() does not work recursively

If I understand correctly, that's the expected behavior, isn't it?

https://kozmicluis.pro/blog/list-directories-c/

**Comment by holzschu** [comment]
Good point. So, the issue is that ripgrep does not work with wasm3 and a directory that contains another directory (it works well otherwise), while wasm has no issue. `wasm3 rg` reports "file does not exist error". I'm investigating, but that means there will likely be another change in `readdir`.

**Comment by kkebo** [comment]
Rust programs usually use `std::fs::read_dir()`. It calls `fd_readdir()`, not `readdir()`. Those two functions are different.

- https://github.com/search?q=repo%3ABurntSushi%2Fripgrep%20readdir&type=code
- https://github.com/rust-lang/rust/blob/4cc494bbfe9911d24f3ee521f98d5c6bb7e3ffe8/library/std/src/fs.rs#L2684
- https://github.com/rust-lang/rust/blob/4cc494bbfe9911d24f3ee521f98d5c6bb7e3ffe8/library/std/src/sys/pal/wasi/fs.rs#L174
- https://github.com/rust-lang/rust/blob/4cc494bbfe9911d24f3ee521f98d5c6bb7e3ffe8/library/std/src/sys/pal/wasi/fd.rs#L164

ripgrep is also a Rust program. By any chance, is it using `fd_readdir()` (`std::fs::read_dir()`) instead of `readdir()`?

- https://github.com/search?q=repo%3ABurntSushi%2Fripgrep+readdir&type=code

**Comment by holzschu** [comment]
Internally, all webAssembly programs that use `readdir()` get back to `fd_readdir()`. It took a while, but I now have a version of `fd_readdir()` (as used by ripgrep) that works with`wasm3`, which makes `rg` *much* faster. 
It's on TestFlight (build 433) if you want to test.

**Comment by kkebo** [comment]
Now, swift-format works perfectly on a-Shell 1.15.7 (433). Thank you!
