### ISSUE TITLE
sqlite3 not working

### ISSUE THREAD

**Issue by coin723** [holzschu/a-shell#857]
I recently tried creating a DB and a table with sqlite3 delivered for a-shell.

However it resulted in a crash as below.
```
[~/Documents]$ sqlite3 test.db 
SQLite version 3.39.3 2022-09-05 11:02:23
Enter ".help" for usage hints.
sqlite> CREATE TABLE example_table (name text, sample_val integer);
wasm: TypeError: Invalid mix of BigInt and other type in bitwise 'and' operation.
[~/Documents]$  
```

Which part would be the cause of this problem?

**Comment by holzschu** [comment]
That's probably related to the recent change in the webAssembly interpreter. I've recompiled sqlite3 and updated it. Try re-installing it with "pkg install sqlite3" (the new binary is 926553 bytes and it works on my side).

**Comment by coin723** [comment]
Following your instruction, it seems working properly. Thank you for your swift response!
