### ISSUE TITLE
Issues handling SIGINT (Ctrl-C)

### ISSUE THREAD

**Issue by sultanqasim** [holzschu/a-shell#858]
I’ve seen various different behaviours with handling of SIGINT (via Ctrl-C) in apps included with a-Shell (as of version 1.15.8).

1. In Python, when you press Ctrl-C, a KeyboardInterrupt does not happen until you press return.
2. When I try to ssh to an unreachable or mistyped IP address (example `ssh user@192.168.99.99`), ssh just hangs, and I can’t cancel it with Ctrl-C. I have to kill A-shell to exit.
3. With the current (2018 era) bc, pressing Ctrl-C from an interactive prompt causes a-Shell to enter a strange state where it’s neither presenting a prompt for bc, nor presenting a shell prompt.
4. With the updated bc (in the TestFlight build you shared for #854), pressing Ctrl-C from an interactive prompt causes a-Shell to crash.

Also relevant to this: #350 #538 #854

**Comment by sultanqasim** [comment]
I experimented with a few more programs to see how Ctrl-C is handled:

1. `ping` handled Ctrl-C normally (stopping the ping, showing summary results, exiting and returning to the shell)
2. `perl` handled Ctrl-C normally (exiting and returning to the shell)
3. `lua` **did not** handle Ctrl-C properly (it ended the REPL but didn’t return to the shell; similar behaviour to the old/current 2018-era bc)
4. `vim` handled Ctrl-C normally (displaying a message saying how to exit)

For reference, I’m testing on iPadOS 18.1.1 and iOS 18.1.1.

**Comment by sultanqasim** [comment]
I also confirmed the behaviour is the same on iOS 16.7.10.

**Comment by holzschu** [comment]
Thanks for this extensive testing. I've fixed the behaviour for lua and bc (it will be in the next TestFlight version, and then in the next release). I'll try ssh next.

**Comment by sultanqasim** [comment]
Regarding ssh, I may have used the term “unreachable” loosely. In general, if you try to ssh to a server for which a route (theoretically) exists but the server doesn’t respond (because the port is closed, or it’s off, or doesn’t exist), ssh still waits a long time trying to connect to it before timing out. It would be nice to be able to cancel that operation with Ctrl-C without needing to wait 30 seconds or whatever the timeout is, as would be possible on a normal shell.

~~~
[Documents]$ ssh user@192.168.95.28
ssh: connect to host 192.168.95.28 port 22: O
peration timed out
~~~

**Comment by holzschu** [comment]
Yes, that one is going to be more difficult to do; we're touching the limitations of iOS here.

**Comment by holzschu** [comment]
The new version is available on TestFlight with the fixes for ^C in bc and lua.

**Comment by sultanqasim** [comment]
Thanks, bc, dc, and lua now handle Ctrl-C properly. I’m guessing iOS makes it tricky to interrupt network calls by SSH (since you can’t just kill the process when everything is in the same process).

That just leaves the bug of Python not registering the Ctrl-C until a newline.

**Comment by holzschu** [comment]
I don't see a way to fix that one (basically, Python only handles keyboard input when there's a newline). Anyway, I would recommand `ipython` for running Python interactively: it has autocomplete, history, syntax colouring...

This may change with the update to Python 3.13, which is my next big change.
