### ISSUE TITLE
Odd escape handling by dash for tr

### ISSUE THREAD

**Issue by sultanqasim** [holzschu/a-shell#859]
I was debugging a shell script that wasn’t working properly in a-Shell and came upon the following odd behaviour. Consider the simple command `echo "hello world" | tr ' ' '\n'`. On the built-in shell, it works as expected:

```
[~/Documents]$ echo "hello world" | tr ' ' '\n'
hello
world
```

However, in dash, it doesn’t seem to understand the \n escape sequence for newline:

```
[\w]$ echo "hello world" | tr ' ' '\n'
hellonworld
```

This results in breakage of scripts. Any idea what’s happening here?

**Comment by sultanqasim** [comment]
Also, for reference, running dash on my Linux machine (version of dash available for RHEL 9), it also works as expected (as long as you use double quotes for escaped strings).

```
$ echo "hello world" | tr " " "\n"
hello
world
```

**Comment by holzschu** [comment]
That was another interesting issue. In the communication between dash and iOS_system, I only enclose between quotes arguments where I feel that I need to enclose them between quotes. Anything with a space in it was detected as important, but not arguments with a "\" in it, resulting in the "\n" being unprotected, and then changed into "n".

**Comment by sultanqasim** [comment]
Thanks, it seems to work correctly in the new version.

**Comment by sultanqasim** [comment]
While the particular issue I pointed out here was fixed, the script that led me to encounter this issue still didn’t work until I made a change around the usage of tr for newline substitution. I’m trying to make a minimal reproducer for that issue.

**Comment by sultanqasim** [comment]
I’m still trying to make a minimal reproducer for the remaining issue, but what I’m seeing is a super wacky bug that’s probably unrelated to the quote escaping issue you fixed here.

**Comment by sultanqasim** [comment]
I finally made a minimal reproducer for my remaining issue, and it’s super weird.

~~~sh
#! /bin/sh

foo() {
        _zzz="" # without this line, the bug doesn't happen
        printf "apple\npear\npeach\norange\n"
}

s=$(foo | tr '\n' ' ')
echo "unquoted" $s
echo "quoted '$s'"
~~~

The output is as follows:

~~~
[~/Documents]$ ./repro3.sh
unquoted apple pear peach orange
quoted 'apple
pear
peach
orange'
~~~

Even though the call to `tr` for newline removal seems to have worked, the same variable when quoted has a value that is as if `tr` never ran.

**Comment by sultanqasim** [comment]
Here’s another funky manifestation of this bug:

~~~sh
#! /bin/sh
foo() {
        _zzz="" # without this line, the bug doesn't happen
        echo "apple pear peach orange"
}
bar() {
        echo "apple pear peach orange"
}
a=$(foo | tr 'a' 'b')
b=$(bar | tr 'a' 'b')
echo "a:" $a

foo() {
        _zzz="" # without this line, the bug doesn't happen
        echo "apple pear peach orange"
}

bar() {
        echo "apple pear peach orange"
}

a=$(foo | tr 'a' 'b')
b=$(bar | tr 'a' 'b')
echo "a:" $a
echo "b:" $b
~~~

Running it gives the following results:

~~~

[~/Documents]$ ./repro4.sh
a: apple pear peach orange
b: bpple pebr pebch orbnge
~~~

Note that `tr` has no effect in the first case (calling the function `foo`), but it works normally in the second case (calling the function `bar`).

**Comment by holzschu** [comment]
I *think* that one is a known unfixable issue. In the usual world, Dollar-parenthesis forks as a new process and evaluates its content. It's one of the few times where fork() is not immediately followed by exec(); instead dash keeps the copy of the parsing tree and evaluates it. That's what allows dash to call functions inside the parenthesis, but not something I can do easily on iOS (this entire project started, five years ago, with "there's no fork() on iOS; how can I replace fork() with what's available (threads)?". Turns out I can do fork()+exec() relatively easily, but not fork() where the two process have the same memory content).

I'm going to investigate to be sure. If that's unfixable on the inside, the fix would be to have a few more lines of code in the script: first evaluate the function, then pass it through `tr`.

**Comment by holzschu** [comment]
I ran more tests, before diving into the code.
- only the first line of the function is sent through the pipe. It doesn't matter whether this first line is a builtin command (like echo, pwd, printf) or a regular command.
- all the other lines of the function are evaluated, but not sent through the pipe, just sent to the standard output.

**Comment by sultanqasim** [comment]
> I ran more tests, before diving into the code.
> 
> * only the first line of the function is sent through the pipe. It doesn't matter whether this first line is a builtin command (like echo, pwd, printf) or a regular command.
> * all the other lines of the function are evaluated, but not sent through the pipe, just sent to the standard output.

This explains the second example I shared (with foo and bar functions behaving differently). I still don’t understand the first example where directly echoing the variable and echoing the same variable through quotation interpolation give different results.

**Comment by holzschu** [comment]
I still don't fully understand it either; maybe the second quotation mark makes it a second redirection, which somehow breaks things.

In the meantime, I've tracked the issue to a place in the code where there's a comment (by me) that says that it's something to be fixed, but there's no easy way to do it... I'm going to trust the wisdom of old me here.

**Comment by sultanqasim** [comment]
> I _think_ that one is a known unfixable issue. In the usual world, Dollar-parenthesis forks as a new process and evaluates its content. It's one of the few times where fork() is not immediately followed by exec(); instead dash keeps the copy of the parsing tree and evaluates it. That's what allows dash to call functions inside the parenthesis, but not something I can do easily on iOS (this entire project started, five years ago, with "there's no fork() on iOS; how can I replace fork() with what's available (threads)?". Turns out I can do fork()+exec() relatively easily, but not fork() where the two process have the same memory content).
> 
> I'm going to investigate to be sure. If that's unfixable on the inside, the fix would be to have a few more lines of code in the script: first evaluate the function, then pass it through `tr`.

I don’t know what ios_system is doing under the hood (I haven’t looked), but naively thinking out loud, what you could do in cases where a function is being called through dollar-parentheses instead of a separate program:

1. Stash the current stack variables and flush stdout before the dollar-parenthesis
2. Redirect stdout to a temporary FIFO
3. Populate the stack with the called function arguments
4. Evaluate the function
5. Restore the stack to the caller’s state
6. Flush stdout to the temporary FIFO, then point it back at where it was in the caller
7. If output is piped: connect the stdout FIFO to stdin of the next stage, and create a new stdout FIFO for this new stage. If the piped command is a separate program then run it through an emulated fork+exec, else if it’s a function or builtin evaluate the next function that the output is piped to sequentially.
8. Repeat step 7 for every stage in the pipe chain
9. Put the contents of the final stdout FIFO in the destination variable

**Comment by sultanqasim** [comment]
I’d say the first bug (that this issue was initially created for) is fully fixed.

Regarding the second bug (around piping output the multi-line functions), I did some more testing of my own and figured out what was happening regarding the first example. When you echo an unquoted multi-line variable, newlines are automatically replaced by spaces, and this is correct behaviour unrelated to the `tr` call. The bug is that in multi line functions whose output is piped, only the first line goes into the pipe, and the rest goes straight to stdout.

I will close this issue as fixed, and make a separate issue about piping multi-line functions.
