### ISSUE TITLE
R command

### ISSUE THREAD

**Issue by macOneOone** [holzschu/a-shell#872]
Hello @N-Holzschuch,

I stumble on r command where suggest to type “old name” to “new name” and set a new name. So I decided to give a try to the command and nothing happens. Also try to find the location of the script or executable and I got `WASI Exit error:1` instead. I also look into info or man page but couldn't find anything related to the command.
Could you tell me if r is related to shortcut for move rename or anything?

**Comment by holzschu** [comment]
Hi,
The "r" command is part of a set of commands to manage bookmarks (l, p, g, s, d and r). It's not related to the R programming language. It's the equivalent of the "renamemark" command: it renames a bookmark that you have already created (usually with the pickFolder command).
