### ISSUE TITLE
aws cli

### ISSUE THREAD

**Issue by DM1145** [holzschu/a-shell#93]
Could the aws cli be installed into a-shell?

**Comment by holzschu** [comment]
I'll have a look, but at first glance it seems like a very difficult case. AWS seems to depend on many other packages that haven't been ported yet, including node.js and git.

**Comment by DM1145** [comment]
My apologies.   I was referring to the AWS CLI.  Much more reasonable to run command-line.
Install notes here for x86, OS X, and Linux:
https://github.com/aws/aws-cli/tree/v2

renamed the ticket accordingly.

**Comment by holzschu** [comment]
I have been told that the Python version of awscli works: https://pypi.org/project/awscli/
You will need to set up the two environment variables: 
```
setenv AWS_SHARED_CREDENTIALS_FILE ~/Documents/.aws/credentials
setenv AWS_CONFIG_FILE ~/Documents/.aws/config
```
I have no way to test this.

**Comment by DM1145** [comment]
I was able to install using “python -m pip install --user awscli”

**Comment by DM1145** [comment]
further:
after creating a .profile file and adding the environment variables above, I was able to successfully run "aws configure" and connect to resources.

Success!!!

**Comment by holzschu** [comment]
Hi, `pip install awscli` worked for me.
