### ISSUE TITLE
Shell scripts ere not executed

### ISSUE THREAD

**Issue by jaclu** [holzschu/a-shell#96]
The script is chmod  755
I have tried with both #!/bin/sh and #!sh in the 1st line

Calling methods attempted:
test.sh
./test.sh
~/Documents/test.sh

So far I always get command not found

**Comment by holzschu** [comment]
Yes, executing an entire shell script is extremely complicated. Basically, it requires porting an entire shell. It is on the todo list, but it won't be easy. 

In the meantime, Shortcuts can run a sequence of commands, and they can be stored in a file. You can have tests depending on the result in Shortcuts.
